SUI-Components/sui

- .github/README_TEMPLATE.md
- README.md
- packages/sui-babel-preset/README.md
- packages/sui-bundler/README.md
- packages/sui-component-dependencies/README.md
- packages/sui-cz/README.md
- packages/sui-decorators/README.md
- packages/sui-i18n/README.md
- packages/sui-lint/Readme.md
- packages/sui-mono/README.md
- packages/sui-precommit/Readme.md
- packages/sui-react-domain-conector/README.md
- packages/sui-ssr/README.md
- packages/sui-studio/README.md
Documentation for packages to be migrated
> Docs for upcoming packages

- packages/sui-lint/bin/sui-lint-js.js
- packages/sui-lint/bin/sui-lint-sass.js
- packages/sui-lint/src/helpers.js
Abstract duplicated code. 
Improvements: 
colors not trimmed from original output. 
Shell option now makes bin to execute from where sui-lint was execute, not file location.
@miduga and @carlosvillu please review
> refactor(sui-lint): refactor sui-lint

- packages/sui-helpers/packages.js
- packages/sui-lint/bin/sui-lint-sass.js
- packages/sui-mono/README.md
- packages/sui-mono/bin/sui-mono-link.js
- packages/sui-mono/bin/sui-mono.js
- packages/sui-precommit/Readme.md
- packages/sui-studio/README.md
- packages/sui-studio/bin/sui-studio-link-all.js
- packages/sui-studio/bin/sui-studio-link.js
- packages/sui-studio/bin/sui-studio.js
sui-mono link link all packages to each other (only if needed)
#21 
Please review @miduga @carlosvillu @naxhh
> Issue/21 Command sui-mono link

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-build.js
- packages/sui-bundler/package.json
- packages/sui-bundler/registerServiceWorker.js
- packages/sui-bundler/shared/index.js
- packages/sui-bundler/shared/precache.js
- packages/sui-bundler/webpack.config.prod.js
- packages/sui-helpers/package.json
- packages/sui-lint/package.json
- packages/sui-mono/package.json
- packages/sui-studio/package.json
- packages/sui-studio/src/components/demo/index.js
Update sui-bundler with last changes from suistudio-webpack
@carlosvillu & @miduga please review
**Sorry for the commits of releases that are out of scope ^^**
> Update sui bundler

- packages/sui-mono/bin/sui-mono-release.js
> Dont publish private packages

- packages/babel-preset-sui/lib/index.js
- packages/babel-preset-sui/package.json
Add Legacy Decorators plugin.
ISSUES CLOSED: #39
> feat(babel-preset-sui): add legacy decorators plugin to make compatible some packages

- packages/sui-bundler/webpack.config.prod.js
ISSUES CLOSED: #41
Move to prefetch instead using blocking preload for now.
> feat(sui-bundler): use prefetch instead preload to avoid blocking requests

- packages/sui-bundler/webpack.config.prod.js
Use contenthash instead chunkhash.
> fix(sui-bundler): use contenthash because chunkhash sometimes doesnt change

- .github/README_TEMPLATE.md
- .gitignore
- packages/sui-cz/config.js
- packages/sui-cz/package.json
- packages/sui-mono/README.md
- packages/sui-studio-create/package.json
- packages/sui-studio-create/src/index.js
- packages/sui-studio/bin/sui-studio-generate.js
Some improvements that I had pending. 2 are bug fixes.
@carlosvillu, @miduga please review
> Misc improvements

- README.md
- packages/sui-polyfills/README.md
- packages/sui-polyfills/package.json
- packages/sui-polyfills/src/index.js
Please, check @carlosvillu @davidbarna 
Create new SUI Polyfills package in order to load the needed polyfills on our components. To be used later on the SUI Bundler behind a configuration.
> feat(sui-polyfills): create sui-polyfills to be reused on all our projects

- packages/sui-studio-create/src/index.js
Fix traling comma un valid in package.json
> fix(sui-studio-create): wrong package.json generation

- packages/sui-bundler/webpack.config.dev.js
- packages/sui-bundler/webpack.config.prod.js
> fix(sui-bundler): fix problems with postCss because API changed for the loader

- packages/sui-mono/README.md
Update docs of sui-mono to reflect latest changes
> docs(sui-mono): update docs to reflect sui-mono changes

- packages/sui-hoc/package.json
> [sui-hoc] Improve npm scripts

- packages/sui-studio/src/components/documentation/try-require.js
ISSUES CLOSED: #76
When wrapped the component in a HoC we lost the API doc
solved #76 
@SUI-Components/developers Review!
> Search for component.js where there is one

- packages/sui-perf/README.md
Api of sui-perf changed but code examples where not updated
Update code examples so people trying the lib don't get confused by not printing any chart.
> docs(sui-perf): update code samples to add options call

- packages/sui-studio/package.json
Use the last version of the sui-bundler. this versión has v3 of webpack and offline features
> [sui-studio] Using V2 of the sui-bundler

- packages/sui-mono/bin/sui-mono-release.js
Tags are being created but not pushed 😢
> fix(sui-mono): push tags to the repo

- packages/sui-bundler/webpack.config.dev.js
- packages/sui-bundler/webpack.config.prod.js
include @schibstedspain/sui-studio inside the babel-loader
> [sui-bundler] Working inside the sui-studio

- packages/sui-studio-create/README.md
- packages/sui-studio-create/package.json
- packages/sui-studio-create/src/index.js
npm install after creating a studio in order to be ready to start hacking after creating it.
ISSUES CLOSED: #88
@naxhh please review
> feat(sui-studio-create): perform npm install after creating studio

- packages/sui-polyfills/package.json
> feat(sui-polyfills): bump core-js version to be in sync with the one used by babel

- packages/sui-mono/bin/sui-mono-release.js
The error was "/bin/sh: sui-mono: command not found"
@SUI-Components/developers please review
> fix(sui-mono): fix error on sui-mono release

- packages/sui-bundler/CHANGELOG.md
- packages/sui-bundler/package.json
- packages/sui-bundler/plugins/loader-options.js
Sui-bundler was broken in windows environment
@naxhh and @miduga please review
> [sui-bundler] Hotfix/path separator breaks windows build

- packages/sui-studio/bin/sui-studio-build.js
- packages/sui-studio/bin/sui-studio-deploy.js
- packages/sui-studio/bin/sui-studio.js
- packages/sui-studio/package.json
New sui-studio command for deploy
Was used to publish this: https://sui-components.now.sh/
#92
@SUI-Components/developers please review
> Issue/92 Add deployments to now.sh

- packages/sui-mono/bin/sui-mono-release.js
The command needs to be executed in the root of the repo, like release command.
Any command that uses isMonoPackage() func needs to be executed with right cwd as this functions depends on the cwd to determine if the current repo is either mono package or multipackage.
@miduga and @naxhh please review
> fix(sui-mono): fix changelog to generate log in right context

- packages/sui-studio/bin/helpers/cli.js
- packages/sui-studio/bin/helpers/file.js
- packages/sui-studio/bin/sui-studio-deploy.js
- packages/sui-studio/bin/sui-studio-generate.js
SPA was browseable in the frontend but inner links could not be shared to open a component directly
#92
@miduga and @carlosvillu please review
> fix(sui-studio): fix: SPA links don't work in deployments

- packages/sui-react-domain-connector/README.md
> [sui-react-domain-connector] update Readme

- packages/sui-polyfills/src/index.js
Add Array.prototype.find polyfill needed for IE11.
> feat(sui-polyfills): add array.find polyfill for IE 11

- packages/sui-studio/CHANGELOG.md
- packages/sui-studio/README.md
- packages/sui-studio/bin/sui-studio-run-parallel.js
- packages/sui-studio/bin/sui-studio.js
- packages/sui-studio/package.json
`sui-studio run-parallel` is 3 times faster that `sui-studio run-all`
> sui-studio run-parallel (rp)

- packages/sui-studio/CHANGELOG.md
- packages/sui-studio/package.json
- packages/sui-studio/src/components/demo/fetch-styles.js
Small improvements on error log in the studio, so they can be easily depurable on prod build.
> Fix sui studio error handling

- packages/sui-component-dependencies/package.json
> feat(sui-component-dependencies): update sui-theme dep

- packages/sui-studio/bin/sui-studio-generate.js
Generate now adds repository and homepage fields.
To avoid breaking changes, it will do it only if the fields is defined in studio's package.json
> [sui-studio] Generate repository field

- packages/sui-studio/bin/sui-studio-generate.js
> [sui-studio] improve generate

- packages/sui-mono/README.md
- packages/sui-mono/bin/sui-mono-commit-all.js
- packages/sui-mono/bin/sui-mono.js
> feat(sui-mono): commit-all command

- packages/sui-mono/package.json
> feat(sui-mono): assign sui-cz@1 to get new features

- packages/sui-component-peer-dependencies/package.json
> feat(sui-component-peer-dependencies): add prop-types@15.6 package

- packages/sui-widget-embedder/package.json
> fix(sui-widget-embedder): move @s-ui/bundler to pro deps

- packages/sui-studio/package.json
> feat(sui-studio): polyfills as vendor

- packages/sui-bundler/package.json
Update webpack to latest version.
> feat(sui-bundler): update to latest webpack version

- packages/sui-decorators/package.json
Remove private field in order to publish this package.
> fix(sui-decorators): remove private from package.json

- .gitignore
- packages/sui-widget-embedder/README.md
- packages/sui-widget-embedder/bin/sui-widget-embedder-dev.js
- packages/sui-widget-embedder/development/harmon.js
- packages/sui-widget-embedder/development/index.js
- packages/sui-widget-embedder/package.json
- packages/sui-widget-embedder/src-react/Widget.js
Fix issue to be used in page with login
> [sui-widget-embedder] Login pages

- packages/sui-domain/src/EntryPointFactory.js
- packages/sui-domain/src/index.js
Please review @carlosvillu 
Fixing: https://github.com/SUI-Components/sui/issues/161
> fix(sui-domain): fix being able to instantiate domain outside the domain package

- packages/sui-domain/src/EntryPointFactory.js
Please review @carlosvillu 
Pass as a parameter for all UseCases the config that we're using.
> feat(sui-domain): add config as param for all useCases

- packages/sui-widget-embedder/bin/sui-widget-embedder-build.js
- packages/sui-widget-embedder/downloader/index.js
- packages/sui-widget-embedder/downloader/sw.js
- packages/sui-widget-embedder/package.json
> [sui-widget-embedder] Add sw to precache assets

- packages/sui-lint/eslintrc.js
- packages/sui-lint/package.json
> feat(sui-lint): upgrade dependencies and support unused expression on chai

- .eslintignore
These fix is going to ignore anything inside this transpiled folder.
eslintignore file to avoid linting errors on sui developent pipe.
This fix 
https://github.com/SUI-Components/sui/issues/144
> fix(META): added a ignore on packages/sui-widget-embedder/react

- packages/sui-component-peer-dependencies/package.json
> feat(sui-component-peer-dependencies): bump to React 16

- packages/sui-studio/README.md
Consolidate how to install the sui-studio component
Readme asks to install a "deprecated" version of this tool in the installation seccion and it is also recommended to not install as a global package.
> Consolidate how to install sui-studio

- packages/sui-i18n/README.md
- packages/sui-i18n/package.json
- packages/sui-i18n/src/adapters/default.js
- packages/sui-i18n/src/adapters/polyglot.js
- packages/sui-i18n/src/console.js
- packages/sui-i18n/src/i18n.js
- packages/sui-i18n/src/index.js
- packages/sui-i18n/src/slugify.js
- packages/sui-i18n/test/i18nSpec.js
- packages/sui-i18n/test/polyglotSpec.js
Move old rosetta package to sui-i18n
I've also done:
fix https://github.com/SUI-Components/sui/issues/215
> feat(sui-i18n): move rosetta to sui-i18n

- packages/sui-studio/src/components/navigation/index.js
added search to default props to avoid lint errors
> refactor(sui-studio): added search to default props to avoid lint errors

- packages/sui-studio-utils/package.json
- packages/sui-studio-utils/src/domain-builder/index.js
- packages/sui-studio-utils/src/i18n/index.js
- Migration to the new @s-ui/i18n module
- DomainBuilder compatibility with the new @s-ui/domain EntryPointFact
- Error messages improvement
> Sui utils/i18n migration

- packages/sui-bundler/README.md
Translate the README to english.
Fixes https://github.com/SUI-Components/sui/issues/211
> feat(sui-bundler): translate to english

- README.md
Instead having an arbitrary sort of the tools, sort alphabetically in order to find them easily.
Fixes https://github.com/SUI-Components/sui/issues/221
> Sort tools in order to be easily found

- packages/sui-domain/src/fetcher/AxiosFetcher.js
> fix(sui-domain): make use of provided config in fetcher

- README.md
Added references to all packages in the repo
> docs(META): added references to new packages

- package.json
Add missing dependencies to get the testing work.
> fix(META): fix testing

- packages/sui-mockmock/src/http/index.js
- packages/sui-test/README.md
- packages/sui-test/bin/cypress/cypress.json
- packages/sui-test/bin/sui-test-e2e.js
- packages/sui-test/bin/sui-test.js
- packages/sui-test/package.json
New command for e2e tests.
First implementation was done here: https://github.schibsted.io/scmspain/frontend-mt--web-app/pull/233
> Sui test e2e

- packages/sui-test/README.md
- packages/sui-test/bin/sui-test-e2e.js
- packages/sui-test/package.json
Avoid installing cypress by default (300MB)
Install only when "sui-test e2e" is executed
> Test e2e cypress lazy install

- packages/sui-mockmock/package.json
- packages/sui-mockmock/src/http/clientMocker.js
- packages/sui-mockmock/test/mockerSpec.js
mockmock wasn't mocking the status code for get requests. Added test where failing before the changes
> fix(sui-mockmock): added != 200 status code mock for get request

- packages/sui-react-initial-props/src/ssrComponentWithInitialProps.js
- packages/sui-ssr/server/ssr/index.js
> [sui-ssr] reduce dependencies with sui-react-initial-props

- package.json
- packages/sui-lint/Readme.md
- packages/sui-lint/bin/sui-lint-js.js
- packages/sui-lint/bin/sui-lint-sass.js
- packages/sui-lint/src/helpers.js
> sui lint improvements

- packages/sui-ssr/archive/Dockerfile
- packages/sui-ssr/archive/index.js
- packages/sui-ssr/archive/pm2.tpl
- packages/sui-ssr/bin/sui-ssr-archive.js
Now `sui-ssr archive` include a Dockerfile to deploy in docker based platforms
This page is deployed directly to now.sh from an archive
https://server-nzlenkqspx.now.sh/list
> [sui-ssr] Add Docker to archive

- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/ssr/index.js
GET /_health is the new health check end point
> [sui-ssr] Add very basic health check end point

- package.json
- packages/sui-lint/.prettierrc.js
- packages/sui-lint/Readme.md
- packages/sui-lint/bin/sui-lint-format-js.js
- packages/sui-lint/bin/sui-lint-js.js
- packages/sui-lint/bin/sui-lint.js
- packages/sui-lint/package.json
- packages/sui-lint/src/helpers.js
- packages/sui-precommit/Readme.md
- packages/sui-precommit/bin/sui-precommit-run.js
Check changes on jsx files: https://github.com/SUI-Components/sui-components/pull/367/files#diff-d65deaf087d1e90de6ccc6d0ba1982b6
#138
> Sui lint prettier

- packages/babel-preset-sui/README.md
Add more info on the README about the plugins/presets used on babel-preset-sui.
> Update README of babel-preset-sui

- packages/sui-helpers/cli.js
- packages/sui-helpers/packages.js
- packages/sui-mono/bin/sui-mono-link.js
Make sui-mono link not to break for an order condition.
> Improve sui mono link

- packages/sui-bundler/webpack.config.server.js
Avoid use https://github.com/felixge/node-gently when compile server code
> [sui-bundler] Avoid use Gently in the server config

- packages/sui-deploy/README.md
- packages/sui-deploy/bin/sui-deploy-spa.js
- packages/sui-deploy/bin/sui-deploy.js
- packages/sui-deploy/package.json
- packages/sui-helpers/cli.js
> Sui deploy demos and protection

- packages/sui-polyfills/src/index.js
Provide a polyfill for Array.fill method to support IE11 cc/ @jcger
> feat(sui-polyfills): add Array.fill polyfill

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-lib.js
- packages/sui-bundler/bin/sui-bundler.js
- packages/sui-bundler/package.json
- packages/sui-bundler/shared/define.js
- packages/sui-bundler/shared/uglify.js
- packages/sui-bundler/webpack.config.lib.js
- packages/sui-bundler/webpack.config.prod.js
Builds en entry file with chunks.
Here's an implementation example: https://github.schibsted.io/scmspain/frontend-mt--lib-motor/pull/306
Here's a playground of it: https://jsbin.com/mavodak/1/edit?html,output
> sui-bundler lib

- packages/sui-helpers/packages.js
- packages/sui-mono/bin/sui-mono-release.js
To avoid messages like this: https://github.schibsted.io/scmspain/frontend-ep--uilib-theme/commit/69479124a7b2dbfd33b8370eed32abf01b5287e8
> Fix releases in windows

- packages/sui-domain/src/AnemicModel.js
- packages/sui-domain/test/AnemicModelSpec.js
> fix(sui-domain): fix: anemic models toJSON not recursive

- packages/babel-preset-sui/package.json
> feat(babel-preset-sui): update react-hot-loader

- packages/sui-deploy/bin/sui-deploy-spa.js
- packages/sui-js/package.json
- packages/sui-js/src/string/index.js
Fixes naming problems with branches like "feature/my-new-feature" as `now` doesn't allow `/` chars
> Sui deploy fix branch name

- packages/sui-deploy/package.json
Add missing sui-js dependency to package.json
> fix(sui-deploy): add missing package to dependencies

- packages/sui-deploy/README.md
- packages/sui-deploy/bin/sui-deploy-dir.js
- packages/sui-deploy/bin/sui-deploy-spa.js
- packages/sui-deploy/bin/sui-deploy.js
> sui-deploy default for docker deployments

- packages/sui-deploy/CHANGELOG.md
- packages/sui-deploy/bin/sui-deploy-dir.js
- packages/sui-deploy/bin/sui-deploy-spa.js
- packages/sui-deploy/package.json
- packages/sui-deploy/src/client/now.js
- packages/sui-deploy/src/utils.js
/lib files were missing because of gitignore.
Moved to src
> Fix sui deploy

- packages/sui-bundler/package.json
was avoiding repos with sui-bundler dep to install last versions of sui-helpers
> fix(sui-bundler): allow last versions of sui-helpers

- packages/sui-bundler/package.json
Fixes error build problems with Node 10.
> fix(sui-bundler): fix Travis CI broken when used node 10

- packages/sui-domain/src/fetcher/AxiosFetcher.js
> feat(sui-domain): add options parameter to delete method

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-lib.js
> feat(sui-bundler): option to not use version directory

- packages/sui-bundler/bin/sui-bundler-lib.js
> fix(sui-bundler): adjust public path on root=true

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-lib.js
New option to publish lib as UMD.
> Sui bundler umd

- packages/sui-test/bin/mocha/register.js
Added support to dynamic imports in server side
We have added recently support on the client side for dynamic imports but we forgot to add the same support of dynamic imports in server side. When we ran the test on the server side the execution crash because dynamic imports weren't supported.
> feat(sui-test): added support to dynamic imports in server side

- .travis.yml
- package.json
Tests were failing before of non escaped chars
> chore(META): fix tests execution in travis

- packages/sui-i18n/src/slugify.js
Modified the regex in order to admit dots on our urls. So we can have 'fake' urls pointing to .php's .html's etc....
> feat(sui-i18n): this PR ads a dot to the regex of the sui-i18n

- packages/sui-i18n/src/slugify.js
- packages/sui-i18n/test/slugifySpec.js
I've changed the REGEX in order to fix an edge case that was throwing errors. 
I've also increased our test suite in order to avoid future problems regarding slugify function.
> fix(sui-i18n): fixed a bug related with regex

- packages/sui-lint/eslintrc.js
- packages/sui-lint/package.json
> feat(sui-lint): throw error if only in tests and use a const for rule values

- packages/sui-bundler/README.md
> docs(sui-bundler): fix link to Hot Module Replacement

- packages/sui-bundler/bin/sui-bundler-build.js
This bugfix let our users know in which environment was their bundle builded.
> fix(sui-bundler): let our bundler notice us about our bundle environment

- packages/sui-bundler/package.json
Just updating bunde analyzer to latest version to help us check bundle sizes. :D
> feat(sui-bundler): update bundle analyzer to latest version

- packages/sui-bundler/webpack.config.lib.js
Fix multiple webpack runtimes collision since the PR https://github.com/SUI-Components/sui/pull/414 didn't fix the actual issue.
https://github.com/SUI-Components/sui/pull/414
> fix(sui-bundler): fix jsonp function param in webpack lib config

- packages/sui-studio/src/components/icons/index.js
- packages/sui-studio/src/components/navigation/index.js
- packages/sui-studio/src/components/utils.js
Remove all about compliant components as is not longer necessary.
> feat(sui-studio): remove all about compliant in sui-studio as not longer necessary

- packages/sui-hoc/package.json
- packages/sui-hoc/src/index.js
- packages/sui-hoc/src/withStateValue.js
`withStateValue` that can be used w/ most of _controlled_ `sui-components` involving some kind of input. Commonly used in `sui-components` demos to demonstrate dynamic behavior
> feat(sui-hoc): withStateValue hoc

- packages/sui-bundler/webpack.config.dev.js
Fix Windows bug with Regular Expression rules, [details](https://github.com/SUI-Components/sui/issues/433#issuecomment-446122985)
Fix #433
> fix(sui-bundler): fix windows bug with Regular Expression rules

- packages/sui-widget-embedder/compiler/development.js
- packages/sui-widget-embedder/compiler/production.js
> fix(sui-widget-embedder): set unique jsonpFunction to avoid collisions

- .gitignore
- jsconfig.json
- packages/sui-dashboard/README.md
- packages/sui-dashboard/bin/sui-dashboard-components.js
- packages/sui-dashboard/bin/sui-dashboard.js
- packages/sui-dashboard/package.json
- packages/sui-dashboard/scripts/clone-and-install.sh
- packages/sui-dashboard/src/index.js
> [sui-dashboard] First draft

- packages/sui-widget-embedder/bin/sui-widget-embedder-build.js
fix travis build success even when one of the pages fail while building
> fix(sui-widget-embedder): add serial build error handling

- packages/sui-widget-embedder/bin/sui-widget-embedder-build.js
widgets are not loading its config
> fix(sui-widget-embedder): change the way the config is loaded

- packages/sui-hoc/src/index.js
- packages/sui-hoc/src/withOpenToggle.js
`withOpenToggle` hoc needed in several sui-components like `AtomTooltip`, `MoleculeSelect` & `MoleculeAutosuggest`
> With open toggle

- packages/sui-bundler/package.json
- packages/sui-component-peer-dependencies/package.json
Upgrade dependencies and force from a specific version to avoid security issues.
> fix(sui-bundler): fix security issues with compromised dependencies

- packages/sui-ssr/archive/index.js
ISSUES CLOSED: EFE-335
Force sui-ssr to be deployed as docker for now by adding in the package.json the now config needed. It also uses the latest features to get the best of the docker deployment.
> feat(sui-ssr): use latest features and force docker type deployment

- .github/CODEOWNERS
> feat(META): add Kiko Ruiz to Code Owners

- packages/sui-test/bin/karma/index.js
Load the correct babel-polyfill for karma.
> fix(sui-test): add new polyfill from babel@7 instead using old one

- packages/sui-mono/bin/sui-mono-release.js
In order to avoid releasing packages in a feature branch, we have added a new check on the sui-bundler release command that ensures the current active branch is `master`
```
$ git checkout test-release
Switched to branch 'test-release'
$ npm run release
> frontend-ma--uilib-components@1.0.0 release frontend-ma--uilib-components
> sui-studio release
✖ An error occurred during command execution. Info:
Error: Active branch is not master, please make releases only in master branch
```
> feat(sui-mono): check branch master is active when releasing a package

- packages/sui-bundler/package.json
Force terser for now to avoid problems on bundling.
> fix(sui-bundler): force terser version to avoid problems with webpack

- packages/sui-decorators/README.md
- packages/sui-decorators/package.json
- packages/sui-decorators/src/decorators/error.js
- packages/sui-decorators/src/index.js
- packages/sui-decorators/test/browser/errorSpec.js
- packages/sui-decorators/test/server/errorSpec.js
Reverts SUI-Components/sui#484 in order to create a major with it.
> Revert "Revert "[sui-decorators] Create new decorator Error""

- packages/sui-react-initial-props/src/ssrComponentWithInitialProps.js
Support nodeToStream in React Initial Props. By default it keeps the same behaviour until now.
> feat(sui-react-initial-props): support React Stream

- packages/sui-mockmock/package.json
- packages/sui-test/bin/karma/config.js
- packages/sui-test/bin/karma/index.js
- packages/sui-test/bin/mocha/register.js
- packages/sui-test/package.json
We want to avoid this error:
```
(function (exports, require, module, __filename, __dirname) { import HttpMocker from './http';
^^^^^^^^^^
SyntaxError: Unexpected identifier
```
> [sui-test] Use webpack

- packages/sui-hoc/src/index.js
Use corrected syntax from exported imported modules
> fix(sui-hoc): fix import export modules

- packages/sui-ssr/package.json
- packages/sui-ssr/server/index.js
> feat(sui-ssr): add GZip compression to the responses

- packages/sui-helpers/package.json
Upgrade listr dependency to fix problems with peer dependency.
> feat(sui-helpers): upgrade dependency listr that fixes problem with peer dependency

- packages/sui-studio/package.json
Update sui-bundler to latest version in sui-studio.
> feat(sui-studio): use latest sui-bundler on studio

- packages/sui-js/src/string/index.js
Remove non supported proposal export and switch it for one supported by syntax.
> fix(sui-js): switch proposal export for supported syntax one

- packages/sui-deploy/package.json
- packages/sui-deploy/src/utils.js
Fix problem using directly lodash method instead using library though to be used via webpack.
> fix(sui-deploy): fix unsupported import from not compiled package

- packages/sui-lint/eslintrc.js
- packages/sui-lint/package.json
Add eslint-plugin-react-hooks package and eslint rules
Add eslint-plugin-react-hooks package and eslint rules
Rules of Hooks offical doc: https://reactjs.org/docs/hooks-rules.html
Interesting info about 'exhaustive-deps' lint rule: https://github.com/facebook/react/issues/14920
> feat(sui-lint): add eslint-plugin-react-hooks package and rules

- packages/sui-studio/package.json
Avoid installing not needed dependencies and some move them to dev.
> fix(sui-studio): avoid installing not needed dependencies and use devDependencies for some

- packages/sui-studio/package.json
otherwise sui-studio-check-release doesn't work
> fix(sui-studio): move sui-mono as dependency

- packages/sui-svg/bin/sui-svg-build.js
- packages/sui-svg/package.json
```
node_modules/@s-ui/js/lib/string/index.js:1
(function (exports, require, module, __filename, __dirname) { import { parse } from 'qs';
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
```
> fix(sui-svg): remove unsupported import

- packages/sui-polyfills/src/index.js
Added polyfill for object.entries IE 11
Added polyfill for object.entries IE 11
> fix(sui-polyfills): added polyfill

- packages/sui-lint/package.json
MORE INFO: https://nvd.nist.gov/vuln/detail/CVE-2018-16469
> [sui-lint] Fix security problem

- packages/sui-test/README.md
add ```--save-dev``` flag in ```npm install``` command in read.me file
> fix(sui-test): npm install command add --save-dev flag

- packages/sui-hoc/README.md
- packages/sui-hoc/package.json
- packages/sui-hoc/src/withAllContexts.js
- packages/sui-hoc/src/withSUIContext.js
- packages/sui-ssr/README.md
- packages/sui-ssr/server/config.js
- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/ssr/index.js
Since there wasn't any site using the new React Context API, SSR was working fine for each one. Right now we need to move to there, so we've added a new option for using it alone or using them all by default (legacy and new one).
> Support new React Context API in SSR.

- packages/sui-js/package.json
Move package to dependency from devDependency
> Move package to dep from devDep

- packages/sui-ssr/README.md
- packages/sui-ssr/server/criticalCss/index.js
> [sui-ssr] Add blackListURLs config to avoid critical CSS in some urls

- packages/sui-bundler/webpack.config.server.js
Make it compatible with `css` files as well.
> fix(sui-bundler): avoid css causing problems

- packages/sui-studio/workbench/src/components/Root/index.js
- packages/sui-studio/workbench/src/components/Root/index.scss
Adds a mobile device graphic to give a nicer context to the rendered component in mobile viewports.
Here is an attached screen caption
Please review:
> feat(sui-studio): adds a mobile device just to make it look cooler

- packages/sui-ssr/hooks-types.js
- packages/sui-ssr/server/hooksFactory/index.js
- packages/sui-ssr/server/index.js
use this hook if you want to set your custom hook to check the health of your app
> feat(sui-ssr): add pre health check hook

- packages/sui-test/README.md
- packages/sui-test/bin/sui-test-server.js
> [sui-test] Add inspect flag to server command

- packages/sui-ssr/server/index.js
We were storing the memoized html template into an object only when the server was multisite. First request for those servers was working properly because the html template assigned was the one read from the public folder, but the following ones were breaking because the html template saved in the request wasn't an string but an object, the same one saved in cache.
To simplify this logic, now memoized templates are saved ALWAYS in an object (`_memoizedHtmlTemplatesMapping`), so that both multisite and single site servers will be retrieving the cached templated from its corresponding key: the `site` variable for multisite servers and a `default` key for single sites.
> fix(sui-ssr): make memoized html template be always an object

- packages/sui-bundler/package.json
- packages/sui-bundler/shared/precache.js
- packages/sui-bundler/webpack.config.prod.js
Move to workbox webpack plugin instead deprecated sw-precache.
> feat(sui-bundler): move to workbox-webpack-plugin

- packages/sui-test/src/descriptor-environment-patcher.js
> fix(sui-test): export instead of exports

- packages/sui-js/test/stringSpec.js
> chore(sui-js): remove only

- packages/sui-svg/package.json
> fix(sui-svg): camelcase is used as a dependency

- packages/sui-js/src/ua-parser/index.js
> add browser to ua-parser

- .travis-release.sh
- package.json
Remove npm scripts for releasing packages.
Use manual release command in travis.
> chore(META): use manual sui-mono release and remove npm scripts

- packages/babel-preset-sui/package.json
- packages/babel-preset-sui/src/index.js
More info: 
- https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-chaining
- https://github.com/tc39/proposal-optional-chaining
- https://twitter.com/TheLarkInn/status/1154456929898385408?s=20
> [babel-preset-sui] Add @babel/plugin-proposal-optional-chaining 🎉

- packages/sui-lint/bin/sui-lint-sass.js
Replace:
```
stylelint 'components/form/forgotPassword/src/_settings.scss, components/form/forgotPassword/src/index.scss'
```
For:
```
stylelint  'components/form/forgotPassword/src/_settings.scss' 'components/form/forgotPassword/src/index.scss'
```
> [sui-lint] Fix lint several scss files

- packages/sui-widget-embedder/compiler/production.js
> fix(sui-widget-embedder): use right file

- packages/sui-widget-embedder/compiler/production.js
> fix(sui-widget-embedder): add source map to minify

- packages/sui-ssr/hooks-types.js
- packages/sui-ssr/package.json
- packages/sui-ssr/server/hooksFactory/index.js
- packages/sui-ssr/server/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/658)
> [sui-ssr] Add PRE_SSR_HANDLER hook

- packages/sui-ssr/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/659)
> [sui-ssr] Update deps

- packages/sui-hoc/src/index.js
- packages/sui-hoc/src/withSwitchValue.js
new hoc `withSwitchValue` for components like`AtomSwitch` or `AtomCheckbox`
> feat(sui-hoc): withSwitchValue

- packages/sui-lint/bin/sui-lint-sass.js
Add fix option to sui-lint sass in order to fix automatically sass problems (when posible).
> feat(sui-lint): add fix arg for sui-lint sass

- packages/sui-lint/Readme.md
- (docs) replace sasslint with styleLint
> docs(sui-lint): replace sasslint with styleLint

- packages/sui-dashboard/bin/sui-dashboard-components.js
- packages/sui-dashboard/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/667)
> [sui-dashboard] Add new projects to the dashboard

- packages/sui-hoc/src/withSwitchValue.js
Passing "name" attribute to event handler
> feat(sui-hoc): name to handleChange

- packages/sui-ssr/README.md
- packages/sui-ssr/server/criticalCss/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/671)
> [sui-ssr] Fix critical css

- packages/sui-domain/src/fetcher/AxiosFetcher.js
- packages/sui-domain/src/fetcher/Fetcher.js
> feat(sui-domain): add patch verb to fetcher

- packages/sui-ssr/README.md
- packages/sui-ssr/server/ssr/index.js
Added a new configuration property `serverContentType` that if is set it will set the current Content-type of the server.
> feat(sui-ssr): added configuration to set the server content-type

- packages/sui-ssr/server/config.js
- packages/sui-ssr/server/ssr/index.js
Related to https://github.com/SUI-Components/sui/pull/679#pullrequestreview-304529929.
Add a DEFAULT_VALUES const in order to avoid branching the code every time we have to rely on a default value. This keep compatibility with the actual behavior.
> feat(sui-ssr): stop branching our code for using default values

- packages/sui-bundler/package.json
Add node 13 support by upgrading node-sass dependency.
> feat(sui-bundler): add node 13 support by upgrading node-sass

- packages/sui-js/README.md
- packages/sui-js/src/cookie/index.js
Add options parameter to set cookies (expires, path, domain and secure)
> feat(sui-js): add cookie set options

- packages/sui-test/bin/sui-test-server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/695)
> [sui-test] Avoid swallow error code in server execution

- packages/sui-svg/src/app.js
- packages/sui-svg/src/index.scss
Add search functionality to icons demo.
> feat(sui-svg): add search functionality to icons demo

- packages/sui-dashboard/bin/sui-dashboard-components.js
Add Habitaclia Web App project to the Dashboard
> feat(sui-dashboard): add new habitaclia project to the dashboard

- packages/sui-js/README.md
- packages/sui-js/src/ua-parser/index.js
- packages/sui-js/test/browser/userAgentParserSpec.js
- packages/sui-js/test/server/userAgentParserSpec.js
- packages/sui-js/test/userAgentParserTest/data/uaDB.json
- packages/sui-js/test/userAgentParserTest/index.js
adds user-agent stats test and isTablet option
> feat(sui-js): add isTablet stat

- packages/sui-dashboard/bin/sui-dashboard-components.js
remove wrong repo from sui-dashboard
> fix(sui-dashboard): fix sui dashboard bad repo

- packages/sui-bundler/package.json
This fixes the `terser` version until this bug is fixed: https://github.com/terser/terser/issues/527
> fix(sui-bundler): fix version of terser

- packages/sui-i18n/package.json
- packages/sui-i18n/src/i18n.js
- packages/sui-js/package.json
- packages/sui-js/src/string/index.js
- packages/sui-js/src/string/slugify.js
Create a copy of slugify from sui-i18n to sui-js.
And preserve the original slugify file to avoid creating a breaking change commit
> [sui-i18n] Move stringify

- packages/sui-test/bin/karma/config.js
- packages/sui-test/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/714)
> [sui-test] Restore spec reporter

- .github/README_TEMPLATE.md
- packages/sui-decorators/README.md
- packages/sui-studio/bin/sui-studio-generate.js
Remove not needed `--flag` on generating new components.
> feat(sui-studio): remove adding --save to README

- packages/sui-mono/bin/sui-mono-phoenix.js
Display the installed packages in the log 
The log indicates the packages pending installation instead of those installed
> feat(sui-mono): set current installed packages log

- packages/sui-dashboard/bin/sui-dashboard-components.js
Add the Unique Tool Web App repository on SUI-Dashboard.
> feat(sui-dashboard): add UT repository

- packages/sui-test/bin/karma/index.js
- packages/sui-test/bin/sui-test-browser.js
- packages/sui-test/bin/sui-test-server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/731)
> [sui-test]: Set properly the timeout in browser and server

- packages/sui-bundler/shared/define.js
- packages/sui-studio/bin/sui-studio-dev.js
- packages/sui-studio/src/components/test-page/index.js
- packages/sui-studio/src/components/test/index.js
- packages/sui-studio/src/components/workbench/index.js
- packages/sui-studio/src/index.html
- packages/sui-studio/src/snarkdown.js
- packages/sui-studio/workbench/src/components/Root/index.js
Fix 
```
ReferenceError: __EXPERIMENTAL_TEST__ is not defined
at component (main.39dfbc18.js:2)
at cs (main.39dfbc18.js:2)
at kr (main.39dfbc18.js:2)
at Aa (main.39dfbc18.js:2)
at fa (main.39dfbc18.js:2)
at ua (main.39dfbc18.js:2)
at ta (main.39dfbc18.js:2)
at Ua (main.39dfbc18.js:2)
at main.39dfbc18.js:2
at ra (main.39dfbc18.js:2
```
Reference Error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/736)
> [Bug] sui studio with testing

- packages/sui-bundler/package.json
- packages/sui-studio/package.json
- packages/sui-studio/src/components/demo/fetch-styles.js
- packages/sui-studio/workbench/src/app.js
> fix(sui-studio): remove deprecated css-content-loader

- packages/sui-studio/scripts/postinstall.js
Right now the test template its having linter issues
> fix(sui-studio): add additional line to test template to avoid linter issues

- packages/sui-studio/scripts/postinstall.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/746)
> [sui-studio] Avoid remove test folder after phoenix

- packages/sui-js/README.md
- packages/sui-js/src/string/to-query-string.js
add some docs about `toQueryString` method
> docs(sui-js): add toQueryString docs

- packages/sui-js/README.md
> docs(sui-js): fix typo in readme

- packages/sui-studio/README.md
- packages/sui-studio/src/components/test-page/index.js
- packages/sui-studio/src/components/test/index.js
- packages/sui-studio/src/patcher-mocha/index.js
- packages/sui-studio/workbench/src/components/Root/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/758)
> [sui-studio] Patcher-mocha is not transpiled

- packages/sui-dashboard/bin/sui-dashboard-components.js
Add Unique Tool repository to SUI-Dashboard.
> feat(sui-dashboard): add Unique Tool repository to SUI-Dashboard

- packages/sui-studio/src/components/test/index.js
- packages/sui-studio/src/index.html
- packages/sui-studio/src/patcher-mocha/index.js
- packages/sui-studio/workbench/src/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/760)
> [sui-studio] hoist demo component to use static props

- packages/sui-ssr/server/template/index.js
Priorize head tag load for improve SEO
> feat(sui-ssr): priorize head tag load for improve SEO

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-build.js
- packages/sui-bundler/loaders/linkLoaderConfigBuilder.js
- packages/sui-ssr/README.md
- packages/sui-ssr/bin/sui-ssr-build.js
- packages/sui-ssr/compiler/server.js
- packages/sui-ssr/package.json
- packages/sui-studio/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/762)
> [Feature] Add link package flag for builds

- packages/sui-studio/bin/sui-studio-generate.js
Use correct package on generating component on studio.
> feat(sui-studio): use new @s-ui/theme pkg

- packages/sui-bundler/package.json
https://github.com/facebook/create-react-app/issues/8153#issuecomment-574397773
https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/webpackHotDevClient.js#L67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/775)
> [sui-bundler] Update dependency of react-dev-utils

- packages/sui-bundler/factories/createDevServerConfig.js
https://github.com/facebook/create-react-app/commit/1cbc6f7db62f78747cb6ca41450099181139325e#diff-595228c9c4e2f6619c6bb1478ba4ef87L10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/776)
> [sui-bundler] noopSW require a string

- packages/sui-component-peer-dependencies/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/778)
> [sui-component-peer-dependencies] Add @s-ui/react-head

- packages/sui-ssr/README.md
- packages/sui-ssr/package.json
- packages/sui-ssr/server/ssr/index.js
- packages/sui-ssr/server/template/index.js
Use the new package [@s-ui/react-head](https://github.com/SUI-Components/sui/tree/master/packages/sui-react-head)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/779)
> [@s-ui/ssr] Migrate to @s-ui/react-head

- packages/sui-ssr/server/ssr/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/780)
> [sui-ssr] Remove JSX from the server code

- packages/sui-react-head/src/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/782)
> [sui-react-head] Add content as fallback

- packages/sui-studio/src/components/style/index.js
- packages/sui-studio/workbench/src/components/Raw/index.js
This means that fist of all, the demo style ill be included, and then the distro styles proposal
> feat(sui-studio): mod styles sorting in workbench Raw view

- packages/sui-studio/src/index.html
- packages/sui-studio/workbench/src/index.html
>  add new global variable

- packages/sui-svg/bin/sui-svg-build.js
add process.exit in sui-svg build error
> fix(sui-svg): add process.exit in sui-svg build error

- packages/sui-test/Dockerfile
- packages/sui-test/README.md
- packages/sui-test/bin/sui-test-e2e.js
- packages/sui-test/package.json
BREAKING CHANGE:
update cypress version
> feat(sui-test): add ci mode and update cypress version

- packages/sui-studio/package.json
`userEvent` is a tool from Testing Library that allows to write better user interaction test component.
an example from its [documentation page](https://github.com/testing-library/user-event#api):
```js
import React from "react";
import { render } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
test("click", () => {
const { getByText, getByTestId } = render(
<div>
<label htmlFor="checkbox">Check</label>
<input id="checkbox" data-testid="checkbox" type="checkbox" />
</div>
);
userEvent.click(getByText("Check"));
expect(getByTestId("checkbox")).toHaveAttribute("checked", true);
});
```
> feat(sui-studio): adds userEvent from testingLibrary

- packages/sui-ssr/server/template/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/796)
> [sui-ssr] Use parse to improve JSON

- packages/sui-react-initial-props/src/withInitialProps.js
Add context and routeInfo the Page.renderLoading
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/785)
> [sui-react-initial-props] Improve Page.renderLoading

- README.md
- Added `react-head` component on components list
- Fixed minor Markdown syntax errors
> docs(META): added react-head on README file

- packages/sui-ssr/compiler/server.js
- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/prpl/index.js
- packages/sui-ssr/server/ssr/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/799)
> [sui-ssr] Add support for the prpl service

- packages/sui-ssr/server/criticalCss/index.js
- packages/sui-ssr/server/dynamicRendering/index.js
- packages/sui-ssr/server/prpl/index.js
- packages/sui-ssr/server/ssr/index.js
Using Header, we can avoid waiting for the getInitialProps resolution to start fetching the critical assets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/800)
> [sui-ssr] send hints preload with headers

- packages/sui-bundler/README.md
- packages/sui-bundler/factories/createDevServerConfig.js
- packages/sui-bundler/package.json
- packages/sui-bundler/shared/precache.js
- packages/sui-bundler/webpack.config.prod.js
Update the workbox-webpack-plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/797)
> [sui-bundler] Update PWA plugin

- packages/sui-ssr/server/criticalCss/index.js
- packages/sui-ssr/server/prpl/index.js
Allow config as:
```
"sui-ssr": {
"prpl": {
"production": {
"host": "frontend-ma--web-app.es-microma-pro.schip.io",
"cdn": "scm-milanuncios-frontend-pro"
},
"preproduction": {
"host": "frontend-ma--web-app.es-microma-pre.schip.io",
"cdn": "scm-milanuncios-frontend-pre"
},
"host": "frontend-ma--web-app.es-microma-pro.schip.io",
"cdn": "scm-milanuncios-frontend-pro",
"protocol": "https",
"strategy": "longestEvaluation"
}
}
```
And with the VERBOSE env var:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/802)
> [sui-ssr] Improve logging and config

- README.md
> docs(META): remove old acronym definition

- packages/sui-ssr/README.md
- packages/sui-ssr/server/ssr/index.js
Plug in context providers
Adds a way to add your custom context providers from your web-app to be rendered server side
> feat(sui-ssr): context providers as plugins

- packages/sui-changelog/bin/index.js
- packages/sui-changelog/src/config.js
- packages/sui-changelog/src/helpers.js
Updates changelog error handling and package scope added to package description
- changelog will refer to package scope + name instead of just name
- Changelog message changes from `There is no changelog data for this package.` to `Error loading changelog data for this package.`
- bad credentials error is intercepted now
> Sui changelog/improved error handling

- packages/sui-studio/package.json
New major of `react testing library` in order to have the `waitFor` method
**BREAKING CHANGE:**
New major of `react-testing-library`
In order to be able to test the logic of `useEffects` and `useMounts`, we must use `waitFor` which was released in version 10 of `reacting-testing-library`
It' important to `await` for the `waitFor` method.
```
const element = getByPlaceholderText('CONTACT_NAME_LABEL')
expect(element.value).to.equal('')
// this changes because we update form fields from user session data in the `useMount`
await waitFor(() => {
const element = getByPlaceholderText('CONTACT_NAME_LABEL')
expect(element.value).to.equal('Fake User')
})
```
> feat(sui-studio): new major react testing library

- packages/sui-studio/src/components/layout/_style.scss
Modify the main readme styling according to the @turolopezsanabria intention
> feat(sui-studio): modify studio styling

- packages/sui-ssr/server/index.js
Change hooks order as it was before adding the router hook. As it is now it's breaking ij's web-app
> fix(sui-ssr): fix hooks order

- packages/sui-react-initial-props/README.md
> docs(sui-react-initial-props): fix typo in README

- packages/sui-ssr/server/hooksFactory/index.js
fix redirect location param name. This was making any <Redirect> set up in the routes fail.
> fix(sui-ssr): fix redirect location param name

- packages/sui-ssr/README.md
- packages/sui-ssr/package.json
- packages/sui-ssr/server/dynamicRendering/index.js
- packages/sui-ssr/server/hooksFactory/index.js
- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/ssr/index.js
- packages/sui-ssr/server/template/index.js
More Info: https://bugs.chromium.org/p/v8/issues/detail?id=2869
> [sui-ssr] Fix memory leak

- packages/sui-changelog/bin/index.js
> fix(sui-changelog): use right strategy file key

- packages/sui-domain/package.json
- packages/sui-mockmock/package.json
Use latest axios version on domain and mockmock with latest bugfixes.
> Use latest axios version with bug fixes

- package.json
- packages/sui-widget-embedder/src-react/Widget.js
Enable browser context in Widget.
> feat(sui-widget-embedder): support browser context in widget

- packages/sui-mockmock/package.json
> feat(sui-mockmock): bump version

- packages/sui-decorators/package.json
> fix(sui-decorators): fix redis cache in browser

- packages/sui-decorators/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/840)
> [sui-decorators] Add redis-mock and hot-shot to dependencies

- packages/sui-bundler/registerServiceWorker.js
Make options parameter to be optional instead required.
> fix(sui-bundler): make options parameter to be optional

- packages/sui-bundler/registerServiceWorker.js
Use `register` directly instead creating a function on invoking it.
> feat(sui-bundler): use register function directly

- packages/sui-react-initial-props/src/loadPage.js
- packages/sui-react-initial-props/src/ssrComponentWithInitialProps.js
- packages/sui-ssr/server/ssr/index.js
Add request and response to the getInitialProps function
> feat/Add request and response to getInitialProps

- packages/sui-bundler/bin/sui-bundler-build.js
sui-bundler: fix check if offline file exists
> fix(sui-bundler): fix check if offline file exists

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-build.js
- packages/sui-bundler/service-worker.js
Adds an option to activate static file cache but without having to create the offline.html page
> feat(sui-bundler): add statics cache only option

- packages/sui-bundler/README.md
- packages/sui-bundler/bin/sui-bundler-build.js
- packages/sui-bundler/package.json
- packages/sui-bundler/service-worker.js
- packages/sui-bundler/shared/precache.js
- packages/sui-bundler/webpack.config.prod.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/861)
> [sui-bundler] Allow import external scripts in our SW

- packages/sui-bundler/bin/sui-bundler-build.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/862)
> [sui-bundler] Allow no static cache config

- packages/sui-studio/README.md
- packages/sui-studio/bin/sui-studio-test.js
- packages/sui-studio/bin/sui-studio.js
- packages/sui-studio/package.json
- packages/sui-studio/scripts/test-runtime.js
- packages/sui-studio/src/components/tryRequire.js
- packages/sui-studio/src/patcher-mocha/index.js
- packages/sui-studio/src/runtime-mocha/index.js
- packages/sui-test/bin/karma/babelPatch.js
- packages/sui-test/bin/karma/config.js
- packages/sui-test/bin/karma/index.js
- packages/sui-test/package.json
Using a real DOM.
runtime.js
```js
import React from 'react'
import hoistNonReactStatics from 'hoist-non-react-statics'
import SUIContext from '@s-ui/react-context'
import withContext from '@s-ui/studio/src/components/demo/HoC/withContext'
import {cleanDisplayName} from '@s-ui/studio/src/components/demo/utilities'
import AtomButton from '../../../components/atom/button/src'
import AtomButtonContexts from '../../../demo/atom/button/context'
const originalKarmaLoader = window.__karma__.loaded
window.__karma__.loaded = () => {}
const run = async () => {
const nextAtomButtonContexts =
typeof AtomButtonContexts !== 'function'
? AtomButtonContexts
: await AtomButtonContexts()
debugger // eslint-disable-line
window.__STUDIO_CONTEXTS__ = nextAtomButtonContexts
window.__STUDIO_COMPONENT__ = …
```
> [Feature] @s-ui/studio run tests in the cli

- packages/sui-studio/src/components/tryRequire.js
- packages/sui-studio/src/runtime-mocha/index.js
FIX the sui-studio build command
> fix(sui-studio): fix sui-studio build bundle

- packages/sui-ssr/server/criticalCss/index.js
Migrate to the new CriticalCSS URL and use the new microservice API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/867)
> [sui-ssr] Migrate to the new CriticalCSS URL

- packages/sui-ssr/server/criticalCss/index.js
We're just doing a cherry-pick of the PR that I just closed to have in sync version 6 and 7 of the sui-ssr.
Does anyone know of any less manual ways?
> [sui-ssr] Cherry pick last commit v6

- packages/sui-bundler/service-worker.js
We want to force the reload when we ask for a new entry in the manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/872)
> [sui-bundler] create a new Request for each entry in the manifest

- packages/sui-ssr/package.json
- packages/sui-ssr/server/template/index.js
cherry pick https://github.com/SUI-Components/sui/commit/5216b47b48aeeb496e9a5b5a620a70361026bdf3 commit to v6 branch
> fix(sui-ssr): fix possible xss

- packages/sui-ssr/archive/Dockerfile.tpl
Cherry Pick for the PR 877 in sui-ssr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/881)
> [sui-ssr] fix node version to 14-alpine in dockerfile.tpl

- packages/sui-ssr/README.md
- packages/sui-ssr/bin/sui-ssr-build.js
- packages/sui-ssr/package.json
- packages/sui-ssr/scripts/remove-tags.js
- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/utils.js
We want to delete any tags that are preceded by the comment ``
> [sui-ssr] Remove ThirdParty script from sui-ssr

- packages/sui-ssr/README.md
- packages/sui-ssr/bin/sui-ssr-build.js
- packages/sui-ssr/package.json
- packages/sui-ssr/scripts/remove-tags.js
- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/884)
> [sui-ssr] Cherry Pick PR-870

- packages/sui-react-router/README.md
- packages/sui-react-router/src/internal/ReactUtils.js
- packages/sui-react-router/src/internal/createTransitionManager.js
- packages/sui-react-router/src/types.d.ts
- packages/sui-react-router/test/common/RouteSpec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/889)
> [sui-react-router] Add RegExp property to the route component

- packages/sui-ssr/server/utils.js
Double check for `multiSiteKeys`
> fix(sui-ssr): add double check before find an array element

- packages/sui-ssr/README.md
- packages/sui-ssr/server/index.js
- packages/sui-ssr/server/utils.js
Cherry-picked from `sui-ssr-v6` branch.
> [feat] allow regexps in multisite config

- package.json
> Migrate to new sui-precommit

- .gitignore
- packages/sui-js/package.json
- packages/sui-js/src/function/index.js
- packages/sui-js/src/function/throttle.js
> feat(sui-js): add throttle fn

- packages/sui-lint/scripts/add-package-json-fields.js
Avoid executing postinstall on CI as it's not needed.
> feat(sui-lint): avoid executing postinstall on CI

- packages/sui-mono/README.md
- packages/sui-mono/bin/sui-mono-release.js
- packages/sui-mono/package.json
> Sui mono/autorelease

- packages/sui-studio/src/patcher-mocha/index.js
> fix(sui-studio): import route

- packages/sui-studio/src/runtime-mocha/index.js
Actual version is crushing the travis integration process (not local). This small change fixes it
> fix(sui-studio): fix environment target

- packages/sui-test/bin/karma/config.js
- packages/sui-test/package.json
Fix the ci errors due to node-modules mjs inclusion and omits the warnings for the scss loaders
> fix(sui-test): fix ci test errors

- packages/sui-studio/scripts/prepare-only-changes.js
Check for a test folder if exists before renaming it.
> fix(sui-studio): check for the test folder

- packages/sui-ci/package.json
- packages/sui-ci/src/updateCommitStatus.js
- packages/sui-ci/test/server/updateCommitStatusSpec.js
- packages/sui-ci/test/server/utils.js
Add support to GitHub Enterprise API.
> feat(sui-ci): add support to Github Enterprise

- packages/sui-studio/src/components/tryRequire.js
Improve chunk naming so we know what we're bundling better.
> feat(sui-studio): improve chunk names to understand better what we're bundling

- packages/sui-studio/src/components/tryRequire.js
Use better chunk naming to avoid twice js extension and add quotation marks to avoid names not generated.
> feat(sui-studio): use better chunk naming to avoid twice js

- packages/sui-react-router/package.json
Upgrade sui-react-router dependencies.
> feat(sui-react-router): upgrade sui-react-router dependencies

- packages/sui-studio/README.md
This PR fixes `patcher-mocha` path in readme file
> docs(sui-studio): fix patcher mocha docs import

- packages/sui-ssr/server/ssr/index.js
Send request and response parameters to ssrComponentWithInitialProps in order to get the request in the getInitialProps as expected.
> feat(sui-ssr): add request and response to ssrComponentWithInitialProps

- packages/sui-component-peer-dependencies/package.json
Install the latest 16 version but avoid installing major 17 version.
> fix(sui-component-peer-dependencies): avoid installing react-dom@17

- packages/sui-lint/eslintrc.js
- packages/sui-lint/package.json
- packages/sui-lint/src/helpers.js
Add cypress rules and environment variables to @s-ui/lint.
This will fix this problem:
> feat(sui-lint): add cypress plugin

- packages/sui-js/README.md
A vulnerability was found on the `htmr` package we have as a dependency of `s-ui/js`.
Dependabot already did its job but the commits were tagged as `chore` so no bump in version took place and no new release was made.
It's just a dummy change on the README file tagged as `feat` just so we can have a new version and release of the package.
N/A
N/A
> feat(sui-js): reformat README to bump version

- packages/sui-svg/package.json
- packages/sui-svg/templates/icon-component.js
Use latest @s-ui/bundler. Also avoid importing React anymore on built icons.
> Use latest sui-bundler on sui-svg and avoid importing React according to new jsx

- packages/sui-dashboard/README.md
- packages/sui-dashboard/bin/sui-dashboard-components.js
- packages/sui-dashboard/src/index.js
added two diferent options:
-v outputs the pkg versions used per component and also on project
-o [filename] outputs the result in a given filename
result:
> filename.json
```json
{
"statsSUIComponentUsedInProjects": {
"@s-ui/react-atom-action-button": [
"/frontend-ma--web-app – v1.3.0",
"/frontend-mt--web-app – v1.3.0"
],
"@s-ui/react-atom-back-to-top": [
"/frontend-cf--web-app – v1.7.0"
],
"@s-ui/react-atom-badge": [
"/frontend-cf--web-app – v1.16.0",
"/frontend-fc--web-server – v1.16.0",
"/frontend-hab--web-app – v1.16.0",
"/frontend-ij--uilib-widgets – v1.16.0",
"/frontend-ij--web-app – v1.16.0",
"/frontend-re--ut-web-app – v1.16.0"
],
"@s-ui/react-atom-button": [
"/frontend-vb--uilib-widgets – v1.53.0",
"/frontend-ma--web-app – v1.53.0",
"/frontend-ma--uilib-widgets – v1.53.0", …
```
> feat(sui-dashboard): add versions and filename result options to the script

- packages/sui-bundler/registerServiceWorker.js
- packages/sui-cz/buildCommit.js
- packages/sui-html-tagger/src/index.js
- packages/sui-mono/bin/sui-mono-check.js
- packages/sui-perf/examples/example-1.js
- packages/sui-perf/examples/index.js
- packages/sui-perf/src/chart.js
- packages/sui-perf/src/measure.js
- packages/sui-polyfills/src/element-closest.js
- packages/sui-react-router/src/Link.js
- packages/sui-ssr/build-device.js
- packages/sui-ssr/server/dynamicRendering/seoBotDetect.js
- packages/sui-studio/src/snarkdown.js
- packages/sui-studio/workbench/src/components/Header/index.js
Remove some noise from GitHub Actions by fixing some linter warnings.
> chore(META): remove some lint warnings to remove some noise

- packages/sui-ci/bin/sui-ci-release.js
- packages/sui-ci/bin/sui-ci-update-commit-status.js
- packages/sui-ci/package.json
- packages/sui-ci/src/git.js
> feat(sui-ci): add support to GitHub Actions

- packages/sui-ci/package.json
- packages/sui-ci/src/git.js
> Feat/support GitHub actions for update commit status

- packages/sui-studio/bin/helpers/copyGlobals.js
- packages/sui-studio/bin/helpers/copyStaticFiles.js
- packages/sui-studio/bin/sui-studio-build.js
- packages/sui-studio/bin/sui-studio.js
- packages/sui-studio/src/app.js
- packages/sui-studio/src/components/tryRequire.js
- packages/sui-studio/workbench/src/app.js
- packages/sui-studio/workbench/src/components/Raw/index.scss
Add global file to include configurations per project once.
Proper for include custom studio cnfigurations, libraires, files, etc.
> feat(sui-studio): add globals.js conf

- packages/sui-ssr/README.md
- packages/sui-ssr/archive/Dockerfile.tpl
- packages/sui-ssr/archive/index.js
- packages/sui-ssr/bin/sui-ssr-archive.js
Add a new option to set a custom registry that can be used as a proxy or instead of the Docker Hub registry.
```
sui-ssr archive --docker-registry="containers.my-domain.com"
sui-ssr archive -R="containers.my-domain.com"
```
> feat(sui-ssr): add option to define a custom registry for the pm2 dependency

- packages/sui-studio/src/app.js
- packages/sui-studio/src/components/tryRequire.js
- packages/sui-studio/workbench/src/app.js
> fix(sui-studio): fix dev mode when globals.js file is not available

- packages/sui-ssr/README.md
- packages/sui-ssr/archive/Dockerfile.tpl
- packages/sui-ssr/archive/index.js
- packages/sui-ssr/bin/sui-ssr-archive.js
Adds the same docker registry option that is set for v7
> feat(sui-ssr): add docker-registry option

- packages/sui-hoc/src/withOpenToggle.js
We have an incompatibility behavior to close the autosuggest list when is open.
> fix(sui-hoc): back to the previous behavior version

- packages/sui-mono/README.md
> docs(sui-mono): fix sui-mono readme typo

- packages/sui-mono/src/config.js
**Fixes**
For example `/demo/node_modules/any-package/folder` was used as scope if `demo` root is installing packages.
This will avoid executing an unnecessary `npm install` on `/demo/**/**/themes` folder as `package.json` doesn't exist and also will skip `demos`  with the `package.json` file. For example, Fotocasa Components goes from 55 `npm install` for demos to `10` and get rid of all the errors.
Error on Travis CI Enterprise we're looking to remove: https://travis.mpi-internal.com/scmspain/frontend-mt--uilib-components/builds/3768262#L306
**Refactors**
The dark magic 🧙‍♂️:
```js
const baseFolders = Array.apply(null, Array(deep)).map(
Number.prototype.valueOf,	
0	
)
```
The easiest way 👍:
```js
[...Array(deep)]
```
> fix(sui-mono): avoid sui-mono to get wrong folders

- packages/sui-ssr/server/criticalCss/index.js
Start using the CriticalCSS service from the SCHIP infra.
> feat(sui-ssr): update the critical css service domain

- packages/sui-hoc/src/withOpenToggle.js
- packages/sui-hoc/src/withStateValueTags.js
- Fix isOpen initial state to withOpenToggle HOC
- Remove unnecessary `<div>` wrapper.
> fix(sui-hoc): fix isOpen initial state to withOpenToggle HOC

- packages/sui-consents/package.json
The package import does not work without this main key
> feat(sui-consents): add package json's main key

- packages/sui-studio/bin/sui-studio-test.js
- packages/sui-studio/package.json
running test in CI pass even though a tests fails, this pr makes the process exit on test error except when running in watch mode
> feat(sui-studio): exit with the test run result

- packages/sui-bundler/bin/sui-bundler-analyzer.js
- packages/sui-bundler/package.json
Download Bundle Analyzer dependencies on demand to improve installation times for the 95% of the times for CI and development.
> feat(sui-bundler): download analyzer dependencies only on demand

- packages/sui-studio/bin/sui-studio-test.js
This PR adds a way to set a `timeout` for the sui browser tests
None
```
sui-studio test --timeout 10000
```
> feat(sui-studio): add test timeout option

- packages/sui-studio/src/index.html
We need to incorporate the global recaptcha variables to be able to launch the corresponding tests with this functionality
> feat(sui-studio): prevent recaptcha global leak

- packages/sui-studio/package.json
Add **@testing-library/react-hooks** dependency to integrate a tool for react hooks testing
> feat(sui-studio): add @testing-library/react-hooks dependency

- packages/sui-studio/src/index.html
- packages/sui-studio/workbench/src/index.html
Add recaptcha globals to workbench 👀
> feat(sui-studio): add recaptcha globals to workbench

- packages/sui-hoc/src/withIntersectionObserver.js
- packages/sui-hoc/src/withOpenToggle.js
Cancel subscriptions before component is unmounted
Possible memory leak in HoC
> fix(sui-hoc): withIntersectionObserver - memory leak - cancel all subscriptions  and asyncronous tasks

- packages/sui-helpers/packages.js
Improve npm packages installed lazy by using some flags.
> feat(sui-helpers): improve installation time of lazy packages

- package.json
- packages/sui-ssr/package.json
- packages/sui-ssr/test/server/templateHtmlBuilderSpec.js
- packages/sui-ssr/test/templateHtmlBuilder.spec.js
Add sui-ssr test infra + first test: html body builder
> chore(sui-ssr): html template test

- packages/sui-pde/README.md
- packages/sui-pde/package.json
- packages/sui-pde/src/adapters/default.js
- packages/sui-pde/src/adapters/optimizely/index.js
- packages/sui-pde/src/pde.js
- packages/sui-pde/test/common/pdeSpec.js
Makes it possible to recover the datafile for server/client use cases
TODO
> Sui pde/get datafile

- packages/sui-ssr/server/utils/factory.js
Remove optional chaining in server code since it was working on our tests but not in the server build.
> fix(sui-ssr): fix optional chaining in server code

- package.json
> chore(META): use sui-mono v2

- packages/sui-studio/src/runtime-mocha/index.js
Fix making test folder really optional
> fix(packages/sui-studio): make test folder really optional

- packages/sui-pde/src/adapters/default.js
- packages/sui-pde/src/adapters/optimizely/index.js
- packages/sui-pde/src/pde.js
- packages/sui-pde/test/common/pdeSpec.js
Add getVariation fn in order to be able to get the variation without tracking the experiment as viewed
> Sui pde/get variation

- packages/sui-studio/src/environment-mocha/setupEnvironment.js
4 testing if the forwardRef is working fine.
> feat(sui-studio): add ref to mocha setup environment

- packages/sui-studio/src/components/utils.js
The component contextification disables the possibility tu ref the component provided by studio to demos and tests.
> feat(sui-studio): studio contextify component without loosing its reference

- packages/sui-studio/package.json
> feat(packages/sui-studio): upgrade react-dom and react version dependencies

- packages/sui-mono/bin/sui-mono-release.js
Remove chivatos.
Remove weird and nearly impossible to read hack for sequential Promises.
> feat(packages/sui-mono): improve sequential promise

- packages/sui-studio/src/index.html
Ignore window leaks so we don't need to keep adding globals.
> feat(packages/sui-studio): ignore window global leaks

- packages/sui-studio/README.md
- packages/sui-studio/test/setupEnvironmentSpec.js
Fix documentation and test in order to avoid confusions
> docs(packages/sui-studio): fix docs setupEnvironment example

- packages/sui-bundler/webpack.config.dev.js
- packages/sui-bundler/webpack.config.lib.js
- packages/sui-bundler/webpack.config.prod.js
- packages/sui-bundler/webpack.config.server.js
Add possibility to be able to resolve import dependencies from root of the project.
This allow us to simplify sui-studio and unirepo.
> feat(packages/sui-bundler): add alias to root process.cwd()

- packages/sui-test/bin/karma/config.js
Add modules resolver to make tests to work with this kind of imports:
```
import {AD} from 'utils/data/ad'
```
> feat(packages/sui-test): add module resolver for tests

- packages/sui-bundler/README.md
- packages/sui-bundler/package.json
- packages/sui-bundler/shared/config.js
- packages/sui-bundler/shared/minify-js.js
- packages/sui-bundler/webpack.config.prod.js
> feat(packages/sui-bundler): add new experimental minifier to test with sui-bundler

- packages/sui-studio/src/components/layout/_style.scss
Just to update sui-studio version (CI).
> feat(packages/sui-studio): deploy

- packages/sui-pde/package.json
Increase optimizely sdk version to latest
SDK 4.5 has several interesting new features:
https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/CHANGELOG.MD#450---february-17-2021
No breaking changes mentioned in changelog
Published a beta with those changes in order to test it: `@s-ui/pde@2.0.0-beta.0`
> feat(packages/sui-pde): increase optimizely sdk version

- packages/sui-studio/package.json
- packages/sui-studio/src/components/demo/_style.scss
- packages/sui-studio/src/components/layout/_style.scss
- packages/sui-studio/src/components/navigation/_style.scss
- packages/sui-studio/src/styles/_default.scss
- packages/sui-studio/workbench/src/components/Raw/index.scss
Add the scrolling behavior fixed in sui-studio v10 to v9 branch
The PR is targetting the sui-studio-v9 branch
> fix(sui-studio): studio workspace area scolling behavior workaround.

- packages/sui-ssr/package.json
Bump sui-ssr because previous GH action finished OK but release was not done.
https://github.com/SUI-Components/sui/runs/2399780001?check_suite_focus=true#step:8:14
> feat(sui-ssr): bump sui-ssr

- packages/sui-ssr/README.md
To force not published previous merge
> feat(packages/sui-ssr): trigger release

- packages/sui-pde/src/hooks/useFeature.js
fix error message for useFeature
> fix(packages/sui-pde): fix error message on useFeature hook

- package.json
- packages/babel-preset-sui/package.json
- packages/babel-preset-sui/src/index.js
- packages/babel-preset-sui/test/server/indexSpec.js
> feat(packages/babel-preset-sui): upgrade babel dependencies

- packages/sui-studio/workbench/src/index.html
Ignore window leaks also for `sui-studio dev`
@midudev was added to build: https://github.com/SUI-Components/sui/commit/d4d94025281f66f989a644f818716f38dc517d1f
> feat(packages/sui-studio): ignore leaks also for studio dev

- packages/sui-critical-css/src/middleware.cjs
> fix(packages/sui-critical-css): remove default value

- packages/sui-ssr/package.json
Upgrade express to latest version.
> feat(packages/sui-ssr): upgrade express dependency version to latest

- packages/sui-studio-create/package.json
- packages/sui-studio-create/src/index.js
Use @s-ui/studio@10 and adapt folders created.
> feat(packages/sui-studio-create): Use studio@10 when creating new studios

- packages/sui-component-dependencies/package.json
> feat(packages/sui-component-dependencies): Remove Rosetta from s-ui/component-dependencies

- packages/sui-theme/package.json
Fix path as its not copying the folders making the whole thing break on build time
> fix(packages/sui-theme): lib script copy path

- packages/sui-pde/README.md
Just adding a little bit more info about what sui-pde is and how to add attributes on activating an experiment
> docs(packages/sui-pde): context + how to attributes

- packages/sui-ssr/package.json
Avoid npm 7 duplicated versions
Same a https://github.com/SUI-Components/sui/pull/1150/files buf for sui-ssr@6
> feat(sui-ssr): fixed mime type

- packages/sui-studio/bin/sui-studio-generate.js
Create package.json for demos and add a private field to avoid publishing them.
Also create the package name accordingly to avoid duplicated workspaces.
> feat(packages/sui-studio): Add package.json to demo with private field

- packages/sui-studio/src/components/navigation/index.js
| Before | After |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/4168389/122549320-a465a880-d032-11eb-8476-02dad0a5e2e3.gif) | ![after](https://user-images.githubusercontent.com/4168389/122549025-551f7800-d032-11eb-92fe-4e579789170a.gif) |
> feat(packages/sui-studio): Make search case insensitive

- packages/sui-studio/scripts/prepare-only-changes.js
Fix builds that use `--only-changes` flag by keeping those components relative imported in demos.
> [fix] relative demo components in only-changes flag

- packages/sui-test/bin/karma/index.js
fix capture console option in karma config
> fix(packages/sui-test): fix capture console option in karma config

- packages/sui-theme/src/layout/_grid.scss
- packages/sui-theme/src/settings-compat-v7/_animation.scss
- packages/sui-theme/src/settings-compat-v7/_box-style.scss
- packages/sui-theme/src/settings-compat-v7/_components.scss
- packages/sui-theme/src/settings-compat-v7/_font.scss
- packages/sui-theme/src/settings-compat-v7/_spacing.scss
- packages/sui-theme/src/settings/_box-style.scss
- packages/sui-theme/src/settings/_spacing.scss
- packages/sui-theme/src/utils/_grid.scss
- packages/sui-theme/src/utils/_image.scss
- packages/sui-theme/src/utils/_opacity.scss
- packages/sui-theme/src/utils/_string.scss
Avoid using slash on SASS files.
> feat(packages/sui-theme): Migrate to avoid using slash as division on SASS

- packages/sui-test/bin/karma/config.js
- packages/sui-test/bin/karma/index.js
Something happened with the previous release because it does not work as expected.
In this PR I have move it to the config file and tested it with beta `4.33.0-beta.1`
> fix(packages/sui-test): improve karma config construction

- packages/sui-studio/src/styles/_settings.scss
[https://sass-lang.com/documentation/breaking-changes/slash-div](https://sass-lang.com/documentation/breaking-changes/slash-div)
- [PR sui-theme](https://github.com/SUI-Components/sui/pull/1207) 
- [PR sui-components](https://github.com/SUI-Components/sui-components/pull/1579) 
- [PR adevinta-spain-components](https://github.com/SUI-Components/adevinta-spain-components/pull/406)
> refactor(packages/sui-studio): slash as division

- packages/sui-react-initial-props/README.md
- packages/sui-ssr/README.md
- packages/sui-ssr/server/ssr/index.js
- packages/sui-ssr/status-codes.js
In some cases we should set a different kind of redirect status code: 302, 301 or even 307 if needed
> feat(packages/sui-ssr): allow to set a specific redirect status code

- packages/sui-theme/src/settings/_color.scss
Add social brand color for TikTok
add color for tiktok
https://jira.scmspain.com/browse/MTR-40934
> feat(packages/sui-theme): add color for tiktok social brand

- packages/sui-studio-create/package.json
- packages/sui-studio-create/src/index.js
> feat(packages/sui-studio-create): Migrate sui-studio-create to esm

- packages/sui-svg/bin/sui-svg-build.js
- packages/sui-svg/bin/sui-svg-demo.js
- packages/sui-svg/bin/sui-svg.js
- packages/sui-svg/package.json
- packages/sui-svg/templates/icon-component.js
> feat(packages/sui-svg): Migrate @s-ui/svg to ESM

- packages/sui-studio/bin/sui-studio-test.js
- packages/sui-test/bin/karma/config.js
- packages/sui-test/bin/karma/index.js
- packages/sui-test/bin/sui-test-browser.js
> feat(packages/sui-test): Add coverage param and exclude not needed files

- packages/sui-test/bin/karma/config.js
Test directory metrics are mostly 100% always 🤣 and we do NOT pretend to get coverage of our own tests (obvious).
We need to exclude them.
diferences in sui-components coverage:
from:
to:
> feat(packages/sui-test): add tests directory to excluded coverage directories

- packages/sui-pde/test/common/useExperimentSpec.js
Also fixing testing by using different experiment ids on each render
> test(packages/sui-pde): adding single tracking feature test

- packages/sui-ci/bin/sui-ci-release.js
- packages/sui-ci/bin/sui-ci-update-commit-status.js
- packages/sui-ci/src/constants.js
- packages/sui-ci/src/git.js
- packages/sui-ci/src/index.js
- packages/sui-ci/src/updateCommitStatus.js
- packages/sui-ci/test/server/updateCommitStatusSpec.js
- packages/sui-svg/CHANGELOG.md
- packages/sui-svg/package.json
> feat(packages/sui-ci): Migrate to ESM

- packages/sui-test/bin/karma/index.js
Add the JSON-summary report in order to update and easy visualize the current tests coverage status in our README.md top level file of the project(if the badge exists).
https://github.com/SUI-Components/sui-components/pull/1621
> feat(packages/sui-test): add json-summary coverage report

- .github/workflows/node.js.yml
- packages/sui-critical-css/package.json
- packages/sui-critical-css/src/extract-from-app.js
- packages/sui-critical-css/src/extract-from-url.js
Add healthCheck support to sui-critical-css to be sure server is available before creating critical css.
> feat(packages/sui-critical-css): Add health check support

- packages/sui-studio-utils/src/domain-builder/index.js
Nowadays if you subscribe to a use case in a component the demo and the tests fail since is not mocked.
This PR adds subscribe support. See example:
```js
/*
domain: DomainBuilder.extend({domain})
.for({useCase: 'get_current_user_use_case'})
.respondWith({
success: user
})
.for({useCase: 'get_private_profile_user_use_case'})
.respondWith({
success: profile
})
.for({useCase: 'update_profile_name_user_use_case'})
.respondWith({
success: {
name: 'Luke Skywalker'
}
})
.build({
inlineError: true
})
*/
it('should render non authenticated content2', async () => {
// Given
const props = {
children: ({isLoading, isAuthenticated, user}) =>
isLoading ? (
<div data-testid="skeleton" />
) : (
isAuthenticated && <p>{user.userName}</p>
)
}
// When
setup(props)
// Then …
```
> feat(sui-studio-utils): add mock subscribe support

- packages/sui-studio-utils/src/domain-builder/index.js
This PR adds subscriptions legacy domain support (v1)
None
None
> feat(packages/sui-studio-utils): add subscriptions domain v1 support

- packages/sui-ssr/bin/sui-ssr-build.js
- packages/sui-studio/bin/sui-studio-dev.js
Add link-package short alias `-l` and `-L` to `sui-ssr` and `sui-studio` as in `sui-bundler`.
> Link package short alias to sui-ssr and sui-studio 

- packages/sui-bundler/shared/module-rules-babel.js
Make use of babelCache in order to cache some babel transformations.
> feat(packages/sui-bundler): Improve build times by caching some transformations

- packages/sui-bundler/package.json
Bump sui-bundler dependencies. They're compatible with the actual code and nothing should be done.
> feat(packages/sui-bundler): Upgrade sui-bundler deps

- packages/sui-i18n/README.md
Added documentation for dynamic translations method.
> docs(packages/sui-i18n): add dynamic translations example

- packages/sui-pde/src/adapters/optimizely/index.js
- packages/sui-pde/test/common/pdeSpec.js
audiences in feature flags aren't working correctly as we weren't passing by the application attributes to optimizely
> fix(packages/sui-pde): isFeatureEnabled pass by application attributes

- packages/sui-domain/README.md
Add example how to unsubscribe a use case to the readme
> docs(packages/sui-domain) add example how to unsubscribe a usecase

- packages/sui-react-initial-props/package.json
- packages/sui-react-initial-props/src/withInitialProps.tsx
- packages/sui-react-initial-props/test/browser/browserSpec.js
- packages/sui-react-initial-props/test/server/serverSpec.js
Fix wrong behaviour not returning initial props.
> fix(packages/sui-react-initial-props): Be sure we have initial props when hydrating

- packages/sui-theme/src/components/thumbnail/_basic.scss
- packages/sui-theme/src/index.scss
We need to add new default values for thumbnail basic.
Related PR -> https://github.com/SUI-Components/adevinta-spain-components/pull/435
https://github.com/SUI-Components/adevinta-spain-components/pull/435
> feat(packages/sui-theme): Add default values for thumbnail basic

- packages/sui-bundler/README.md
> docs(packages/sui-bundler): fix typo

- packages/sui-studio/bin/sui-studio-generate.js
Add a new flag to create components using new compiler.
> feat(packages/sui-studio): Add new flag to create components using new compiler

- packages/sui-react-router/src/Link.js
- packages/sui-react-router/test/browser/LinkSpec.js
Remove unnecessary anchor prop & add test
> feat(packages/sui-react-router): remove unnecessary prop & add test

- packages/sui-react-router/src/.npmignore
- packages/sui-react-router/src/Link.js
> fix(packages/sui-react-router): Avoid using object on pushing new location

- packages/sui-domain/src/index.js
Changed the import/export syntax, thank you @midudev to share this tip 😊
> refactor(packages/sui-domain): change import/export syntax

- packages/sui-domain/README.md
Update documentation to create the useCases object
> docs(packages/sui-domain): update domanin documentation

- packages/sui-theme/src/components/atom/input/_placeholders.scss
- packages/sui-theme/src/components/atom/input/_settings.scss
add new variable: border input focus
> feat(packages/sui-theme): add new variable: border input focus

- packages/sui-lint/src/helpers.js
Get range of commits only for CI
> feat(packages/sui-lint): Get range of commits only for CI

- packages/sui-lint/eslintrc.js
New check for file extensions so we start migrating to ESModules.
> feat(packages/sui-lint): Add rule to check extensions on files

- packages/sui-js-compiler/package.json
Update SWC core and helpers to latest versions
ℹ️  swc core has several fixes and performance improvements: https://github.com/swc-project/swc/blob/main/CHANGELOG.md
> fix(packages/sui-js-compiler): use last version of swc core and helpers

- packages/sui-precommit/bin/sui-precommit-install.js
- packages/sui-precommit/bin/sui-precommit-run.js
- packages/sui-precommit/bin/sui-precommit.js
- packages/sui-precommit/package.json
Stop using CommonJS and move package to ESModules
> feat(packages/sui-precommit): Migrate package to ESModules

- packages/sui-widget-embedder/bin/sui-widget-embedder-generate.js
Stop using `colors` package as it's getting blocked some processes.
> feat(packages/sui-widget-embedder): Stop using colors package and use our own helper

- packages/sui-studio/bin/sui-studio-migrate.js
- packages/sui-theme/src/settings-compat-v7/_components.scss
Fix variable declaration order to:
1.- Declare variable
2.- Use declared variable
> fix(packages/sui-theme): fix variable declaration order

- packages/sui-lint/src/helpers.js
Fix the conditional used on the code so we make the first commit of the Pull Request to check the correct files.
> fix(packages/sui-lint): Use correct conditional for PRs on Actions

- packages/sui-component-dependencies/package.json
> chore(packages/sui-component-dependencies): remove depretacted libraries

- packages/sui-precommit/bin/sui-precommit.js
Use correct commit-msg hook name.
> fix(packages/sui-precommit): Fix commit-msg hook

- packages/sui-studio/src/runtime-mocha/index.js
There was a problem importing components to browser in 11.2.0 when running tests
> fix(packages/sui-studio): fix studio import components

- packages/sui-widget-embedder/bin/sui-widget-embedder-build.js
use `rmSync` instead `rmdirSync`
> fix(packages/sui-widget-embedder): fix rm fn to delete public folder

- packages/sui-mono/src/config.js
Fix sui-mono optional chaining break
> feat(packages/sui-mono): fix optional chaining break

- packages/sui-bundler/test/server/integration/features-app/src/app.js
- packages/sui-bundler/test/server/integration/features-app/src/features/index.js
- packages/sui-bundler/test/server/integrationSpec.js
- packages/sui-bundler/test/server/linkLoaderSpec.js
> test(packages/sui-bundler): Enable sui-bundler test

- package.json
- packages/sui-studio-create/src/index.js
Adapt sui-studio-create to use latest deps and configs
> feat(packages/sui-studio-create): Adapt sui-studio-create to use latest deps

- packages/sui-polyfills/src/index.js
> fix(packages/sui-polyfills): Add new polyfill for Object.fromEntires

- packages/sui-test-contract/package.json
> feat(packages/sui-test-contract): bump

- packages/sui-bundler/shared/minify-js.js
- packages/sui-bundler/test/server/integration/legacy-browsers-app/src/app.js
- packages/sui-bundler/test/server/integrationSpec.js
> test(packages/sui-bundler): add optional error binding test

- packages/sui-i18n/README.md
- packages/sui-i18n/test/fixtures/languages.js
- packages/sui-i18n/test/i18nSpec.js
> docs(packages/sui-i18n): Add i18n docs regarding plurals and add test

- packages/sui-widget-embedder/README.md
- packages/sui-widget-embedder/compiler/production.js
> feat(packages/sui-widget-embedder): Remove vendor from widget embedder config

- packages/sui-dashboard/bin/sui-dashboard-components.js
- packages/sui-dashboard/bin/sui-dashboard.js
- packages/sui-dashboard/package.json
- packages/sui-dashboard/src/index.js
> feat(packages/sui-dashboard): Migrate to esm

- packages/sui-hoc/package.json
- packages/sui-hoc/src/avoidSSRRender.js
- packages/sui-hoc/src/index.js
- packages/sui-hoc/src/withAllContexts.js
- packages/sui-hoc/src/withContext.js
- packages/sui-hoc/src/withIntersectionObserver.js
- packages/sui-hoc/src/withOpenToggle.js
- packages/sui-hoc/src/withSUIContext.js
- packages/sui-hoc/src/withStateValue.js
- packages/sui-hoc/src/withStateValueTags.js
- packages/sui-hoc/src/withSwitchValue.js
> feat(packages/sui-hoc): Migrate to ESM

- packages/sui-html-tagger/package.json
- packages/sui-html-tagger/test/indexSpec.js
> feat(packages/sui-html-tagger): Migrate to ESM

- packages/sui-mono/bin/sui-mono-commit-all.js
- packages/sui-mono/src/config.js
- packages/sui-mono/src/prompter-manager.js
- packages/sui-mono/test/server/checkSpec.js
- packages/sui-mono/test/server/configSpec.js
Fix release error when repo is monopackage (with no workspaces)
`✖ Error: Error: Root/package.json: ENOENT: no such file or directory, open 'Root/package.json'`
> fix(packages/sui-mono): fix release for monopackage

- packages/sui-test/README.md
- packages/sui-test/bin/karma/index.js
- packages/sui-test/bin/sui-test-browser.js
- packages/sui-test/package.json
> feat(packages/sui-test): Add new headless flag

- packages/sui-studio/bin/sui-studio-test.js
Allow flag to use headless mode on Sui-studio test components.
> feat(packages/sui-studio): Add support to headless on sui-studio test

- packages/sui-js-compiler/package.json
Update SWC compiler deps to latest versions
Beta for testing purposes `@s-ui/js-compiler@1.18.0-beta.0`
> feat(packages/sui-js-compiler): update swc to latest versions

- packages/sui-widget-embedder/bin/sui-widget-embedder-build.js
- packages/sui-widget-embedder/bin/sui-widget-embedder-dev.js
- packages/sui-widget-embedder/bin/sui-widget-embedder-generate.js
- packages/sui-widget-embedder/package.json
Update commander to v8.3.0
Beta for testing purposes: @s-ui/widget-embedder@5.8.0-beta.0
> feat(packages/sui-widget-embedder): update commander to v8.3.0

- packages/sui-dashboard/package.json
> feat(packages/sui-dashboard): update commander version

- packages/sui-lint/.prettierrc.js
- packages/sui-lint/bin/sui-lint-js.js
- packages/sui-lint/bin/sui-lint-sass.js
- packages/sui-lint/package.json
- packages/sui-lint/src/helpers.js
- Update dependencies
- Add support to `fix` and `addFixed` options to sass lint.
Beta for testing purposes @s-ui/lint@4.11.0-beta.2
> feat(packages/sui-lint): update dependencies

- packages/sui-react-initial-props/test/browser/browserSpec.js
This PR add some tests to react initial props in client-side
> test(packages/sui-react-initial-props): add client tests

- packages/sui-ci/bin/sui-ci-update-commit-status.js
- packages/sui-ci/package.json
Update dependencies
- commander 👉 8.3.0 - The latest version used by sui tools
- node-fetch 👉 3.2.3 - The latest
> feat(packages/sui-ci): update dependencies

- packages/sui-test/bin/sui-test-browser.js
- packages/sui-test/bin/sui-test-server.js
- packages/sui-test/package.json
Update commander 👉 8.3.0 - The latest version used by sui tools
Beta for testing purposes `@s-ui/test@8.8.0-beta.0`
> feat(packages/sui-test): update commander dependency

- packages/sui-studio/bin/helpers/walker.js
- packages/sui-studio/bin/migrations/demo-folders.js
- packages/sui-studio/bin/migrations/test-folders.js
- packages/sui-studio/bin/sui-studio-build.js
- packages/sui-studio/bin/sui-studio-dev.js
- packages/sui-studio/bin/sui-studio-generate.js
- packages/sui-studio/bin/sui-studio-test.js
- packages/sui-studio/bin/sui-studio.js
- packages/sui-studio/package.json
Use new commander version used across Sui-tools.
> feat(packages/sui-studio): Use new commander version

- packages/sui-changelog/bin/index.js
- packages/sui-changelog/package.json
- packages/sui-changelog/src/config.js
- packages/sui-changelog/src/helpers.js
- packages/sui-changelog/src/strategies/factory.js
- packages/sui-changelog/src/strategies/packageLock.js
- packages/sui-changelog/src/strategies/shrinkwrap.js
> feat(packages/sui-changelog): Migrate to ESM and upgrade commander

- .github/workflows/node.js.yml
- package.json
- packages/sui-consents/package.json
- packages/sui-decorators/package.json
- packages/sui-domain/package.json
- packages/sui-hoc/package.json
- packages/sui-html-tagger/package.json
- packages/sui-i18n/package.json
- packages/sui-js-compiler/README.md
- packages/sui-js/package.json
- packages/sui-lint/package.json
- packages/sui-mockmock/package.json
- packages/sui-pde/package.json
- packages/sui-react-context/package.json
- packages/sui-react-head/package.json
- packages/sui-react-initial-props/package.json
- packages/sui-react-router/package.json
- packages/sui-sass-loader/package.json
- packages/sui-studio-utils/package.json
- packages/sui-studio/bin/sui-studio-generate.js
- packages/sui-svg/README.md
- packages/sui-test-contract/package.json
- packages/sui-test-e2e/package.json
- packages/sui-test/package.json
- packages/sui-theme/package.json
- packages/sui-widget-embedder/package.json
> chore(Root): Use ultra-runner instead native npm run

- packages/sui-studio/bin/sui-studio-generate.js
…on test code.
Adding the component source file extension to the auto-generated import code for `sui-studio`.
N/A
The following shouldn't be an issue anymore:
> feat(packages/sui-studio): add .js extension to Component import 

- packages/sui-test/bin/sui-test-server.js
- packages/sui-test/package.json
> feat(packages/sui-test): Use mocha@10

- packages/sui-js/README.md
- packages/sui-js/src/array/index.js
- packages/sui-js/test/arraySpec.js
Provide a unbiased algorithm to shuffle an array based on the algorithm described [here](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm)
```
import {shuffleArray} from '@s-ui/js/lib/array'
const list = [1,2,3,4,5]
shuffleArray(list)
```
> feat(packages/sui-js): Added util to shuffle an array

- .gitignore
- packages/sui-test-contract/package.json
- packages/sui-test-contract/src/setup/index.js
> feat(packages/sui-test-contract): Upgrade msw and pact versions and adapt import

- packages/sui-ssr/bin/sui-ssr-archive.js
- packages/sui-ssr/bin/sui-ssr-build.js
- packages/sui-ssr/bin/sui-ssr.js
- packages/sui-ssr/compiler/server.js
- packages/sui-ssr/package.json
Remove dependencies from sui-ssr to avoid installing them and use native alternatives.
> feat(packages/sui-ssr): Remove copy-webpack-plugin and rimraf as they're not needed

- packages/sui-studio/bin/sui-studio-generate.js
Change the default template package-json component file npm run script
> feat(packages/sui-studio): Update template

- README.md
Update all packages list in readme
> docs(Root): update packages list

- .github/CODEOWNERS
[docs(owners)--update-codeowners](https://github.com/ferminhg/sui/tree/docs(owners)--update-codeowners)
Update codeowners
>  docs(owners)--update-codeowners

- packages/sui-precommit/bin/sui-precommit.js
- packages/sui-precommit/package.json
Update dset to last version and [fix vulnerability](https://github.com/SUI-Components/sui/security/dependabot/23)
> feat(packages/sui-precommit): update dset to latest version

- packages/sui-decorators/package.json
- Update redis-mock dependency to latest
- Update redis dependency to last v3 version and [fix vulnerability](https://github.com/SUI-Components/sui/security/dependabot/1)
> feat(packages/sui-decorators): update redis-mock and redis dependencies

- packages/sui-studio/bin/helpers/copyStaticFiles.js
- packages/sui-studio/src/components/workbench/index.js
- packages/sui-studio/src/constants.js
- packages/sui-studio/src/routes.js
Delete excess code for ux tab
Closes [2376](https://github.com/SUI-Components/sui-components/issues/2376)
According [#2376](https://github.com/SUI-Components/sui-components/issues/2376)
> feat(packages/sui-studio): Delete excess code for ux tab

- packages/sui-theme/README.md
- packages/sui-theme/src/classes/README.md
- Add docs about breakpoints and media queries.
- Remove utility classes docs from the main README (moved to its corresponding folder since it's a PoC and the exposed file shouldn't be imported from the entry point).
> docs(packages/sui-theme): update docs

- packages/sui-studio/src/components/documentation/markdown.css
- packages/sui-studio/src/styles/components/_tabs.scss
**Small restyle to force a release**
No issue related, just forcing with a minimum CSS change (a real improvement of course)
> release(packages/sui-studio): Small style to force a release

- packages/sui-studio/src/styles/components/_tabs.scss
remove not used scss
After https://github.com/SUI-Components/sui/pull/1498/, there is some scss not used.
https://github.com/SUI-Components/sui/pull/1498/
> refactor(packages/sui-studio): remove not used scss

- packages/sui-test-contract/README.md
- packages/sui-test-contract/src/setup/index.js
Enable specific apiUrl for each endpoint interaction
> feat(packages/sui-test-contract): add custom api url for each endpoint

- packages/sui-js-compiler/package.json
- packages/sui-js-compiler/test/server/index.js
Update swc compiler dependencies
Beta for testing purposes: @s-ui/js-compiler@1.21.0-beta.0
> feat(packages/sui-js-compiler): update swc deps

- packages/sui-studio/src/components/layout/_style.scss
- packages/sui-studio/src/components/layout/index.js
- packages/sui-studio/src/components/navigation/_style.scss
- packages/sui-studio/src/components/navigation/index.js
- packages/sui-studio/src/components/workbench/_style.scss
- packages/sui-studio/src/styles/_default.scss
- packages/sui-studio/src/styles/_settings.scss
- fix the padding affecting to the workbench area
- fix styles affecting to the workbench area elements
- SearchInput is fixed on top and it is not included in the scrollbar
> feat(packages/sui-studio): fix styles

- packages/sui-bundler/bin/sui-bundler.js
- packages/sui-studio/src/components/navigation/_style.scss
> feat(packages/sui-bundler): mispelling error

- packages/sui-test-contract/src/setup/utils.js
- packages/sui-test-contract/test/server/setupSpec.js
fix interaction data when setting same request path and different body
> fix(packages/sui-test-contract): fix interaction data

- packages/sui-i18n/src/i18n.js
- packages/sui-i18n/test/fixtures/languages.js
- packages/sui-i18n/test/i18nSpec.js
Restore first slash when token is validated in i18n.url.
> fix(packages/sui-i18n): restore slash when token is validated in i18n.url

- packages/sui-studio/bin/sui-studio-generate.js
This PR fixes fixes post install script dividing into different elements in the spawn array
> fix(packages/sui-studio): update studio postinstall

- packages/sui-bundler/package.json
- packages/sui-js/package.json
- packages/sui-mono/package.json
- packages/sui-sass-loader/package.json
- packages/sui-ssr/package.json
- packages/sui-svg/package.json
- packages/sui-test/package.json
Fix the current Dependabot alerts:
> fix security issues

- .github/workflows/node.js.yml
Not needed since we're not reviewing/using those metrics at all.
> chore(Root): stop sending devhose metrics

- packages/sui-pde/package.json
Update optimizely version to fix vulnerability
> feat(packages/sui-pde): update version optimizely

- packages/sui-ssr/package.json
Update express dependency to fix a security issue
> fix(packages/sui-ssr): update express dependency to fix a security issue

- packages/sui-bundler/bin/sui-bundler-lib.js
Error en el lib
Cuando petaba el run del lib, no se detenía la ejecución y daba un exit 0
> fix(packages/sui-bundler): Fix bundler error display

- packages/sui-react-web-vitals/src/index.js
This PR uses `cwv` method of the logger instead of `log` to log cwv metrics
None
> feat(packages/sui-react-web-vitals): use cwv instead of log

- packages/sui-react-web-vitals/src/index.js
> fix(packages/sui-react-web-vitals): use metricsAllChanges and add more default metrics

- packages/sui-bundler/bin/sui-bundler-build.js
- packages/sui-test-contract/package.json
Add option to save stats.json in public to compare bundle size if wanted
> feat(packages/sui-bundler): Add option to save stats.json in build

- packages/sui-mono/README.md
- packages/sui-mono/bin/sui-mono-release.js
This PR adds package-lock file update support to `sui-mono`
None
None
> feat(packages/sui-mono): add lockfile support

- packages/sui-mono/bin/sui-mono-release.js
This avoids update lock file if no package is updated
None
> feat(packages/sui-mono): avoid update lock file if no package is updated

- packages/sui-react-web-vitals/package.json
Update Web Vitals lib to 3.5.0
> feat(packages/sui-react-web-vitals): update Web Vitals lib to 3.5.0

- packages/sui-bundler/package.json
Update version due to vulnerability
https://www.npmjs.com/package/postcss?activeTab=versions
https://github.mpi-internal.com/scmspain/frontend-re--ut-web-app/security/dependabot/16
> feat(packages/sui-bundler): update postcss version

- packages/sui-ssr/server/middlewares/ssr.js
> feat(packages/sui-ssr): revert csp report

- packages/sui-react-web-vitals/src/index.js
> feat(packages/sui-react-web-vitals): add INP eventType attribution

- packages/sui-react-web-vitals/src/index.js
In case `routeid` is present, report it.
N/A
N/A
> feat(packages/sui-react-web-vitals): add routeId field to logger

- packages/sui-bundler/factories/createDevServerConfig.js
SUI BUNDLER
Allow statics folder for Statics in Dev
> feat(packages/sui-bundler): Allow statics folder for Statics in Dev

- packages/sui-studio/bin/sui-studio-dev.js
This PR disables filesystem cache in dev mode
None
None
> feat(packages/sui-studio): disable filesystem cache in dev mode

- packages/sui-studio/package.json
> feat(packages/sui-studio): upgrade Chai to fix vulnerability

- .github/workflows/node.js.yml
- packages/sui-mono/bin/sui-mono-check.js
- packages/sui-mono/src/check.js
Make `sui-mono` be able to release multiple packages from changes in just one commit, like in this case: https://github.com/SUI-Components/sui/pull/1707/files
> [sui-mono] multiple releases per commit

- packages/sui-test/bin/karma/config.js
This PR fixes some aliases for React 18 compatibility
> feat(packages/sui-test): update react aliases

- packages/sui-react-web-vitals/src/index.js
- packages/sui-react-web-vitals/test/browser/indexSpec.js
Add `deviceMemory`, `effectiveType`, and `hardwareConcurrency` device information to send to Open Search.
> feat(packages/sui-react-web-vitals): add some device data to sent to Open Search

- packages/sui-react-web-vitals/src/index.js
Skip the empty target attributions until the [bug](https://github.com/GoogleChrome/web-vitals/issues/335) will be fixed
> feat(packages/sui-react-web-vitals): skip empty targets

- packages/sui-react-context/package.json
- packages/sui-react-context/src/index.tsx
- packages/sui-react-context/tsconfig.json
Fix compilation and type export.
Changes are cherry-picked from https://github.com/SUI-Components/sui/pull/1614.
> [FIX] react context compilation & types

- packages/sui-react-web-vitals/package.json
**v3.5.2** (2024-01-25)
> Pick the first non-null target for INP attribution [#421](https://github.com/GoogleChrome/web-vitals/pull/421)
**v3.5.1** (2023-12-27)
> Add extra guard for PerformanceEventTiming not existing [#403](https://github.com/GoogleChrome/web-vitals/pull/403)
> feat(packages/sui-react-web-vitals): upgrade web vitals package

- packages/sui-ssr/server/hooksFactory/index.js
This PR fixes internal error middleware
> fix(packages/sui-ssr): internal error

- packages/sui-bundler/webpack.config.client.dev.js
This PR fixes an issue in the bundler when using ssr dev mode
> fix(packages/sui-bundler): ssr dev

- packages/sui-studio/bin/sui-studio-generate.js
Add jest command and template to sui-studio to generate script
> feat(packages/sui-studio): Add jest command and template

- packages/sui-react-web-vitals/src/index.js
The attribution target for the INP is  `attribution.interactionTarget` now
> fix(packages/sui-react-web-vitals): add expected attribution for inp

- packages/eslint-plugin-sui/src/rules/factory-pattern.js
- packages/eslint-plugin-sui/test/server/factory-pattern.js
Add new rules according to our current agreements
> feat(packages/eslint-plugin-sui): factory pattern rules update

- packages/sui-pde/src/components/experiment.js
- packages/sui-pde/src/components/feature.js
Add missing adapterId and shouldTrackExperimentViewed to Feature and Experiment component on sui-pde
> feat(packages/sui-pde): Add adapterId and shouldTrackExperimentViewed to Feature and Experiment components

- package-lock.json
- packages/sui-lint/eslintrc.js
- packages/sui-lint/package.json
**The purpose of this PR is add the testing-library rules to our Jest tests on FC Portal.**
> feat(packages/sui-lint): Add TESTING_LIBRARY_RULES on sui-lint for Jest folders

- package-lock.json
- packages/sui-polyfills/src/index.js
Added polyfills for Array.prototype.at, Promise.allSettled and Promise in order to be able to support the last version of the react-pdf lib https://github.com/wojtekmaj/react-pdf?tab=readme-ov-file#compatibility
> feat(packages/sui-polyfills): Added polyfills

- packages/sui-performance/src/index.js
This PR moves idle queue inside the method to avoid global objects
> feat(packages/sui-performance): move queue

- packages/sui-bundler/webpack.config.client.dev.js
- packages/sui-bundler/webpack.config.lib.js
Add TypeScript support for the bundling modes:
- server dev
- lib
> feat(packages/sui-bundler): add ts support for all the bundling modes

- README.md
Add Project Stats in the README
[Repobeats Axiom](https://repobeats.axiom.co/)
> docs(Root): add project stats

- packages/babel-preset-sui/src/defaults.js
Update default node version to 18
> feat(packages/babel-preset-sui): update default Node version to 18

- package-lock.json
- packages/sui-domain/package.json
Upgrade axios dependency to solve https://github.com/advisories/GHSA-8hc4-vh64-cxmj
> feat(packages/sui-domain): Update axios dependency due to high security vulnerability

- packages/eslint-plugin-sui/src/utils/decorators.js
Fix Error: https://github.mpi-internal.com/scmspain/frontend-re--ut-web-app/actions/runs/7193388/job/22413221#step:5:178
> fix(packages/eslint-plugin-sui): Fix null check

- .gitignore
- packages/eslint-plugin-sui/src/rules/decorator-inline-error.js
- packages/eslint-plugin-sui/test/server/decorator-inline-error.js
> Fix decorator-inline-error

- packages/sui-bundler/webpack.config.client.dev.js
Standardize the entry point chunk names to match production one
> feat(packages/sui-bundler): change bundler entry point name

- package-lock.json
- packages/sui-mockmock/package.json
- packages/sui-test-contract/bin/sui-test-contract-publish.js
- packages/sui-test-contract/package.json
* `@s-ui/test-contract`: Switch from `@pact-foundation/pact` to `@pact-foundation/pact-node`, in order to avoid `axios` dependency.
* `@s-ui/mockmock`: Upgrade `axios` dependency.
* Upgrade root `package-lock.json`
> update deps & fix vulnerability alert on axios version

- packages/sui-pde/src/adapters/default.js
This PR adds default object return for the `DefaultAdapter`
> feat(packages/sui-pde): update default adapter

- package-lock.json
- packages/sui-logger/README.md
- packages/sui-logger/package.json
- packages/sui-logger/src/client.js
- packages/sui-logger/src/index.js
- packages/sui-logger/src/logger.js
- packages/sui-logger/src/server.js
- packages/sui-logger/src/server/expressMiddleware/DataDogLogger.js
- packages/sui-logger/src/server/expressMiddleware/StdoutLogger.js
- packages/sui-logger/src/server/expressMiddleware/index.js
- packages/sui-logger/src/server/index.js
- packages/sui-logger/src/server/logger/index.js
- packages/sui-logger/src/server/utils/format.js
- packages/sui-logger/src/traceInitialProps.js
- packages/sui-logger/test/browser/indexSpec.js
- packages/sui-logger/test/helpers/routes.js
- packages/sui-logger/test/server/dataDogLoggerSpec.js
- packages/sui-logger/test/server/formatConsoleSpec.js
- packages/sui-logger/test/server/indexSpec.js
- packages/sui-logger/test/server/performanceSpec.js
- packages/sui-logger/test/server/stdoutLoggerSpec.js
- packages/sui-logger/test/server/traceInitialPropsSpec.js
Migrate sui-logger from inner source
> feat(packages/sui-logger): Migrate sui-logger from inner source

- package-lock.json
- packages/sui-logger/README.md
- packages/sui-logger/package.json
- packages/sui-logger/src/index.js
- packages/sui-logger/test/browser/indexSpec.js
- packages/sui-logger/test/server/indexSpec.js
Rename Reporter and migrate to SWC
> refactor(packages/sui-logger): rename Reporter and migrate to SWC

- packages/sui-logger/README.md
> feat(packages/sui-logger): improve the documentation

- packages/sui-logger/src/client.js
- packages/sui-logger/src/server.js
- packages/sui-logger/test/server/indexSpec.js
> refactor(packages/sui-logger): add missed Trackers in client and server level

- packages/sui-decorators/src/decorators/error.js
> feat(packages/sui-decorators): remove console.log

- package-lock.json
- packages/sui-bundler/package.json
- packages/sui-bundler/shared/index.js
- packages/sui-bundler/shared/module-rules-sass.js
- packages/sui-bundler/webpack.config.client.dev.js
- packages/sui-bundler/webpack.config.dev.js
This PR adds tailwind support to sui-bundler
> feat(packages/sui-bundler): add tailwind support

- packages/sui-pde/README.md
> docs(packages/sui-pde): fix typo

- packages/sui-segment-wrapper/src/repositories/googleRepository.js
- packages/sui-segment-wrapper/src/segmentWrapper.js
- packages/sui-segment-wrapper/test/segmentWrapperSpec.js
- packages/sui-segment-wrapper/test/stubs.js
Sets GA `user_id` on every `identify` call to Segment Analytics.
> feat(packages/sui-segment-wrapper): set ga user id on identify

- packages/sui-logger/src/server.js
> fix(packages/sui-logger): add missing trackers param

- packages/sui-i18n/src/adapters/polyglot.js
This PR forward options from adapter to polyglot
> feat(packages/sui-i18n): add options

- packages/sui-bundler/scripts/postinstall.js
> feat(packages/sui-bundler): modify the postinstall tsconfig template

- packages/sui-studio/src/components/demo/_style.scss
- packages/sui-studio/src/components/demo/index.js
- packages/sui-studio/src/components/layout/index.js
- packages/sui-studio/src/components/preview/_style.scss
- packages/sui-studio/src/index.html
- packages/sui-studio/src/styles/components/_tabs.scss
- Add some icon button aria-labels
- Improves clicking area of theme selectors
- relocates fullscreen button a little bit top
> fix(packages/sui-studio): improve sui-studio accessibility lighthouse metrics

- packages/sui-dashboard/package.json
- packages/sui-dashboard/src/index.js
Update require fn to be ready to node@20
> feat(packages/sui-dashboard): compatible with node 20 require fn way

- package-lock.json
- packages/sui-studio/src/styles/_settings.scss
> fix(packages/sui-studio): wrong color name token

- packages/sui-studio/src/components/layout/_style.scss
> fix(packages/sui-studio): a11y color-contrast improvements

- packages/sui-segment-wrapper/src/segmentWrapper.js
Get GA client id synchronously
> feat(packages/sui-segment-wrapper): get client id synchronously

- packages/sui-segment-wrapper/src/index.js
- packages/sui-segment-wrapper/src/repositories/googleRepository.js
- packages/sui-segment-wrapper/src/segmentWrapper.js
Send **Adobe MCVID** along all the **GA4 events**.
> feat(packages/sui-segment-wrapper): send adobe mvcid along the ga event

- package-lock.json
- packages/sui-dashboard/bin/sui-dashboard-components.js
- packages/sui-dashboard/package.json
- packages/sui-dashboard/src/index.js
This feature ables the possibility to define which part of the semver version gets stacked in the output and mark if its outdated
> feat(packages/sui-dashboard): add several extra commands

- packages/sui-polyfills/src/index.js
> feat(packages/sui-polyfills): Added replaceAll polyfills to support chrome version >= 49

- packages/sui-polyfills/src/index.js
> feat(packages/sui-polyfills): add object group by polyfill

- packages/sui-react-web-vitals/README.md
- packages/sui-react-web-vitals/src/index.js
- packages/sui-react-web-vitals/test/browser/indexSpec.js
- Add LCP Subpart metric
- Add Test
- Rename variable name
> feat(packages/sui-react-web-vitals): add LCP Subpart metrics to send to logger

- packages/sui-segment-wrapper/src/repositories/googleRepository.js
- packages/sui-segment-wrapper/test/segmentWrapperSpec.js
analytics_storage is being mapped to DENIED always do to a bug in the code
> fix(packages/sui-segment-wrapper): map analytics_storage to correct value

- packages/sui-decorators/src/decorators/tracer/index.js
- packages/sui-decorators/src/helpers/isNode.js
Stop using CJS syntax to detect the Node environment.
> remove cjs syntax

- packages/sui-critical-css/src/extract-from-url.js
> fix(packages/sui-critical-css): display close all error

- packages/sui-critical-css/src/extract-from-url.js
> feat(packages/sui-critical-css): increase critical timeout

- packages/sui-critical-css/src/extract-from-url.js
> feat(packages/sui-critical-css): add timeout to networkidle

- packages/sui-studio/src/components/theme-mode/index.js
- packages/sui-studio/workbench/src/app.js
- packages/sui-studio/workbench/src/components/Header/index.js
- packages/sui-studio/workbench/src/components/Header/index.scss
- packages/sui-studio/workbench/src/components/Raw/index.js
- packages/sui-studio/workbench/src/components/Raw/index.scss
- packages/sui-studio/workbench/src/components/Root/index.js
- packages/sui-studio/workbench/src/components/Root/index.scss
- packages/sui-studio/workbench/src/components/Workbench/Workbench.js
- packages/sui-studio/workbench/src/components/Workbench/index.js
- packages/sui-studio/workbench/src/components/Workbench/queryStringToJSON.js
- packages/sui-studio/workbench/src/styles.scss
> feat(packages/sui-studio): add theme mode to dev runner

- packages/sui-logger/src/server/expressMiddleware/DataDogLogger.js
This PR enables to setup a custom host and port for Datadog server
> feat(packages/sui-logger): add host and port for datadog

- package-lock.json
- packages/sui-segment-wrapper/README.md
- packages/sui-segment-wrapper/src/segmentWrapper.js
- packages/sui-segment-wrapper/test/segmentWrapperSpec.js
This PR add `userIdPrefix` config param for identify events
> feat(packages/sui-segment-wrapper): add userIdPrefix prop

- packages/sui-segment-wrapper/src/segmentWrapper.js
- packages/sui-segment-wrapper/test/segmentWrapperSpec.js
This PR fixes an issue when identify is called with no user id
> feat(packages/sui-segment-wrapper): update userid parsing

- packages/sui-segment-wrapper/src/repositories/googleRepository.js
This PR removes expected error that causes false positives in logs
> feat(packages/sui-segment-wrapper): remove expected error

- packages/sui-segment-wrapper/src/middlewares/source/pageData.js
- packages/sui-segment-wrapper/test/middlewares/pageDataMiddlewareSpec.js
This PR fixes issue when event is not defined
> fix(packages/sui-segment-wrapper): page data

- packages/sui-ssr/bin/sui-ssr-dev.js
This PR adds SSL support to webpack assets server
> feat(packages/sui-ssr): add webpack ssl support
