package.json, packages/sui-precommit/Readme.md, packages/sui-precommit/bin/sui-precommit-install.js, packages/sui-precommit/bin/sui-precommit-run.js, packages/sui-precommit/bin/sui-precommit.js, packages/sui-precommit/package.json
Proposal for sui-precommit new deal
Changes:
* **precommit rules are run a as a whole**
* Pros:
*  If you add new rules, we don't have to change installation or worry about chantes made by user
* Cons:
* User can't choose what to executed.
* **Now hook install is not automatic**
* Pros:
* User controls how he wants to integrate with git. He can even set the precommit before executing commitizen (no frustration)
* No magic. User won't find its package.json to have been changed...
* **Husky is used for git hooks integration**
* Pros: 
* It's npm scripts based, with adds value to the project.
* It's already used by sui-mono
Please review @miduga && @carlosvillu
=> Migrate precommit rules

packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/package.json
Release commit had empty version number
A wrong version was published as 1.12.0 and then unpublished. But, i could'nt publish 1.12.0 so I did it as 1.12.1...
As we use comver it shouldn't be a concern...
But, I can publish 1.13 if you think it's more apropriate.
Please review @naxhh @carlosvillu @miduga
=> Fix version tag

packages/sui-studio/bin/sui-studio-link.js
As @naxhh pointed out, `sui-studio link` can link a component outside of the studio. `sui-studio link-all` can't...
=> fix(sui-studio): don't deprecate link command, only mention link-all

packages/sui-studio/src/components/preview/index.js
Last version(s) changed the demo error reporting to a nice error message in the dom.
That's nice but you loose the stack and you generally don't know where the error comes from.
Example: "can't read type of undefined" instead of 'can't read type of undefined callback this._getStatus ....'
=> feat(sui-studio): log demo errors on console too

packages/sui-studio/src/components/demo/_style.scss, packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/styles/_settings.scss
ISSUES CLOSED: #25 
[The overlay z-index ](https://github.com/glenjamin/webpack-hot-middleware/blob/master/client-overlay.js#L13) was under the z-index we were setting in sui-studio, so I updated our z-index
#25
=> fix(sui-studio): update elements z-index

packages/babel-preset-sui/lib/index.js, packages/babel-preset-sui/package.json
Add support to
```
export * as ns from 'mod';
export v from 'mod';
```
=> feat(babel-preset-sui): add babel-plugin-transform-export-extensions

packages/sui-studio/src/components/demo/index.js
In order to pass initialProps to the component without a "tramsmit" like solution in the studio. We will go to use directly the domain in the playground
=> Pass domain to playground

packages/babel-preset-sui/CHANGELOG.md, packages/sui-bundler/CHANGELOG.md, packages/sui-component-dependencies/CHANGELOG.md, packages/sui-component-peer-dependencies/CHANGELOG.md, packages/sui-cz/CHANGELOG.md, packages/sui-decorators/CHANGELOG.md, packages/sui-helpers/CHANGELOG.md, packages/sui-helpers/cli.js, packages/sui-hoc/CHANGELOG.md, packages/sui-i18n/CHANGELOG.md, packages/sui-lint/CHANGELOG.md, packages/sui-mono/CHANGELOG.md, packages/sui-mono/bin/sui-mono-changelog.js, packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/bin/sui-mono.js, packages/sui-mono/package.json, packages/sui-mono/src/config.js, packages/sui-perf/CHANGELOG.md, packages/sui-polyfills/CHANGELOG.md, packages/sui-precommit/CHANGELOG.md, packages/sui-react-domain-connector/CHANGELOG.md, packages/sui-react-initial-props/CHANGELOG.md, packages/sui-ssr/CHANGELOG.md, packages/sui-studio-create/CHANGELOG.md, packages/sui-studio/CHANGELOG.md, packages/sui-studio/package.json, packages/sui-studio/src/components/documentation/Markdown.js, packages/sui-studio/src/components/documentation/try-require.js, packages/sui-studio/src/components/workbench/index.js, packages/sui-studio/src/routes.js
New command to generate CHANGELOG for monorepos (mono and multipackages)
#27 
@SUI-Components/developers please review !
=> Issue/27 [sui-studio] Add new Changelog tab for components

packages/sui-bundler/plugins/loader-options.js, packages/sui-bundler/shared/loader-options.js, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.prod.js
Webpack was loading sass-loader without its options (jsonImporter) for files outside of the context: sui-studio/src.
Created a plugin that ensure loader are instantiated with the same options in all
@naxhh @kikoruiz @miduga please review
=> fix(sui-bundler): fix json files not loading in sass imports

packages/sui-studio/package.json, packages/sui-studio/src/components/documentation/Markdown.js, packages/sui-studio/src/components/documentation/MarkdownFile.js, packages/sui-studio/src/components/documentation/ReactDocGen.js, packages/sui-studio/src/components/layout/index.js, packages/sui-studio/src/routes.js
Shape props are now detailed, subprop by subprop.
Now react-docs output is not rendered by sui-studio itsefl but by react-docs-markdown
Thanks to react-docs-markdown, we also have other improvements like for oneOf props. 
#29
@SUI-Components/developers please review
=> [sui-studio] Improve documentation with Shape props types

packages/sui-mono/src/check.js
Order was change: https://git-scm.com/docs/git-log#git-log---topo-order
#100
@naxhh and @miduga please review
=> fix(sui-mono): fix: release not detected with overlapped commits

packages/sui-helpers/cli.js, packages/sui-mono/README.md, packages/sui-mono/bin/sui-mono-run-parallel.js, packages/sui-mono/bin/sui-mono.js, packages/sui-mono/src/run.js
New command to improve productivity, mainly when resetting a projects with "run phoenix"
The command was tested  on sui-components
`sui-mono run npm i`: 171s
`sui-mono run-parallel npm i`:  52s
A new command was created as it was difficult to do something like `npm run --parallel npm i`. In this case, `process.argv` was changing the order of the arguments like this : npm, run, i, npm.
Let me know if you know a better way.
Please review @carlosvillu @miduga
=> [sui-mono] new command sui-mono run-parallel

packages/sui-perf/README.md, packages/sui-perf/src/measure-axios.js
This is one part of a 3 PRs that solves [this issue](https://github.com/SUI-Components/sui/issues/79) :
* Add support to measure axios' requests ([sui](https://github.com/SUI-Components/sui/pull/111))
* Add request id to the domain on SSR ([mt--web-app](https://github.schibsted.io/scmspain/frontend-mt--web-app/pull/126))
* Add (commented) support for axios measurement ([mt--lib-motor](https://github.schibsted.io/scmspain/frontend-mt--lib-motor/pull/150))
Testing this feature on mt--web-app with 3 simultaneous request and cache deactivated for news, we get the following:
```
timeline        start  time   %    label
███████████████ 0ms    4811ms 100% Request
█              399ms  272ms  6%   CreateContext
████          672ms  1363ms 28%  UseCases
███          1101ms 934ms  19%  🌎  GET …
```
=> feat(sui-perf): add support to measure axios' requests

packages/sui-studio/src/components/demo/index.js
If displayName is not set, the demo doesn't work in prod, like happened here: https://github.com/SUI-Components/sui-components/pull/152
@SUI-Components/developers please review
=> fix(sui-studio): enforce displayName for all components

packages/sui-studio/src/components/icons/index.js, packages/sui-studio/src/components/navigation/_style.scss, packages/sui-studio/src/components/navigation/index.js, packages/sui-studio/src/components/utils.js
Now you can mark a component like a compliant component using the stadio´s package.json
And if you want search by all compliant component in the studio, you can search by "*"
=> feat(sui-studio): mark and search by compliant

packages/sui-studio/package.json, packages/sui-studio/src/app.js
Studio was broken in IE, because of the absence of Array.prototype.includes
Polyfills were added.
@carlosvillu @miduga please review
=> fix(sui-studio): fix studio not working in IE browsers

packages/babel-preset-sui/lib/index.js, packages/babel-preset-sui/package.json
ISSUES CLOSED: #122
No improvement of final build... Even trying to build only for Chrome it doesn't seem to be worth having separated bundles by env.
=> feat(babel-preset-sui): replace es2015 preset by env

packages/sui-hoc/package.json, packages/sui-hoc/src/withContext.js
This fixes the problem with the warnings about the contextTypes when using the hoc to add context to a component. It also uses the external prop-types library to be prepared when using React 16 library version.
=> feat(sui-hoc): fix proptypes and prepare for react 16 using external proptypes library

packages/sui-react-initial-props/package.json, packages/sui-react-initial-props/src/loadPage.js
Move to prop-types library in order to be able to use React 16.
=> feat(sui-react-initial-props): use prop-types library

packages/sui-studio/bin/sui-studio-generate.js
Fix linting warning when creating a new component because not needed spaces before the line.
=> fix(sui-studio): fix linting error with new import when generating a component

packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.prod.js
It has a new parallelisation flag in order to do in parallel the uglification of the files.
A quick test of before and after building same application:
```
before
CDN=/ NODE_ENV=production npm run build  43.83s user 2.99s system 102% cpu 45.744 total
after
CDN=/ NODE_ENV=production npm run build 28.49s user 3.02s system 95% cpu 33.110 total
```
=> feat(sui-bundler): use new uglifyJSPlugin version

packages/sui-js/README.md, packages/sui-js/package.json, packages/sui-js/src/cookie/index.js
Parse, get and set cookies. Returns an object `cookie` with `parse`, `get` and `set` methods.
**Note:** `set` method does not work on server side.
```js
import cookie from '@s-ui/js/lib/cookie'
// Parse
const {parse} = cookie
domain.config('cookie', parse(cookies))
// Get
const {get: getCookie} = cookie
const smartBannerCookie = getCookie('smartbanner')
// Set
const {set: setCookie} = cookie
const setSmartBannerCookie = setCookie('smartbanner', 1)
```
=> feat(sui-js): adding js-cookie top sui-js

packages/sui-studio/src/components/demo/index.js, packages/sui-studio/src/components/demo/try-require.js
With this changes a studio package can export whatever it wants and it will be defined in the playground file
=> feat(sui-studio): exported data accesible from playground

packages/sui-js/README.md, packages/sui-js/package.json, packages/sui-js/src/string/index.js
Add a bunch of string utilities (`sui-js`). For now: `removeAccents` and `hasAccents` methods. Use npm `remove-accents` third-party package.
```js
import { removeAccents, hasAccents } from '@s-ui/js/lib/string'
console.log(removeAccents('París')) // "Paris"
console.log(hasAccents('Árbol')) // true
```
Please review @SUI-Components/developers !
=> feat(sui-js): add string utilities

packages/sui-domain/README.md, packages/sui-domain/src/EntryPointFactory.js
In order to provide a way to be able to use instatiable and mutable config we're ofering a param in the constructor. For fixing this https://github.com/SUI-Components/sui/issues/166
=> feat(sui-domain): make config instatiable and mutable

packages/sui-js/src/cookie/index.js
Adds support for `getJSON` method that will return the parsed representation of the string stored in the cookie according to `JSON.parse`.
```
jsCookie.getJSON('myKey'); // => { foo: 'bar' }
```
=> feat(sui-js): add getjson method

packages/sui-studio/bin/sui-studio-generate.js
refactor(sui-studio): changed the theme to be used on our index.scss from theme-basic to sui-theme
Now the index.scss files inside our created components will have the sui-theme import intead of have the theme-basic
Changed generator to have the import of sui-theme
https://jira.scmspain.com/browse/SM-2721
=> refactor(sui-studio): changed the theme to be used on our index.scss from theme-basic to sui-theme

packages/sui-studio/package.json, packages/sui-studio/src/components/preview/index.js, packages/sui-studio/src/index.html
While far from ideal, that gives a boost over the build time as babel-standalone is a huge dependency. So that ignores it and use directly from a cdn, giving some seconds of boost over initial build and incremental builds.
From node_modules (before):
From CDN (now):
=> perf(sui-studio): use babel-standalone from cdn instead as package dependency

packages/sui-studio/src/components/documentation/ReactDocGen.js
Load the chunk of React Doc Gen only when needed as it's pretty big in the bundle (33% of the bundle is that dependency) so we try to not rebuild everytime a change is detected and also to speed up the boot-up of the studio. So, the chunk will be loaded only when the user open the API tab.
Before:
After:
=> perf(sui-studio): load chunk of React Doc Gen only when needed

packages/sui-widget-embedder/bin/sui-widget-embedder-build.js, packages/sui-widget-embedder/downloader/index.js
Added serviceWorkerCdn option to allow have different urls for the widget statics and for the
service worker as we need an url over https and same placed as the site domain.
Now we are setting the static-cdn as our default cdn for ALL the resources. As sw.js need to run over an ssl url and over THE SAME domain as our target site we need to have a different URL to make it work.
We are guaranteeing retro-compatibility by setting as a fallback var the remoteCdn variable.
=> feat(sui-widget-embedder): added service worker cdn

README.md
In order to let people check quickly the code, point to the project instead  the file README directly, so people could check the code when entering a project along the README that is showed by default.
=> Point to project not README

packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.server.js
Maybe in the future we could want a command in the CLI. But for now is enough with a simple webpack config to be imported.
=> [sui-bundler] Add compile server config

packages/sui-studio/src/components/demo/try-require.js
This fixes the studio as the import with context is causing to import the wrong files as the variables are causing webpack to go through the whole tree (node_modules included) to search a `/src/index.js`. Rollback the way we import this until we figure out how to deal with it.
=> fix(sui-studio): rollback import context as it's causing to import wrong files

packages/sui-lint/src/helpers.js
Ignore comments on .gitignore file in order to avoid problems when adding them in the ignore-pattern.
Fixes: https://github.com/SUI-Components/sui/issues/264
=> fix(sui-lint): ignore comments on .gitignore files to avoid putting them in the .gitignore

packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.prod.js
- [fix] Use Object.assign instead spread operator in order to keep compatibility with node 6.
- [refactor] Remove not needed preload webpack plugin as we're doing the same with the scriptExtPlugin.
- [style] Sort imports of the file for clarity.
=> Remove not needed preload webpack plugin and fix node6 compatibility

packages/sui-bundler/webpack.config.prod.js
This PR fixes a regression from the latest major as the runtime chunk is not being generated and hashes are being generated again and again.
=> fix(sui-bundler): fix regression that runtime has not been created

packages/sui-helpers/cli.js, packages/sui-helpers/package.json, packages/sui-test/bin/sui-test-e2e.js
This PR was originally created to make sui-test commands compatible with windows.
`#!/usr/bin/env node` doesn't work on windows.
=> Windows cmd compatibility

packages/sui-helpers/cli.js, packages/sui-mono/README.md, packages/sui-mono/bin/sui-mono-phoenix.js, packages/sui-mono/bin/sui-mono.js, packages/sui-mono/package.json, packages/sui-mono/src/config.js, packages/sui-mono/src/run.js, packages/sui-test/bin/karma/patch.js
As part of windows compatibility, we need a command that avoid use "rm -Rf" and doesn't rely on having installed 'rimraf' globally. 
So, now we have an `sui-mono phoenix` command that is even more optimized that the classic `rm -Rf node_modules && npm i && sui-mono run-parallel rm -Rf node_modules && sui-mono run-parallel npm i` as it runs more in parralel.
=> Sui mono phoenix

packages/babel-preset-sui/lib/index.js
As some of you may know, the `last 4 versions` in browserlist is considered harmful. Why? Well, basically because we're aiming the last 4 versions OF ALL THE BROWSERS IN THE HISTORY OF THE BROWSERS. 🤯
It does mean we're supporting even IE7, old browsers as IE Mobile or not longer developed browsers like Opera Mini. In order to try a better aiming to our browsers, this PR try to use a best approach.
You could check the browsers supported in these new lines:
Before:
http://browserl.ist/?q=%3E+1%25%2C+last+4+versions%2C+Firefox+ESR%2C+Safari+%3E%3D+6%2C+iOS+%3E%3D+7%2C+not+ie+%3C+11
After:
http://browserl.ist/?q=%3E+0.25%25%2CFirefox+ESR%2CSafari+%3E%3D+8%2CiOS+%3E%3D+8%2Cie+%3E%3D+11%2Cnot+op_mini+all
=> feat(babel-preset-sui): use better targeting browsers in order to make more sense

packages/sui-bundler/shared/module-rules-babel.js, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.lib.js, packages/sui-bundler/webpack.config.prod.js, packages/sui-bundler/webpack.config.server.js
dev config had a bad format. So babel-preset-sui was not used and "env" was used instead.
This causes problems in studios that use spread operators in they demo files for instance.
=> fix(sui-bundler): sui-bundler dev not using babel-preset-sui

packages/sui-ssr/server/ssr/index.js
The error was caused when we tried to redirect from the root of our application to another route.
So if we have a kind of this router structure:
```javascript
<Router>
<Route path="/" getComponent={App}>
<IndexRedirect to="/bar">
<Route path="/bar">
<IndexRoute getComponent={LoadAlertasPage} />
</Route>
</Route>
</Router>
```
As we had the code it will throw an error here `if (error || !renderProps) {` because the redirect does not have any renderProp but have a redirectLocation object.
=> feat(sui-ssr): fix an error that was causing a false no renderProps error on our ssr server

packages/sui-lint/package.json
Some methods are marked as unused because it doesn't detect decorators. It seems that's a problem from a babel-eslint subdependency. In order to try to fix that, we're upgrading the babel-eslint version to the latest as in local it fixed the problem.
=> fix(sui-lint): upgrade babel-eslint version and fix problems with decorators

packages/sui-mono/bin/sui-mono-phoenix.js
While we're supposed to support npm 3, node 8 and node 10 comes with greater versions. So some developers are not getting the latest update in the @s-ui/studio because they've package-lock files after the installs. For the sake of not having to support them, I'm adding a feature to support latest npm version removing the package-lock.json file in the phoenix. If the file is not present, it gets ignored. So, completely compat with previous versions.
=> feat(sui-mono): add npm 6 support for phoenix

packages/sui-deploy/src/client/now.js, packages/sui-helpers/packages.js, packages/sui-test/bin/sui-test-e2e.js
Lazy loading of now in sui-deploy to avoid:
* to have to install it globally (in travis for instance)
* to have it install with sui-deploy before having to do a deployment, which is not a common task.
Plus, a helper has been created to avoid duplicated code and cypress in sui-test is now lazy loaded the same way.
=> Fix sui deploy

packages/sui-deploy/src/client/now.js
When a deploy is made with the same source code, deploy is omitted and then the alias should not be tried to set. This wsa throwing a 409 error.
=> fix(sui-deploy): don't try to alias when alias is present

packages/sui-js/src/number/index.js
This small utility has the purpose of being a centralized tool to format numbers in thousands with dots or commas.
I'm not using `toLocaleString` to avoid incompatibility issues with browsers like IE or Safari Mobile.
```javascript
const numToFormat = 100000
numberWithDots({ value: numToFormat })  // result : '100.000'
```
Please review @SUI-Components/developers
=> adds number formating functions

packages/sui-polyfills/package.json
Avoid installing two different versions of core-js so we use the latest version as it's being used by babel-polyfill.
=> feat(sui-polyfills): use latest core-js to use same version as latest babel-polyfill used

packages/sui-mockmock/README.md
Updated the `README.md` for noticing an error that someone else can find with the usage of the `mockmock package`
The `mockmock package` needs to have the same parameter order in the mocked and the original http request
=> Err404 thrown when parameter dont have same order readme update

packages/sui-studio/src/components/tryRequire.js
It seems that there is one path separator ‘/‘ that is unescaped inside the webpackExclude regex, which is making that the studio fails to start.
The error displayed when trying to run `sui-studio start` command is:
```
./components/tryRequire.js 154:31-91
Compilation error while processing magic comment(-s): /* webpackExclude: /\/node_modules\/(.*)\/demo/index.js$/ */: Invalid regular expression flags
```
=> fix(sui-studio): unescape path separator in regex to avoid error importing demo page.

packages/sui-bundler/loaders/linkLoaderConfigBuilder.js
This PR adds the ability to easily link a package using relative path to your linked component
The current Sui-Bundler allows to link packages using absolute paths like this:
`./node_modules/@s-ui/bundler/bin/sui-bundler-dev.js --link-package User/david.garcia/www/frontend-fc--lib-real-estate`
Linking the Domain to Web Server:
`./node_modules/@s-ui/bundler/bin/sui-bundler-dev.js --link-package ../frontend-fc--lib-real-estate`
_Notice the relative path to the linked component_
To make it even easier, you can create an alias function in your .bashrc/.zshrc config file so the execution to link the real-estate domain to the Web Server will be:
`sblink ../frontend-fc--lib-real-estate`
Linking the Domain to Web Server:
`./node_modules/@s-ui/bundler/bin/sui-bundler-dev.js --link-package …
=> feat(sui-bundler): adds relative to absolute path conversion

packages/sui-test/bin/karma/config.js
We have recently added support for dynamic imports in client and server side but we found that is necessary that Istanbul reads the code after been "transpiled", for this reason, the order is important and has changed in this PR. Now we have first the transform plugins and later Istanbul package for test coverage.
=> feat(sui-test): added support dynamic import when we run ci test

packages/sui-studio/bin/sui-studio-generate.js
Avoid generating a new component with sass and js lint errors. For that, we're adding an empty line to the end of the generated file.
=> fix(sui-studio): generate components without linter errors nor warnings

packages/sui-mono/README.md, packages/sui-mono/bin/sui-mono-phoenix.js
This option is needed to avoid overload of log buffer in travis environments
=> feat(sui-mono): phoenix with --no-progress output

.travis.yml, packages/sui-react-initial-props/src/createClientContextFactoryParams.js, packages/sui-react-initial-props/src/createServerContextFactoryParams.js, packages/sui-ssr/README.md, packages/sui-ssr/hooks-types.js, packages/sui-ssr/package.json, packages/sui-ssr/server/hooksFactory/index.js, packages/sui-ssr/server/index.js, packages/sui-ssr/server/ssr/index.js
The main purpose is about being able to set environmental variables on runtime so that:
- you don't have to build the app one time per environment.
- It means that this ease, simplifies and speeds up your CI/CD process.
- Also the code and config are separated so that your app becomes environment agnostic.
- And as your app is built just once you can trust that what you test is exactly what you deploy.
- Note that env file was named with "public" word so that developers have a clue to not add secrets in it. If a secret was needed, the same approach could be applied in an implementation where secrets are read from a `private-env.yml` file with the exception that this data should not be passed to the SPA in any case.
- req.hostname is added to appConfig by default. In the NC project the …
=> Load env vars from file on runtime, buid app config object and pass it to the SPA

packages/sui-js/README.md, packages/sui-js/package.json, packages/sui-js/src/string/index.js
import `query-string` library parse method to be used in motor domain as `parseQueryString`.
https://github.schibsted.io/scmspain/frontend-mt--lib-motor/pull/346/files/39c994ed364ef3dda144ad309a377e3d1a53bf40#diff-5e0c506e61dc67658876dd8cd35e014d
=> feat(string): adding query-string utility

packages/sui-bundler/webpack.config.lib.js
Since in Motor sites we started to use the Domain as UMD module, we could realise multiple webpack runtimes in the same webpage may collide. So that a `jsonpFunction` name is required to avoid it.
More info: https://webpack.js.org/configuration/output/#output-jsonpfunction
=> avoid multiple webpack runtimes collision

packages/sui-js/src/string/index.js
Cover the need of stringify query string objects/params.
```js
import { stringify } from 'query-string';
const filters = {
brand: "CITROEN",
price_min: 3000,
provinces: ["alicante", "barcelona"]
};
console.log(stringify(filters)); // brand=CITROEN&price_min=3000&provinces=alicante&provinces=barcelona
```
=> feat(sui-js): add an string method to convert objects to query strings

packages/babel-preset-sui/README.md, packages/babel-preset-sui/lib/clean-list.js, packages/babel-preset-sui/lib/index.js, packages/babel-preset-sui/lib/is-installed.js, packages/babel-preset-sui/package.json
Remove flow temp support for the POC in our babel-preset-sui.
=> feat(babel-preset-sui): remove POC flow usage on babel-preset-sui not supported on our platforms

packages/sui-widget-embedder/package.json
We need to update the bundler version in order to avoid multiple webpack runtimes collision, if applies.
https://github.com/SUI-Components/sui/pull/400
=> fix(sui-widget-embedder): update bundler version

packages/sui-widget-embedder/compiler/production.js
build failing because of 
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.entry should be one of these:
object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
-> The entry point(s) of the compilation.
Details:
* configuration.entry['vendor'] should be a string.
-> The string is resolved to a module which is loaded upon startup.
* configuration.entry['vendor'] should be an array:
[non-empty string]
* configuration.entry should be a string.
-> An entry point without name. The string is resolved to a module which is loaded upon startup.
* configuration.entry should be an array:
[non-empty string]
* …
```
=> fix(sui-widget-embedder): remove undefined vendor from webpack's config

packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.server.js
Fix problems when importing scss files from the server in the sui-bundler. So we should just ignore them.
=> fix(sui-bundler): ignore scss import files in server

packages/sui-widget-embedder/compiler/production.js
Once I've been working with widgets integrating the IAB modal I've seen that even if I was forcing z-index to high values my final result bundled was always less than the number that I was setting (for example if I setted z-index: 2500 my bundled value was 2)
This is caused by a default behavior of cssnano (more info here):
https://github.com/ben-eb/gulp-cssnano/issues/8
In fact we are not using css nano directly but we are using optimize-css-assets-webpack-plugin which is using cssnano as a dependency.
In order to fix that ONLY ON THE WIDGETS I've decided to modify the widget package as if I modify the webpack.conf of the bundler we could step into unexpected behaviors on all the sites that are using s-ui/bundler.
=> fix(sui-widget-embedder): disable zindex optimization on cssnano

packages/sui-bundler/package.json
npm-run-all 3.1.2 uses pid-tree 1.0.0
pid-tree was compromised and removed in a newer version
Since we don't use the dep. remove it
=> Remove npm-run-all since it's not used

packages/sui-bundler/loaders/linkLoaderConfigBuilder.js
Fix Windows RegExp syntax in LoaderConfigBuilder
=> fix(sui-bundler): fix Windows RegExp syntax in LoaderConfigBuilder

packages/sui-test/README.md, packages/sui-test/bin/sui-test-e2e.js
--userAgent option has been added
It is required in order to change the entire user agent.  Alto, --userAgentAppend behavior stays the same.
Related Issue: Fix [#446](https://github.com/SUI-Components/sui/issues/446)
**To test:**
1.  ```cd frontend-mt--e2e-tests```
2. ```node ../sui/packages/sui-test/bin/sui-test.js e2e --baseUrl="http://pre.coches.net"  --scope="coches" --gui --userAgent="Screaming Frog SEO Spider/8.3"```
3. Then, run a test and write ```navigator.userAgent``` in console
=> feat(sui-test): add overwrite user agent option

packages/sui-hoc/src/index.js, packages/sui-hoc/src/withStateValueTags.js
`withStateValueTags` hoc needed for several components like `MoleculeInputTags` and `MoleculeAutosuggest`
=> feat(sui-hoc): withStateValueTags

packages/sui-react-initial-props/src/loadPage.js
Keep displayName for server wrapped components in react-initial-props.
=> feat(sui-react-initial-props): add displayName for server component

packages/sui-test/README.md, packages/sui-test/bin/sui-test-e2e.js, packages/sui-test/package.json
Motor frontends need to have support files in order to configurate a custom command with the user login.
sui-test e2e does not accept supportFile directory
ISSUES CLOSED: #459
=> feat(sui-test): support file option added to e2e tests

packages/sui-bundler/README.md, packages/sui-bundler/package.json, packages/sui-bundler/shared/module-rules-babel.js, packages/sui-bundler/shared/uglify.js, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.prod.js
This PR adds sourcemap generation support for sui-bundler. It expects a new section `sourcemaps` in the sui-bundler project package.json configuration to get from there the desired devtool webpack value. By default, the behaviour would be same as it is now and no sourcemaps are generated if this section is not present.
A new source-map-loader has been added for all js/jsx files in the babel rules config and the flag for sourcemaps in the uglifyJS plugin config has been changed.
```json
{
"sui-bundler": {
"sourcemaps": {
"dev": "cheap-module-eval-source-map",
"prod": "hidden-source-map"
}
}
}
```
=> feat(sui-bundler): Add sourcemaps support to improve sentry integration

packages/babel-preset-sui/package.json
Add new @babel/runtime to be used in case you're trying to use old babel-preset-sui mixed with the new one.
=> fix(babel-preset-sui): add babel runtime 7 for compatibility

packages/sui-widget-embedder/README.md, packages/sui-widget-embedder/bin/sui-widget-embedder-build.js, packages/sui-widget-embedder/downloader/index.js
Regarding the best practice of loading one widget bundle by page, in the most cases we'll need to load that bundle on a specific number of pages, via the existing param `pathnameRegExp`, but sometimes we'll want to load it everywhere but not on those pages, so that, the param `blacklistedRegExps` will help us to skip them.
```js
// pages/all-not-static.js
{
"version": "1.0.0",
"private": true,
"pathnameRegExp": ".*",
"blacklistedRegExps": [
"contact.html",
"about.html"
]
}
```
=> feat(sui-widget-embedder): allow to add a blacklist of reg exps

packages/sui-svg/bin/sui-svg-build.js
Exporting svgs from illustrator adds a title which shouldn't be needed, this PR removes the title tag when converting into a react component
=> feat(sui-svg): remove title tag on build

packages/sui-studio/bin/sui-studio-dev.js
Because studio is messing with alias config and it shouldn't. Bad boy!
=> fix(sui-studio): fix problems with react-hot-loader when linking studio

packages/babel-preset-sui/lib/index.js
Don't assume that the opts are being used when using the babel-preset-sui. Get a default value with an empty object to avoid problems like this one:
```
TypeError: Cannot destructure property `isDevelopment` of 'undefined' or 'null'. (While processing preset: "/Users/carlos.villuendas/Developer/frontend-ma--lib-milanuncios/node_modules/babel-preset-sui/lib/index.js")
```
=> fix(babel-preset-sui): add default value for opts

packages/sui-test/src/descriptor-environment-patcher.js
```
> @schibstedspain/milanuncios@2.7.0 test:server /Users/carlos.villuendas/Developer/frontend-ma--lib-milanuncios
> NODE_ENV=development sui-test server
mocha /Users/carlos.villuendas/Developer/frontend-ma--lib-milanuncios/test --require /Users/carlos.villuendas/Developer/frontend-ma--lib-milanuncios/node_modules/@s-ui/test/bin/mocha/register.js --recursive
ENV: development
Internal: false
/Users/carlos.villuendas/Developer/frontend-ma--lib-milanuncios/node_modules/@s-ui/test/lib/descriptor-environment-patcher.js:11
export var descriptorsByEnvironmentPatcher = function descriptorsByEnvironmentPatcher() {
^^^^^^
SyntaxError: Unexpected token export
at new Script (vm.js:74:7)
```
=> [sui-test] export using commonjs

packages/sui-polyfills/package.json
Update core-js of polyfills to avoid packing twice same library as noted here:
```
> CDN=/ NODE_ENV=production sui-bundler analyzer
🔎  Bundler Analyzer
Building and analyzing...
Bundle analyzed successfully
core-js
Multiple versions of core-js found:
2.5.7 /Users/miguelangel.duran/Dev/frontend-fc--web-server/~/@s-ui/polyfills/~/core-js from /Users/miguelangel.duran/Dev/frontend-fc--web-server/~/@s-ui/polyfills/~/core-js/modules/es7.array.includes.js
2.6.3 /Users/miguelangel.duran/Dev/frontend-fc--web-server/~/core-js from /Users/miguelangel.duran/Dev/frontend-fc--web-server/~/core-js/library/modules/_array-includes.js
regenerator-runtime
Multiple versions of regenerator-runtime found:
0.11.1 /Users/miguelangel.duran/Dev/frontend-fc--web-server/~/babel-runtime/~/regenerator-runtime from …
```
=> perf(sui-polyfills): use same core-js as @babel/runtime to avoid packing twice same library with different versions

packages/sui-bundler/package.json
`>= 5.0.2` is installing `v7.x.x` which breaks our studios when running them on IE11, `v6` doesn't work either
=> fix(sui-bundler): set fixed react-dev-utils version

packages/sui-i18n/README.md, packages/sui-i18n/src/i18n.js, packages/sui-i18n/test/i18nSpec.js
Proposal to address #491. The current solution considers holding future "minor types" if necessary (any suggestions for better naming?). Is this a suitable approach?
Note: If the proposal were to be accepted, it would be necessary to add proper documentation [into the README](https://github.com/SUI-Components/sui/blob/master/packages/sui-i18n/README.md).
```js
i18n.f('phone', '123123123') // outputs '123 123 123'
```
=> feat(sui-i18n): add format method for minor types, add tests

packages/sui-hoc/package.json
Bump Intersection Observer to latest version.
=> fix(sui-hoc): use same version of the package as other libraries to avoid having twice the same

packages/sui-js/README.md, packages/sui-js/src/classes/index.js, packages/sui-js/test/classesSpec.js
Added a new util function to be able to easily suit a class name following the convention for baseComponent{-children}-element--modifier
`
const baseComponent = suitClass('baseComponent')
<div className={baseComponent({element: 'element'})}/>
`
=> feat(sui-js): added utils to suit class names

packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.dev.js
Use `@hot-loader/react-dom` to patch react-dom in dev mode.
=> feat(sui-bundler): patch in development mode react-dom for get working with hooks and other features

packages/sui-bundler/webpack.config.dev.js
Alias `react` package so when linking components we make sure we're only using only one React library and we're not loading different React instances.
=> fix(sui-bundler): add alias to get linked packages with react hooks working

packages/sui-lint/sass-lint.yml
Exclude media queries from `mixins-before-declarations` sass lint rule, in order to be able to declare css default properties before media queries and don't get an error.
=> feat(sui-lint): exclude media queries from mixins-before-declarations sass lint rule

packages/sui-svg/templates/pure-component.js
Move sui-svg to hooks in order to improve bundle and parse time.
=> perf(sui-svg): move to React Hooks instead using class

packages/sui-widget-embedder/package.json, packages/sui-widget-embedder/src-react/Widget.js
Since we're trying to migrate all our vertical components to the new React Context API, we need to have the Context Provider wrapping our widgets apps.
=> feat(sui-widget-embedder): add support for the new react context

packages/sui-test/bin/karma/config.js, packages/sui-test/bin/mocha/register.js, packages/sui-test/package.json
Give support for some proposal export plugins as `plugin-proposal-export-default-from` and `plugin-proposal-export-namespace-from` in unit tests execution (both client and server).
Some of code examples that will be supported with this change will be:
```js
// @babel/plugin-proposal-export-default-from
export test from 'sui-test';
// @babel/plugin-proposal-export-namespace-from
export * as ads from 'ads';
```
=> feat(sui-test): add support for some proposal export babel plugins

packages/sui-domain/src/index.js
Stop using unsupported export proposal and use the native way of handling this (supported by webpack and native modules).
=> fix(sui-domain): avoid using not supported export from webpack

packages/sui-mono/src/config.js
Avoid creating the Root scope path as it doesn't exist when we try performing a phoenix or running an npm install in parallel.
```
→ cd demo && ../node_modules/.bin/sui-mono run-parallel npm install --no-progress
{ 'sui-mono': { packagesFolder: '.', deepLevel: 3, addRootScope: false } }
true
❯❯ Running 6 commands in parallel.
⠙ npm install --no-progress @profile/themes
⠙ npm install --no-progress @banner/themes
⠙ npm install --no-progress @appBoundary/themes
⠙ npm install --no-progress @gallery/themes
⠙ npm install --no-progress @icons/themes
✖ npm install --no-progress @demo/Root
→ spawn npm ENOENT
✖ An error occurred during command execution. Info:
Error: spawn npm ENOENT
```
=> fix(sui-mono): Avoid creating root path Scope because it doesnt' exist

packages/sui-precommit/bin/sui-precommit-run.js
it commits even if test broken
serialSpawn throws an error, does not return a code https://github.com/SUI-Components/sui/blob/master/packages/sui-helpers/cli.js#L98
=> fix(sui-precommit): exit on error

packages/sui-bundler/webpack.config.dev.js
Since in Motor we're working with new React Context package, we've notice linking components that import `@s-ui/react-context` in our app breaks the loaded page.
=> fix(sui-bundler): fix linking packages not working with the react context package

packages/sui-widget-embedder/downloader/index.js
Storing in a variable the whole pathname.match is causing problems when using widgets.
For avoiding that, we should store the `pathname` and use the method match instead, in order to avoid losing the reference of the string we want to match.
=> fix(sui-widget-embedder): fix wrong context on using pathname.match

README.md, packages/sui-changelog/README.md, packages/sui-changelog/bin/index.js, packages/sui-changelog/package.json, packages/sui-changelog/src/config.js, packages/sui-changelog/src/helpers.js
> CLI to retrieve a changelog from a set of dependencies.
The main aim of this package is to build a changelog file with all the last changes you get in your last installation within your project. Dependencies are retrieved by its scope in the `node_modules` folder, so you can customize the scopes to get the changelog data from.
Moreover, `sui-changelog` package runs a `npm shrinkwrap` in order to get the differences in the dependencies, and you can optionally run a `phoenix` command if you want to have a clean install before building your changelog.
Install `node@11` with `npm@6` in your env and run the following CLI command:
```sh
$ npx @s-ui/changelog
```
Or, if you want to save it in your project development dependencies:
```sh
$ npm install @s-ui/changelog --save-dev
$ sui-changelog …
```
=> Add "sui-changelog" package

packages/sui-js/README.md
Added a new package `htmr` to have the option to convert html strings to React element.
`No more dangerouslySetInnerHTML`
👉🏼 [htmr](https://github.com/pveyes/htmr)
```
const HtmlContent = (html) => {
return (
htmlStringToReactElement(html)
)
}
```
=> feat(sui-js): added htmr package

packages/sui-bundler/webpack.config.dev.js
Add support to `react-router-dom` package when linking packages as it's using React.Context and we cannot load two different libraries for it.
=> feat(sui-bundler): support react-router-dom link-package

packages/sui-analytics/README.md, packages/sui-analytics/package.json, packages/sui-analytics/src/index.js, packages/sui-analytics/test/suiAnalyticsSpec.js
In order to be able to track the user and anonymous id in adobe, we need segment to sent in its message's context the anonymousId as a trait, a message example would be:
```json
{
"anonymousId": "e1f5e097-dd7b-456b-bfc9-0d0273017cc1",
"context": {
"traits": {
"anonymousId": "e1f5e097-dd7b-456b-bfc9-0d0273017cc1",
"userId": "d2g5s9vu-ds7b-456b-bfc9-7d8592734kd3"
},
},
"userId": "d2g5s9vu-ds7b-456b-bfc9-7d8592734kd3"
}
```
track event in which we can see that it normalizes the options https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L337
normalize function in which we can see that the unknown keys are added into the context https://github.com/segmentio/analytics.js-core/blob/master/lib/normalize.js#L77
=> feat(sui-analytics): add userId and anonymousId trait into message context

packages/sui-mono/bin/sui-mono-changelog.js
Sometimes race conditions can occur between reading git log and writing changes to CHANGELOG.MD.
Currently changelog.md generation process ends after the `end` event is emitted from `conventionalChangelog` reading stream. The proposal is to resolve the promise after the `end` event emitted from the writing stream.
fix #581 
Currently the content of [CHANGELOG.md](https://github.com/SUI-Components/sui/blob/master/packages/babel-preset-sui/CHANGELOG.md) was wiped out after a release [release commit](https://github.com/SUI-Components/sui/commit/58791e7195388f43d7a3b9bd64e19bdb3da43b91)
=> feat(sui-mono): resolve promise on writeStream end event

packages/sui-js/README.md, packages/sui-js/package.json, packages/sui-js/src/string/index.js, packages/sui-js/test/stringSpec.js
Method for transforming a parameter object into a query-string. If one of the parameters contains an array, it will construct it with a comma separation.
> Needs to upgrade `qs` package from `6.6.0` to `6.7.0`
```javascript
const params = {userId: 1, adId: 2, products: [3, 4, 5]}
console.log(arrayToCommaQueryString(params)) // 'a=1&b=2&c=3,4,5'
```
=> feat(sui-js): arrayToCommaQueryString method

packages/sui-bundler/README.md, packages/sui-bundler/webpack.config.dev.js
The **Experiment Context** feature [which was introduced in this PR](https://github.com/SUI-Components/schibsted-spain-components/pull/94) and resides in the `@s-ui/abtesting-optimizely-x` package, needs an alias on sui-bundler in order to work with linked packages, so the `createContext` method is ran from a single place: the `node_modules` directory from the project in which sui-bundler is running.
This is the very same problem that is being solved for `@s-ui/react-context` package by adding an alias as well:
https://github.com/SUI-Components/sui/blob/3fd5a279e43e9aed038b48da41b3a4d5774bfe72/packages/sui-bundler/webpack.config.dev.js#L28-L30
=> feat(sui-bundler): add alias to keep same experiment context on linked packages

packages/sui-bundler/shared/parse-alias.js, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.lib.js, packages/sui-bundler/webpack.config.prod.js, packages/sui-bundler/webpack.config.server.js
Alias parsing logic must be present on all the webpack configs.
Fixes #625
=> fix(sui-bundler): move alias parse logic to shared for all environments

packages/sui-svg/package.json
`lodash.camelcase` dependency was missing from the dependencies list of this package.
This `require()` https://github.com/SUI-Components/sui/blob/master/packages/sui-svg/bin/sui-svg-build.js#L9 was modified in #553 but probably another package was importing lodash, since it has been working fine until recently. 
Unfortunately it produces an error when trying to build the icon library for milanuncios.
=> fix(sui-svg): add missing lodash.camelcase dependency

packages/sui-lint/stylelint.config.js
So, now that we're using prettier for stylelint it seems that we can't keep using no-leading-zero rule as prettier enforces it and is causing a mismatch between both. In order to fix it, we will need to embrace the leading-zero rule to be used always.
Related: https://github.com/prettier/prettier/issues/2705
=> feat(sui-lint): equal prettier and  stylelint rule

packages/sui-polyfills/src/element-closest.js, packages/sui-polyfills/src/index.js
Add `Element.closest()` polyfill
Internet Explorer 11 has no support for Element.closest(), so we are adding a polyfill for this. The code is the proposed in MDN (https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill) for browsers that support `element.matches()` (IE9+).
I couldn't find any polyfill for it available in core-js.
=> feat(sui-polyfills): add element.closest() polyfill

packages/sui-decorators/README.md, packages/sui-decorators/src/decorators/cache/index.js
The decorator applies the cache always. In some cases we may need to disable this in certain environment such as testing. For this purpose, add a `__SUI_CACHE_DISABLED__` variable in global scope.
```
// For client side
window.__SUI_CACHE_DISABLED__ = true
// Server side
global.__SUI_CACHE_DISABLED__ = true
```
=> feat(sui-decorators): allow to disable the cache.

packages/sui-bundler/package.json
Rollback version of raw-loader to avoid problems with dev and start mode because breaking changes on raw-loader exporting files.
=> fix(sui-bundler): rollback to raw-loader@1 to fix problems with export files

packages/sui-studio-utils/src/domain-builder/index.js
Currently, Domain useCases using the [@inlineError](https://github.com/SUI-Components/sui/blob/master/packages/sui-decorators/src/decorators/error.js#L6) decorator are not supported by `DomainBuilder` to override responses when Demoing components.
This PR adds compatibility so we'll be able to use both: Domain useCases using the pattern `[error, response]` and `response` only.
Thanks to @midudev and @zecafa for your help 😍 
Let's say I want to build a Demo for some component using the current logged `userId`. We can simulate a `get_current_user_use_case` response via DomainBuilder:
```javascript
domain: DomainBuilder.extend({domain: new Milanuncios()})
.for({useCase: 'get_current_user_use_case'})
.respondWith({
success: {id: 179587252}
})
```
So far, DomainBuilder was not taking into …
=> feat(sui-studio-utils): adds compatibility with inlineError

packages/sui-js/README.md, packages/sui-js/src/string/index.js, packages/sui-js/src/string/random-string.js, packages/sui-js/test/stringSpec.js
Add getRandomString in sui-js in order to have the possibility to create random strings with a defined length
https://github.com/SUI-Components/sui/pull/703/files#diff-e231c378ec264fa0c1d2439f65a9d2afR109
```
import {getRandomString} from '@s-ui/js/lib/string'
const randomStringLength = 6
const randomString = getRandomString(randomStringLength)
console.log(randomString.length) // log = 6 || 15 by default
console.log(randomString) // qwerty
```
=> feat(sui-js): add getRandomString function

packages/sui-bundler/package.json
Remove terser pinned version needed for the bug caused on 4.4.1. 4.4.2 is already published and working as expected.
=> feat(sui-bundler): remove terser pinned  version

packages/sui-ssr/README.md, packages/sui-ssr/server/criticalCss/index.js
This feature allows to set an object containing all the custom headers you want to send to the Critical CSS service in order to make it work without any limitation or regarding any requirement your target URL needs.
=> feat(sui-ssr): allow sending custom headers to critical css service

packages/sui-ssr/server/criticalCss/index.js
`headers` object wasn't sent properly inside the options object of the `https` request method 😭
=> fix(sui-ssr): send custom headers properly inside an options object

packages/sui-react-initial-props/package.json, packages/sui-react-initial-props/src/createClientContextFactoryParams.js, packages/sui-react-initial-props/src/createServerContextFactoryParams.js, packages/sui-react-initial-props/src/index.js, packages/sui-react-initial-props/src/initialPropsContext.js, packages/sui-react-initial-props/src/loadPage.js, packages/sui-react-initial-props/src/ssrComponentWithInitialProps.js, packages/sui-react-initial-props/src/withInitialProps.js
**react-initial-props** package:
- **Remove usage of old context API** and use the new one instead.
- Use `undefined` instead `delete` in order to keep JS compiler optimizations.
- Avoid repeating code.
- Move ClientPage from class to function using new hooks.
=> Use new context for react-initial-props package

packages/sui-mockmock/src/http/clientMocker.js, packages/sui-mockmock/src/http/mockerInterface.js, packages/sui-mockmock/src/http/serverMocker.js, packages/sui-mockmock/test/mockerSpec.js
Just add `PATCH` as a new method to mock in our tests.
```
const mocker = new Mocker()
mocker
.httpMock(_API_BASE_URL)
.patch(
`${_API_UPDATE_VEHICLE_URL}?vehicleId=${VEHICLE_ID}`
)
.reply(updateUserVehicleUseCaseApiResponse, 200)
```
=> feat(sui-mockmock): add patch method to sui-mockmock

packages/sui-test/bin/sui-test-e2e.js
- add --record flag to sui-test e2e command
- add --key flag to sui-test e2e command
This flag will allow to record e2e tests while running into CI and be able to debug/inspect the errors more easily if some tests fail.
[Official Documentation](https://docs.cypress.io/guides/dashboard/projects.html#Set-up-a-project-to-record)
=> feat(sui-test): add record flag

packages/sui-polyfills/src/index.js
Add Array.flat polyfill since it is not natively supported in IE11.
=> feat(sui-polyfills): add Array.flat polyfill

packages/sui-lint/Readme.md
Following [prettier guidelines](https://github.com/prettier/prettier-vscode#linter-integration) about **VScode** linting integrations is recommended to use the proposed config in this PR:
```json
{
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true
}
}
```
=> docs(sui-lint): update Prettier integration in VScode

packages/sui-widget-embedder/src-react/Widget.js
When there is no way to target a deterministic URL to load a specific Widget via RegEx, this `isVisible` prop can handle logic to show/hide Widget based in a Boolean condition.
This feature has a default prop to be backward compatible with the previous version.
https://jira.scmspain.com/browse/MMAA-12153
=> feat(sui-widget-embedder): show/hide prop where URLs are not deterministic

packages/sui-studio/README.md, packages/sui-studio/patcher-mocha/index.js, packages/sui-studio/src/components/test-page/index.js, packages/sui-studio/src/components/test/index.js
test/atom/button/index.js
```js
import '@s-ui/studio/patcher-mocha'
chai.use(chaiDOM)
describe.context.default('atom/button', AtomButton => {
it('Render', () => {
const {getByText} = render(<AtomButton>HOLA</AtomButton>)
expect(getByText('HOLA')).to.have.text('HOLA 12')
})
})
describe.context.other('atom/button', AtomButton => {
it('Render', () => {
const {getByText} = render(<AtomButton>HOLA</AtomButton>)
expect(getByText('HOLA')).to.have.text('HOLA 34')
})
})
```
demo/atom/button/context.js
```js
export default () => {
return Promise.resolve({
default: {
user: {id: 12},
language: 'es'
},
other: {
user: {id: 34},
language: 'ca'
}
})
}
```
components/atom/button/index.js
```js
export default function AtomButton({children}) {
const {user} = useContext(SUIContext)
console.log({user}) // …
```
=> [sui-studio] Add patcher to mocha to allow switch contexts

packages/sui-bundler/webpack.config.prod.js
PR to avoid putting in chunks repeated libraries that are not in initial chunks. In this example, you could see @s-ui/js library repeated over different chunks.
Before (chunks over ~7KB):
After (chunks over ~4KB) as @s-ui/js is already in the app or other chunk:
=> perf(sui-bundler): avoid repetated libraries

package.json, packages/sui-js/src/string/parse-query-string.js, packages/sui-js/test/stringSpec.js
Fix adding delimiter option for `parseQueryString`
=> feat(sui-js): add delimiter option

packages/sui-js/src/string/to-query-string.js, packages/sui-js/test/stringSpec.js
Fix adding delimiter option for toQueryString
=> fix(sui-js): enable delimiter to toQueryString method

packages/sui-i18n/src/i18n.js
Add get languages method to get the translation object.
The current option would be `i18n._languages[i18n.culture].MONTH.LONG`.
The new option `i18n.languages[i18n.culture].MONTH.LONG` without accessing private property 🙄.
=> feat(sui-i18n): add get languages method

packages/sui-domain/src/EntryPointFactory.js
Fixes the subscribe behaviour on useCases using the `@streamify` decorator.
So far, only the first argument was taken by the subscribe method (which happened to be `onNext` from `@streamify`). The method is now also taking `onError` for a correct error handling. 
N/A
N/A
=> fix(sui-domain): make subscribe method take onNext, onError arguments

packages/sui-js/src/string/to-query-string.js
…and subsequent call to `stringify`
One of our use cases uses toQueryString to pass on a URL which doesn't need to be encoded. Hence, we need to be able to pass the option `encode` as `false` to `qs`'s `stringify`. 
N/A
N/A
=> feat(sui-js): add encode to toQueryString options

packages/sui-component-dependencies/package.json
Install @s-ui/theme in order to be able to import it over the old @schibstedspain/sui-theme. We're keeping the old one in order to keep compatibility.
=> feat(sui-component-dependencies): add @s-ui/theme pkg to be imported

packages/sui-js/src/string/highlighter.js, packages/sui-js/src/string/index.js, packages/sui-js/test/stringSpec.js
Add highlightText method to sui-js
highlightText method allows to add a `startTag` and `endTag` around all ocurrences of certain `query` of a `value` in a case-insensitive and accent-insensitive way.
https://jira.scmspain.com/browse/SUIC-447
Tests and Documentation updated (see examples)
If value is `Cádiz`, query is `ca`, startTag is `<strong>`, endTag is `</strong>` it returns: `<strong>Cá</strong>diz`
=> feat(sui-js): add highlightText method to sui-js

packages/sui-mockmock/src/http/serverMocker.js
In all verticals we are restoring our mocks after each test:
But sui-mockmock does not use nock implementation for clear all the interceptors created by other test mocks. This PR add this implementation for clean all the interceptors when we use `mocker.restore()`
See docs 👀 https://github.com/nock/nock#restoring
In motor we had a test that mocks `/authentication` with `reply({})`.
After this one, we have another test with same mock but with `reply({...someData})`
Given we never restore the interceptors, second test fails because mock replies with `{}` because of nock uses `interceptors.find` it appears earlier in interceptors array.
Just 🤯
=> fix(sui-mockmock): fix restore interceptors and use new nock version

packages/sui-ssr/server/ssr/index.js
Add check to skip SSR if statusCode is set to 404
This code will cause skipping the SSR phase if the status code of the response is set previously to `404`. This solves the issue where the hook `TYPES.NOT_FOUND` is never reached because the ssr always matches routes like `/*`.
1. First set the status code in `hooks[TYPES.PRE_SSR_HANDLER]` hook, for example. 
```js
[TYPES.PRE_SSR_HANDLER]: (req, res, next) => {
res.status(404)
return next()
}
```
2. When the SSR is reached, this code will make it skip ssr and jump to `hooks[TYPES.NOT_FOUND]` hook
3. The `NOT_FOUND` hook will render the static 404 page.
=> [sui-ssr] Add check to skip SSR if statusCode is set to 404

packages/sui-ssr/server/ssr/index.js
Use skipSSR flag instead of checking status code
See #786 
After consideration, we have seen it is more convenient having a flag that any hook can set to skip the SSR phase. 
```js
[TYPES.PRE_SSR_HANDLER]: (req, res, next) => {
req.skipSSR = true
return next()
}
```
=> [sui-ssr] Use skipSSR flag instead of checking status code

packages/sui-studio/src/components/style/index.js
fix the children's prop because it now arrives as an array instead of a string
=> fix(sui-studio): fix Style children array proptype

packages/sui-ssr/server/criticalCss/index.js
Add criticalcss invalidation param with the format `x-criticalcss-cache-invalidate` 
Call http://www.milanuncios.com/fax?x-criticalcss-cache-invalidate to invalidate all generated critical CSS just in case they were generated badly or with errors.
=> feat(sui-ssr): add criticalcss invalidation param

packages/sui-studio/src/index.html, packages/sui-studio/workbench/src/index.html
add a mocha variable `__ROUTER_PUSH_TRIGGERED__ `, so component tests don't fail due to [`global leak detected error`](https://github.com/mochajs/mocha/issues/110).
In context.js file we can mock the `router.push` function with: 
then in the test asserting that the url is in the window variable:
=> feat(sui-studio): add mocha global to test url redirects

packages/sui-studio/src/components/test/index.js
`hoistNonReactStatics` only preserve the static (non-react) METHODS
The desired behaviour requires to preserve the displayName to get them in testing
```
class A extends React.PureComponent {
static displayName = 'A'
render() { return null }
}
A.staticMethod = () => 'B'
const AA = props => (
<SUIContext.Provider value={nextContexts.default}>
<A {...props} />
</SUIContext.Provider>
)
hoistNonReactStatics(AA, A)
A.displayName // 'A'
A.staticMethod // f()...
AA.displayName	// undefined
AA.staticMethod // f()...
```
=> feat(sui-studio): provide the displayName to the tested components

packages/sui-studio/src/components/test/index.scss
When having an error, if the error is large, it disappears from the window and it's quite annoying because most of the time you can't read the message.
To solve this, you have to force a width in the `dev tools` of that element, and these styles disappear after applying a change in the test.
Give a `max-width` to the errors and test window to avoid this.
=> fix(sui-studio): stop having super large windows when errors are long

packages/sui-mockmock/README.md, packages/sui-mockmock/src/http/clientMocker.js, packages/sui-mockmock/src/http/mockerInterface.js, packages/sui-mockmock/src/http/serverMocker.js
- get nth request (url, body, headers) from clientMocker
Inside your client tests, now you can get a request mocked by sui-mockmock and inspect it.
For example you want to assert that the body of a certain request has a concrete body in order to test that your usecase is doing the transformations in a properly way
- First rectangle gets the first request : `const request = mock.requestNTH(0)`
-Second  rectangle asserts that the  request body is equal to a super long string allocated in a variable. `expect(request.body).to.be.equal(category245Ad.body)`
Implement both `toStandardRequest` and `requestNTH` in the serverMocker.js.
=> feat(sui-mockmock): get nth request (url, body, headers) from clientMocker

packages/sui-studio/src/components/test/index.scss
When having some tests and/or errors that overflow the window, we have no scroll.
* Made max-width of the test window wider
* Added scroll in case of overflow
=> feat(sui-studio): add scroll to the tests section

packages/sui-studio/bin/sui-studio-generate.js
It is a common scenario to add images to a component's documentation. While useful, these images shouldn't have an impact on the package size.
This PR adds the `assets` folder -commonly used for images and other static files for documentation- to the `.npmignore` file of the component.
=> feat(sui-studio): add assets folder to .npmignore

packages/sui-test/README.md, packages/sui-test/bin/sui-test-e2e.js
There is a need in UniqTools to be able to run E2E tests without Cors and in various browsers.
For them we have added two new flags:
--noWebSecurity
--browser
Example of use:
```
λ npx sui-test e2e --noWebSecurity --baseUrl=http://localhost:3000 --gui --browser firefox
```
Pending update of README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/843)
=> [Feature] sui tests add new flags

packages/sui-bundler/bin/sui-bundler-build.js
Avoid some files to be added to the cache as they're resulting on users having to download too much files unnecessarily.
=> feat(sui-bundler): better filtering to ditch files not needed for the SW

packages/sui-react-router/src/Router.js
Create a prevState reference to compare with the nextState so we avoid updating the state (and cause a re-render of the app) if it's not needed.
=> fix(sui-react-router): avoid not needed re-renders

package.json, packages/sui-widget-embedder/README.md, packages/sui-widget-embedder/package.json, packages/sui-widget-embedder/src-react/Widget.js
We've found in Fotocasa that sometimes we want to render the same Widget in, for example, a list of cards. So we're adding a way to render the same component over different HTML nodes while keeping the old compatibility.
=> feat(sui-widget-embedder): allow multiple containers for single Widget

packages/sui-decorators/src/decorators/cache/index.js, packages/sui-decorators/test/server/cacheSpec.js
We added a fix to the sui-decorators, to manage the same method in different instances of the class.
=> [sui-decorators] Reuse cache instances

packages/sui-i18n/src/i18n.js, packages/sui-i18n/test/i18nSpec.js
Currently on our `i18n` we don't provide with a method to format percentages. 
This `PR` adds a new method `.p()` that adds a percentage sign to the number we pass on as a value.
`console.log(i18n.p(69));`
would tipically output:
`69 %`
=> feat(sui-i18n): add percentage formatting capability to i18n

packages/sui-bundler/bin/sui-bundler-build.js
We don't need to load the SourceMaps files when installing on ServiceWorker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/865)
=> [sui-bundler] Avoid load source maps

packages/sui-ssr/package.json, packages/sui-ssr/server/template/index.js
Use jsesc in order to encode possible xss attacks 
API could potentially return a string with script tag that breaks our initial props and gets executed
=> fix(sui-ssr): fix possible xss

packages/sui-mono/README.md, packages/sui-mono/bin/sui-mono-phoenix.js, packages/sui-mono/src/config.js
Adds the `--scope` param in order to just phoenix one package
`npx @s-ui/mono phoenix --no-root --scope atom/button` will delete atom/button's node_modules folder and package-lock.json file and run `npm install` in it
=> Sui mono/single scope

packages/sui-bundler/shared/minify-js.js
Use a fixed number of cores for CI environments instead relying on cpus from system.
=> feat(sui-bundler): use fixed number of cores for Travis

packages/sui-ssr/archive/Dockerfile.tpl
fix node version to 14-alpine in dockerfile.tpl
Deploy pipelines are blocked because the `pm2:latest-alpine` is installing the node v 14.5.0 and this version is making pods fail when they try to start.
=> fix(sui-ssr): fix node version to 14-alpine in dockerfile.tpl

packages/sui-dashboard/bin/sui-dashboard-components.js
We are seeing some instability when installing the packages before displaying the SUI metrics. We hope that by running the installations in series rather than in parallel, we will eliminate those bugs.
The cost in time is almost double:
```
Serie:
real	12m57.145s
user	6m29.825s
sys	2m41.791s
Parallel:
real	5m47.174s
user	7m26.293s
sys	2m49.787s
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sui-components/sui/888)
=> [sui-dashboard] Use serial spawn over parallel

packages/sui-ssr/README.md, packages/sui-ssr/server/index.js, packages/sui-ssr/server/utils.js
Accept hotname patterns (reg exps) in multisite config. 
```json
{
"multiSite": {
"my-trucks.com": "public-trucks",
"v([0-9]+).my-trucks.com": "public-trucks",
"default": "public-cars"
}
}
```
=> feat(sui-ssr): accept host patterns in multisite config

packages/sui-bundler/factories/createDevServerConfig.js, packages/sui-bundler/package.json
Added `transportMode` to `ws` and `injectClient` to false to avoid problem with ECONNRESET.
```
// Use 'ws' instead of 'sockjs-node' on server since we're using native
// websockets in `webpackHotDevClient`.
transportMode: 'ws',
// Prevent a WS client from getting injected as we're already including
// `webpackHotDevClient`.
injectClient: false,
```
The problem:
=> fix(sui-bundler): use native ws as sockjs is giving problems with latest Node versions

packages/sui-widget-embedder/README.md, packages/sui-widget-embedder/src-react/Widget.js
Add a way to send a general context object agnostic to:
- Business logic and architecture decisions (as this is open source and context could be something different to what we use in Adevinta).
- Easy to be expanded as it doesn't rely that each prop is a property in the context (so, it's tolerant to future changes).
- Update README and deprecate `browser`, `i18n` and `domain` props intended for the creation of the context (now is more agnostic).
=> feat(sui-widget-embedder): allow a way to send a general context object

packages/sui-studio/README.md, packages/sui-studio/bin/sui-studio-build.js
Better use `--before-build` flag instead of `--phoenix-command` because it's more open to execute whatever you want and even do more things than just a "phoenix".
**_Note_: Since this is a new feature not used anywhere, we are not creating a major version for it.**
- **`-O, --only-changes`**: only build changed components or demos
- **`-B, --before-build <command>`**: command to be executed before the build (not working with multiple commands like `npx sui-mono phoenix && npx sui-lint js`, try to group them into just one: `npm run before_build`, for example)
```bash
npx sui-studio build
```
```bash
npx sui-studio build --only-changes --before-build="npx sui-mono phoenix"
```
=> [fix] change studio build flag name

packages/sui-test/bin/karma/config.js, packages/sui-test/package.json
Some 3rd party seems to be trying to load some svg. On sui-test we're adding the possibility to import svg but keeping it as null.
=> feat(sui-test): add support to svg import on null-loader

packages/sui-svg/package.json
Use latest sui-bundler for sui-svg so we could use Node 14 without the need of compile sass binaries.
=> feat(sui-svg): upgrade to latest sui-bundler version

packages/sui-ci/README.md, packages/sui-ci/bin/sui-ci-release.js, packages/sui-ci/bin/sui-ci-update-commit-status.js, packages/sui-ci/bin/sui-ci.js, packages/sui-ci/package.json, packages/sui-ci/src/index.js, packages/sui-ci/src/release.js, packages/sui-ci/src/updateCommitStatus.js, packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/package.json
=> feat(sui-ci): add release command

packages/babel-preset-sui/package.json, packages/babel-preset-sui/src/index.js
Add babel-plugin-preval plugin. This plugin allow us to use code to be evaluated in Babel. Useful to read folder and files content instead of bundling them. Not only could be useful for sui-studio problems but, for example, for configurations or to improve code performance buy pre evaluating some things instead doing them in runtime.
=> feat(babel-preset-sui): add babel-plugin-preval plugin to unlock some further optimizations

packages/sui-ci/src/release.js
Updates master branch before starting release process
We've got this error message in our component's repo
```
To https://github.mpi-internal.com/scmspain/frontend-jobs--uilib-components.git
* [new tag]           candidate/searchIJ-1.43.0 -> candidate/searchIJ-1.43.0
! [rejected]          HEAD -> master (fetch first)
error: failed to push some refs to 'https://github.mpi-internal.com/scmspain/frontend-jobs--uilib-components.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[sui-mono …
```
=> feat(sui-ci): pull changes before running release command

packages/sui-decorators/src/decorators/cache/algorithms/Cache.js, packages/sui-decorators/src/decorators/cache/algorithms/LRU.js, packages/sui-decorators/src/decorators/cache/algorithms/Redis.js, packages/sui-decorators/src/decorators/cache/index.js, packages/sui-decorators/src/index.js
This PR attempts to add cache invalidation. The need of this feature is explained below with an example:
The `GetCurrentSessionUseCase` method provides information of the active session and it's being called in several places in a same page, `cache` decorator was added to avoid duplicated calls.
```js
@cache({
ttl: '1 minute',
cacheKeyString: 'HTTPUserRepository#currentSession'
})
@inlineError
currentSession() {
// stuff
}
```
However if the user logouts there is no way to invalidate this cache. I thought about two options to avoid this issue.
-  A new decorator `invalidateCache`, which receives the key and invalidates the cache
- A new decorator `injectCache`, which receives the key and returns the cache. Then `clear` method could be called (see …
=> feat(sui-decorators): add cache invalidation proposal

packages/sui-react-router/src/internal/createTransitionManager.js, packages/sui-react-router/test/common/RouteSpec.js
Routes that were placed below a Route with a regexp, were not working
ISSUES CLOSED: #946
After adding the `regexp` feature to `sui-router`, routes that were placed below that one were not working.
For example:
```
<Route path='/static' component={...} />
<Route regexp={...} component={...} />
<Route path='/static2' component={...} />
```
When visiting `/static` we would have no problem. On the other hand, when visiting `/static2` it would not work.
fix #946
=> fix(sui-react-router): fixed Routes below a Route that use regexp

packages/sui-studio/src/components/demo/fetch-styles.js
It seems that the `app` chunk, that's the problematic one: 
So, we're generating all styles in the same chunk. Instead, we're going to be sure the chunks for styles are lazy and thus separated in different chunks. This should benefit terser in order to avoid crashing.
Before (app is 25MB):
After (app is 5MB):
=> feat(sui-studio): separate big app chunk in smaller ones to improve build and avoid crash

packages/babel-preset-sui/src/index.js
Cache babel config to avoid executing the config method for every file transformed.
=> feat(babel-preset-sui): cache babel config

packages/sui-studio/src/components/demo/index.js
Acceptance criteria:
1.- Go to a component demo
2.- Select any theme
3.- Select another different component demo
4.- It looks like your demo is returning the theme selected cuz your theme selector menu is displaying it, but the style loaded is the default one.
5.- Go to the first Displayed component (step one).
6.- Select any other theme, and select again the theme selected 4 the bug (step 2). Thats the right style might be presented.
=> fix(sui-studio): theme not charged when changing between components despite of presenting it selected in theme selector

packages/sui-studio/src/components/documentation/Api.js
In some cases the api tab is not working due to a multiple exports incidence detected by react-docgen
react-docgen provides a resolver solution called `resolver.findAllComponentDefinitions` which analyzes all the module exports in its AST analyzer returning an array of exported elements.
[react-docgen parser resolver](https://github.com/reactjs/react-docgen#resolver)
the tooltip API for sui-components it's broken
[sui-components-tooltip](https://sui-components-kjcnxnuko.vercel.app/workbench/atom/tooltip/documentation/api)
and thats the new solution
=> fix(sui-studio): some api doc tabs not working fine

packages/sui-studio/bin/sui-studio-generate.js
Use native `prepare` script instead `build` as it will be needed for workspaces.
=> feat(sui-studio): use native prepare script instead build

packages/sui-mono/bin/sui-mono-release.js
Detect if should unshallow before doing it to avoid problems on Travis builds like this one:
This is happening as Travis is cloning repos with a 50 commits depth by default. That means that if the repo has less than 50 commits the clone is not a shallow and thus we should not try to unshallow it.
=> feat(sui-mono): detect if should unshallow

packages/sui-bundler/webpack.config.prod.js
We must keep comments from HTML in order to keep using magic comments in our apps.
=> fix(sui-bundler): avoid removing magic comments from index html

packages/sui-lint/eslintrc.js
Add `no-var` rule to warning so we avoid using `var` instead `let` or `const`.
=> feat(sui-lint): add no-var rule warning

packages/sui-test/README.md, packages/sui-test/bin/mocha/register.js, packages/sui-test/src/config.js
🆕 Config to add to the package.json the modules that need to be transpiled for `sui-test server`.
This will simplify and fix all the problems we're facing on different projects where some external modules need to be transpilated because are using ESModules.
=> feat(sui-test): add a config to force transpilation of modules via config

packages/sui-studio/package.json
The current `react-docgen` version 5.3.0 in the project doesn't have the optional chaining feature support and SUI Studio can't generate de API documentation in few components, like [Autosuggest](https://sui-components.now.sh/workbench/molecule/autosuggest/documentation/api) and show the next error:
```
Uncaught (in promise) Error: did not recognize object of type "ChainExpression"
```
This problem is fixed in the 5.3.1 version after update `ast-types` to [the last version](https://github.com/reactjs/react-docgen/releases/tag/v5.3.1) *(9 days ago)*
`react-docgen` solve it in [this commit](https://github.com/reactjs/react-docgen/pull/468/files) 
Update the dependency to 5.3.1 😊
=> chore(sui-studio): update react-docgen to ad support to optional chaining

packages/sui-bundler/webpack.config.lib.js
When working on umd packages, we should avoid using chunks to fix this:
=> feat(sui-bundler): disable Code Splitting for libs built with Webpack

packages/sui-studio/workbench/src/app.js
Use `default` on all styles as `ESModules` are not used by default on new @s-ui/bundler.
This fixes missing styles on dev mode for components using demo.js playground.
=> fix(sui-studio): fix themes on dev mode

packages/sui-studio/src/components/demo/fetch-styles.js
Importing styles using css-loader now returns an ESModules so we've to extract the `default` from the module to get it working.
=> fix(sui-studio): fix styles not showing on start mode

packages/sui-react-router/README.md, packages/sui-react-router/src/Link.js, packages/sui-react-router/src/Router.js, packages/sui-react-router/src/internal/ReactUtils.js, packages/sui-react-router/src/withRouter.js, packages/sui-react-router/test/browser/LinkSpec.js, packages/sui-react-router/test/common/IndexRouteSpec.js, packages/sui-react-router/test/common/LinkSpec.js, packages/sui-react-router/test/common/RedirectSpec.js, packages/sui-react-router/test/common/RouteSpec.js, packages/sui-react-router/test/common/hooksSpec.js, packages/sui-react-router/test/common/matchSpec.js, packages/sui-react-router/test/common/withRouterSpec.js
Use new JSX by avoiding importing React manually.
=> feat(sui-react-router): use new React jsx import from babel

packages/sui-studio/src/components/globals.js, packages/sui-studio/src/components/tryRequire.js, packages/sui-studio/src/components/utils.js, packages/sui-studio/workbench/src/app.js
=> fix(sui-studio): avoid bundling all styles on dev and fix scss linking

packages/sui-lint/eslintrc.js
Checking for `babel-preset-sui` should be done with a `try/catch` to avoid this problem:
With that fix, `@s-ui/lint` will work on pure node projects without `babel-preset-sui` installed.
=> fix(sui-lint): use it without babel preset sui for node projects

packages/sui-hoc/src/withOpenToggle.js
We use this HOC to add Toggle behavior in components, such as `MoleculeAutosuggest`, and the default state to `isOpen` is **false**, ignoring the prop `isOpen`.
We have a use case to load the Autosuggest showing the options, so we need to use the `isOpen` prop to do it.
=> fix(sui-hoc): define default state with prop

packages/sui-domain/src/Entity.js, packages/sui-domain/src/ValueObject.js, packages/sui-domain/src/inherits.js
Avoid the transformation of the Babel. So we move the ugly transformation to deal with ESModules on node.js for now. 
Not ideal solution but solving the problem for now.
=> fix(sui-domain): avoid transforming with Babel to avoid problems with @s-ui/test

packages/sui-i18n/README.md, packages/sui-i18n/src/i18n.js, packages/sui-i18n/test/i18nSpec.js
Currency symbol 💲
This PR adds currency symbol support
None
```js
i18n.currency = 'USD';
console.log(i18n.currencySymbol) // $
```
=> feat(sui-i18n): add currency symbol support

packages/sui-bundler/bin/sui-bundler-build.js, packages/sui-bundler/package.json, packages/sui-bundler/service-worker.js, packages/sui-bundler/webpack.config.prod.js
Package goes from 85MB to 79MB with these changes. ~8% less.
=> feat(sui-bundler): remove dependencies and use newest webpack-manifest-plugin

packages/babel-preset-sui/src/index.js
Use wrap mode instead removing them directly so dev environments still has prop types.
Anyway propTypes will be removed by terser on Production.
=> feat(babel-preset-sui): avoid removing propTypes and wrap with NODE_ENV static check

packages/sui-js/package.json, packages/sui-js/src/ua-parser/index.js
Update bowser version
Update the latest version of the bowser library that includes the latest updates of the google bot user agents.
With the current version, it is not returning the user agent correctly when it is a google bot. Example:
"Mozilla / 5.0 (Linux; Android 6.0.1; Nexus 5X Build / MMB29P) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 87.0.4280.88 Mobile Safari / 537.36 (compatible; Googlebot / 2.1; + http: // www. google.com/bot.html) ", it is returning us as browserName" Chrome "instead of" Google bot"
https://github.com/lancedikson/bowser/blob/master/README.md
=> feat(sui-js): update bowser version

packages/sui-js/src/ua-parser/index.js
This PR fixes an issue related with using `PLATFORMS_MAP`. It should be `bowser.PLATFORMS_MAP` instead of `import  {PLATFORMS_MAP} from 'bowser'`.
See [src](https://github.com/lancedikson/bowser/blob/f09411489ced05811c91cc6670a8e4ca9cbe39a7/src/bowser.js)
None
None
=> fix(sui-js): fix bowser map

packages/sui-widget-embedder/compiler/development.js
Widget are not working in dev mode, the bundle.js file is without the transpiled code
=> fix(sui-widget-embedder): widgets not loading in dev mode

packages/sui-ssr/README.md, packages/sui-ssr/bin/sui-ssr-release.js
Start using `GITHUB_TOKEN` instead `GH_TOKEN` to normalize this environment variable across systems.
Keep `GH_TOKEN` as a fallback to avoid breaking compatibility.
=> feat(sui-ssr): use GITHUB_TOKEN instead GH_TOKEN to normalize but keep compatibility

packages/sui-hoc/src/withIntersectionObserver.js
It adds a safety check before disconnecting the intersection observer for those components where the unmount happens before the intersectionObserver can be saved in the state.
Control with an if statement if the intersection observer already exists.
=> fix(sui-hoc): add safety check before disconnecting intersection observer

packages/sui-test/README.md, packages/sui-test/bin/sui-test-e2e.js, packages/sui-test/package.json
Add parallelization support to sui-test via cypress.
Example of usage (private link, sorry OSS):
https://github.mpi-internal.com/scmspain/frontend-re--ut-web-app/pull/288
=> feat(sui-test): add support to parallelization

packages/sui-ssr/server/utils/factory.js, packages/sui-ssr/test/server/fixtures/index.js
This PR fixes an issue when defining the request url for the Critical CSS service because of an object reference mistake .
=> fix(sui-ssr): fix critical css config object

packages/sui-mono/bin/sui-mono-release.js
This will allow us to call this command on PR without the noise and the hassle to check if we're on PRs.
=> feat(packages/sui-mono): check isMaster before creating scopes

packages/sui-test/bin/karma/babelPatch.js
Fix an existing magic that was making testable components in studio could have their contexts available, but it started to fail since a new path for tests was created in `sui-studio`.
=> fix(packages/sui-test): fix new test path in studio

packages/sui-test/README.md, packages/sui-test/bin/mocha/applyEsmOverride.js, packages/sui-test/bin/mocha/register.js
ISSUES CLOSED: #1068
According to the description of issue #1068 this adds an optional config attribute for the `sui-test server` command in order to patch the CJS Loader in `node > v12.16`.
Now, we'll be able to enable this patch by the `esmOverride` config like:
```
"sui-test": {
"server": {
"forceTranspilation": ["@adv-ui"],
"esmOverride": true
}
}
```
And server tests will be able to transpile patched files:
#1068
=> fix(packages/sui-test): add option to patch CJS loader in node v12.21.0

package.json, packages/sui-pde/package.json
sui-pde exports hooks which need react and therefore need it as dependency although the exact version should be set by the package which uses those hooks
=> chore(packages/sui-pde): react as peer dependency

packages/sui-studio/package.json
In MA we started to use `@testing-library/react-hooks`, but seems doesn't exists the needed dependency. 
We're recieving this error: 
`npm WARN @testing-library/react-hooks@4.0.1 requires a peer of react-test-renderer@>=16.9.0 but none is installed. You must install peer dependencies yourself.`
=> chore(packages/sui-studio): add react-test-renderer dependency

packages/sui-studio/src/components/style/index.js
This fix should remove the console warning present in each demo.
=> fix(sui-studio): fix prop types warning for Style

packages/sui-test/README.md, packages/sui-test/bin/sui-test-e2e.js
Add plugins support on e2e sui-test command so we can customize, for example, the browser's launching flags.
See: https://docs.cypress.io/guides/tooling/plugins-guide.html
=> feat(packages/sui-test): add plugins support on e2e

packages/sui-test/Dockerfile
When running Cypress, default browser is Electron, which yeah is Chromium, but our users actually use Chrome. Shouldn't we run our tests in Chrome instead? Well, when using our docker image `suitools/test` we currently **can't run tests in Chrome**.
❌ Our custom docker image is currently based on `cypress/base` which exposes `electron` as the only available browser. If you run tests adding `--browser=chrome` you receive a "can't find chrome" error.
✅ There's another official image called `cypress/browsers` which actually adds Chrome [(see Cypress docker images)](https://github.com/cypress-io/cypress-docker-images#cypress-docker-images-). Existing setups should keep working as usual.
=> Fix/sui test/e2e docker image to use browsers

packages/sui-test/README.md, packages/sui-test/bin/sui-test-e2e.js
Adds some options for e2e command:
- **headless**: if you set a different browser by using `--browser` option, can't be headless unless you specify it.
- **defaultCommandTimeout**: since default is 4s, we need to set a higher value in order to ensure some tests pass in CI, because CI processes are sometimes slower than local.
=> feat(packages/sui-test): add headless and default command timeout options

packages/sui-test/package.json
add `@testing-library/cypress` lib. 
With this [lib](https://testing-library.com/docs/cypress-testing-library/intro/) we will be able to use the selectors that we use in the test components in our e2e tests.
=> feat(packages/sui-test): add @testing-library/cypress lib

packages/sui-mono/bin/sui-mono-phoenix.js
=> fix(packages/sui-mono): remove root node_modules when using phoenix

packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/src/PrompterManager.js, packages/sui-mono/src/commitTypes.json
Remove META and examples context in order to stick to better meaningful context for commits
=> feat(packages/sui-mono): use less context for commits

packages/sui-studio/src/components/demo/_style.scss, packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/components/navigation/_style.scss, packages/sui-studio/src/styles/_default.scss, packages/sui-studio/workbench/src/components/Raw/index.scss
The workaround to get the sui-studio scrolling effect in the mock component area as much clean and native as possible. At the moment it is giving undesired behaviors to final applications. The main idea is having a working area as much clean as possible.
The inner div scrolling effect is only used in the component navigator menu, giving to the workbench area the native scrolling like most of our verticals. It also removes the `box-sizing: border-box;` global rule
It also adds a 16px padding to the Raw component (dev mode) in order not to see the mocked component spaced with the workspace boundings.
https://sui-components-51b9cvlxx-schibstedspain.vercel.app/workbench/atom/popover/demo
The current scroll behavior is giving undesired behaviors of popovers
=> fix(sui-studio): studio workspace area scolling behavior workaround.

packages/sui-ssr/README.md, packages/sui-ssr/server/config.js, packages/sui-ssr/server/ssr/index.js, packages/sui-ssr/server/utils/factory.js, packages/sui-ssr/server/utils/index.js, packages/sui-ssr/test/server/utilsSpec.js
- **`createStylesFor`** (`undefined`): Define how the server should manage style imports. When separate styles per page, by default those imports will load css asynchronously but maybe we want that server to add them as an `<link>` in app head and be async or not depends on criticalCSS.
- **`appStyles`** (`string`): Define the webpackChunkName of app styles. These styles usually are imported in `app.js`.
- **`createPagesStyles`** (`false`): Define if pages have style imports that should be managed by the server. The server will get these files from the `asset-manifest.json` file, which should be created by sui-ssr.
> ⚠️ `createStylesFor` does not works as expected when sui-bundler configuration has `onlyHash` defined to `true`.
Published as a beta: `7.21.0-beta.2`
This code is based on FC …
=> feat(packages/sui-ssr): inline dynamic import styles on demand

packages/sui-pde/README.md, packages/sui-pde/src/adapters/optimizely/index.js, packages/sui-pde/test/common/pdeSpec.js
Adds a way to add global attributes so they are set up once and reused every time. The idea behind this PR is to send the site and environment on every impression event
```js
const optimizelyAdapter = new OptimizelyAdapter({
optimizely: optimizelyInstance, // created before
userId: '1234',
hasUserConsents: true,
applicationAttributes: {   // optional, global application attributes that must be send on every experiment activation
site: 'coches.net',
environment: 'development'
}
})
```
=> feat(packages/sui-pde): global attributes to be always used

packages/sui-pde/src/hooks/useExperiment.js, packages/sui-pde/test/common/useExperimentSpec.js
we cannot send Experiment Viewed before the tracking library is ready otherwise it wouldn't include our wrapper stuff
=> fix(packages/sui-pde): wait for tracking lib to be ready

packages/sui-ssr/server/config.js
Hotfix: For more than one async scripts it fails because first is deleting the critical element and others throws an error because can not find parent node of undefined
Ready for test under `@s-ui/ssr@7.22.0-beta.0`
=> fix(packages/sui-ssr): prevent remove already deleted node

packages/sui-ssr/README.md, packages/sui-ssr/bin/sui-ssr-release.js
If you want that release commit does not to trigger a Travis build you could use the flag `--skip-ci` and commit message will have `[skip ci]` string. See more information about [Travis skipping build docs](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build)
This feature will help us to improve our CI pipeline
=> feat(packages/sui-ssr): skip ci release by flag

package.json, packages/sui-test/README.md, packages/sui-test/bin/mocha/register.js
Use flag as `false` by default to avoid problems
=> feat(packages/sui-test): use flag as false by default

packages/sui-bundler/package.json
`fibers` dependency is not longer compatible with node 16 and is causing problems. With Node 16 anyway its benefits are almost none, so we could remove it and everything should work as expected.
=> feat(packages/sui-bundler): remove fibers dependency

package.json
with ** it was installing strange packages that I'd say are not meant to be workspaces
node_modules  integration/empty-studio
node_modules  atom/button
node_modules  integration/sample-studio
on my machine client tests pass now, server test are broken because of module imports
=> chore(Root): workspaces are only package first level folder

package.json, packages/sui-js/package.json
Use legacy peer deps for phoenix. Some dependencies of dependencies uses different React versions and could cause test errors on local
=> fix(Root): use legacy peer deps to run test well in local

packages/sui-test/package.json
Add `cypress-file-upload` dependency in order to enable some Cypress commands that make us test upload files easily.
=> feat(packages/sui-test): add cypress-file-upload dependency

packages/babel-preset-sui/test/server/indexSpec.js, packages/sui-critical-css/package.json, packages/sui-critical-css/src/extract-from-url.js
Improve Critical CSS in order to get better output size by minify by using Clean CSS.
It's a smaller dependency, faster and better. 🚀
=> feat(packages/sui-critical-css): use Clean CSS instead PurgeCSS. 

packages/sui-mono/package.json
Use latest version of commitizen with 2MB less of dependencies.
https://packagephobia.com/result?p=commitizen@4.2.4
=> feat(packages/sui-mono): use latest commitizen with less dependencies

packages/sui-ssr/bin/sui-ssr-release.js
Move ssr7 feature to ssr6 https://github.com/SUI-Components/sui/pull/1142
**Context**
In a multipackage repository scenario, maybe we do not want to release the last commit because it could be another package release (with his self-release tag).
We enable the possibility to send commit via a command in order to define which commit we want to release. In a Travis CI pipeline it could be `npx @s-ui/ssr release --email git@email.com --name gitName --commit $(TRAVIS_COMMIT)`
=> feat(packages/sui-ssr): enable define commit to release

packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/components/navigation/_style.scss
The actual studio (v9) is presenting a 220px margin left also when the navbar is hidden for the mobile devices (small breakpoint). This PR fixes it preserving the alder transition.
=> fix(packages/sui-studio): mobile navbar behavior

packages/sui-studio/bin/sui-studio-generate.js
Studio generate demo file imports component from root component path and `package.json` indicates that entry point is `/lib/index.js`
It causes confusion in development mode because src changes compile but not updates demo.
This PR fix studio generate, doing that demo file imports uses `src` code
Reported by @Sabri1209
=> fix(packages/sui-studio): studio demo should use src code instead lib

packages/sui-mono/bin/sui-mono-commit-all.js, packages/sui-mono/src/prompter-manager.js
Use porcelain mode instead checking the message of the status (as some users could have this in Spanish instead).
=> fix(packages/sui-mono): Avoid checking git status message and use porcelain instead

packages/sui-ssr/bin/sui-ssr-release.js
We have experienced some troubleshooting with `--package-lock-only` option in npm 7.
As we can see in **npm CLI issue:** https://github.com/npm/cli/issues/2747 "_the right behaviour is what npm 6 eventually did - package-lock-only implies package-lock. This was an unintentional breaking change in v7._"
For that reason, this PR requires a clean install (deleting lock file and adding node_modules) in order to generate a correctly new lock file and use it for the release.
=> fix(packages/sui-ssr): fix ssr lock file update for npm 7

packages/sui-studio/bin/sui-studio-generate.js, packages/sui-studio/src/components/demo/fetch-styles.js
Use correct path themes for npm start and build mode.
Use @s-ui/theme on generating new components as peerDependency.
=> fix(packages/sui-studio): Use correct paths for themes on npm start

packages/sui-studio/bin/cpx.js, packages/sui-studio/package.json
Remove big dependency (cpx) with some deprecated dependencies and use `copyfiles` instead with a wrapper, keeping binary compatibility to avoid doing changes on repositories.
This will remove 6MB of dependencies from @s-ui/studio (137MB -> 131MB).
=> feat(packages/sui-studio): Remove deprecated dependency but keep compatibility

packages/sui-theme/src/settings/_spacing.scss
Add new variables with the gap spaces to use on `gap` CSS property
```css
.element {
align-items: center;
display: flex;
gap: $g-l;
}
=> feat(packages/sui-theme): add gap variables

packages/sui-js/package.json
htmr 1.0.0 has react 17 support, looks like there is no breaking change although I've published a beta version which I'm about to test for possible incompatibilities
npm@7 + components in same repo doesn't work as expected as while running the studio test it breaks because of two different react versions
=> feat(packages/sui-js): update htmr version

packages/sui-ssr/server/ssr/index.js
Stylesheet links are not being replaced well in some of cases:
- If a stylesheet link is already async, it's being replaced again (duplicating some attributes)
- If HTML string has more than one link, it's only replaced the first one
This PR is fixing these 2 scenarios.
=> fix(packages/sui-ssr): fix async stylesheet links replacement

packages/sui-pde/src/hooks/platformStrategies.js
Avoid sending track `Experiment Viewed` every time we call the `useExperiment`.
We store the event sent for the Experiment in order to avoid sending it more than once.
=> feat(packages/sui-pde): Track experiment viewed only once

packages/sui-pde/README.md, packages/sui-pde/src/adapters/default.js, packages/sui-pde/src/adapters/optimizely/index.js, packages/sui-pde/src/hooks/useFeature.js, packages/sui-pde/src/pde.js, packages/sui-pde/test/common/useFeatureSpec.js
This PR adds feature variables support
- Add feature variables support using [getAllFeatureVariables](https://docs.developers.optimizely.com/full-stack/docs/get-all-feature-variables-javascript) method.
- Tests added
Variables can be added in feature flags from Optimizely dashboard as follows:
None
Returns all feature variables for the specified feature flag. If not `variables` are being set the default value will be an empty object (`{}`)
```js
import {useFeature} from '@s-ui/pde'
const MyComponent = () => {
const {isActive, variables} = useFeature('myFeatureKey') // variables = an object with all the feature variables
return (
<p>
The feature 'myFeatureKey' is{' '}
{isActive ? `active and price value is ${variables.price}` : 'inactive'}
</p>
)
}
```
=> feat(packages/sui-pde): add feature variables support

packages/sui-critical-css/package.json, packages/sui-critical-css/src/config.js, packages/sui-critical-css/src/extract-from-url.js
=> feat(packages/sui-critical-css): Use chromium only and add UA to critical-css service

packages/sui-bundler/README.md, packages/sui-bundler/loaders/linkLoaderConfigBuilder.js, packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.prod.js
This PR:
- Tries to improve sass build time using an experimental loader based on [fast-sass-loader](https://github.com/yibn2008/fast-sass-loader) named [super-sass-loader](https://github.com/andresz1/super-sass-loader). I forked it and published a version with changes needed to make it work properly with our project (I wanted to test and iterate it fast, if it works as expected we can open a PR to the previous repo and use it instead). Use `useExperimentalSCSSLoader` to try it out (by default disabled)
Results using Milanuncios web app:
**Before**
**After**
- Adds a way to measure build times. Use `measure` to try it out (by default disabled)
None
=> feat(packages/sui-bundler): improve sass build time

packages/sui-test/README.md, packages/sui-test/bin/karma/index.js
To avoid "logs noise" in CI, I propose enabling a karma option for CI to make `captureConsole` customizable.
Also, I hope it will improve a little bit memory usage in CI
=> feat(packages/sui-test): enable or disable logs in ci for browser test

packages/sui-test/bin/sui-test-e2e.js
Currently, there's no way to set a custom viewport height and / or width via CLI.
This PR allows for that.
Introducing two new options for `sui-test-e2e`: `viewportHeight` and `viewportWidth`.
n/a
n/a
=> feat(packages/sui-test): allow for custom viewport height and width

packages/sui-bundler/package.json
This PR upgrade super-sass-loader version to add `@use` support (see [changes](https://github.com/andresz1/super-sass-loader/commit/8b83147214459d53df739809e32f06b74ebb1216)). Now `@uses` are cached and appended at the top of the merged scss file
`@use` wasn't working as expected with experimental scss loader
None
=> upgrade super-sass-loader version to add use support

package.json, packages/sui-consents/package.json, packages/sui-mockmock/package.json, packages/sui-pde/package.json, packages/sui-pde/test/browser/browserSpec.js, packages/sui-react-head/package.json, packages/sui-react-router/package.json, packages/sui-ssr/package.json
Instead of installing different @s-ui/test versions, we use only the one from the root.
Still this makes specific scripts work on every workspace.
=> feat(Root): Use single @s-ui/test across packages

packages/sui-bundler/README.md, packages/sui-bundler/bin/sui-bundler-build.js, packages/sui-bundler/bin/sui-bundler-dev.js
Added shorthands for `--link-package` and `--link-all`.  `-l` and `-L` respectively.
Added --link-multiple-packages option for the command line.
This allows to pass multiple comma-separated directories while running _dev_ script instead of using `--link-package` option for each one. 
E.g.: `sui-bundler dev --link-multiple-packages=/my/domain,/my/components/header`
None
=> feat(packages/sui-bundler): add shorthand to link packages

packages/sui-pde/README.md, packages/sui-pde/src/adapters/optimizely/index.js, packages/sui-pde/src/hooks/useFeature.js, packages/sui-pde/test/common/pdeSpec.js, packages/sui-pde/test/common/useFeatureSpec.js
Tracking useFeature hook so we are able to analyse user behaviour based on a feature value. How will this work?
- on useFeature, we will send an Experiment Viewed with the feature key as experimentName and `On State` or `Off State` as variationName
- if a feature flag is used in a feature test, the tool will also send an Experiment Viewed for each linked experiment, working exactly the same way we track experiments with useExperiment
=> feat(packages/sui-pde): track feature flags and feature tests

packages/sui-pde/src/hooks/platformStrategies.js
Currently forcing a feature flag is not working with Server-Side Rendering. This PR will allow it.
How could it be done ?
```js
import {useLocation} from '@s-ui/react-router'
import {useFeature} from '@s-ui/pde'
const useEnhancedFeature = (key, attributes) => {
const location = useLocation()
return useFeature(key, attributes, location.search)
}
export default useEnhancedFeature
```
Since `useLocation` has Server-Side Rendering support this will work out of the box.
Another alternative would be to provide the location somehow when creating an instance of `PDE`
None
=> feat(packages/sui-pde): force feature ssr support

packages/sui-bundler/README.md, packages/sui-bundler/shared/minify-css.js, packages/sui-bundler/shared/minify-js.js, packages/sui-bundler/webpack.config.prod.js
Use `esbuild` for CSS minification instead `css-minimizer-webpack-plugin` when `useExperimentalMinifier` is enabled.
=> feat(packages/sui-bundler): Use esbuild for CSS minification

packages/sui-i18n/src/i18n.js, packages/sui-i18n/test/i18nSpec.js
Added a new method to add translations dynamically and refresh the translator.
N/A
It is useful if you are adding new translations dynamically. You can load less translations by default and then, when you navigate to a certain page, load the specific translations for that.
=> feat(packages/sui-i18n): add or modify translations dynamically

packages/sui-react-head/src/types.d.ts, packages/sui-react-head/src/utils.tsx
=> feat(packages/sui-react-head): Avoid preload and prefetch link tags to create duplicated keys

packages/sui-theme/src/utils/_url.scss
With this PR, when using the `image-url` utility function, we'll be able to pass images with a starting slash because sometimes in dev envs, URLs are generated relative. If we don't put the slash, it will be added to the final URL.
```css
$url-statics: 'https://my-cdn.com/';
background-url: image-url('my-image.jpg'); /* Will generate: `https://my-cdn.com/images/my-image.jpg` */
background-url: image-url('/my-other-image.jpg'); /* Will generate: `https://my-cdn.com/images/my-other-image.jpg` */
```
=> feat(packages/sui-theme): make url final slash optional

packages/sui-studio/src/components/demo/fetch-styles.js
Working with themes, sbdy may need to load index.scss files in a demos that are currently not loaded (in case of existing) with de default theme wiew. It loads by default the package styles, ignoring the index.scss file located in the demo directory. This PR fix this behavior diferentiating between 3 different cases:
- Theme selected --> loads that file
- default theme && not demo/index.scss --> loads src/index.scss component styles file
- default theme && demo/index.scss --> loads demo/index.scss demo styles file
=> fix(packages/sui-studio): studio default style loading

packages/sui-i18n/src/i18n.js
This PR allows setting a custom culture for `n` and `c`.
We want to enable this behaviour since we want to format our prices with a custom culture. Given `es-ES` the price `1000` is formatted as `1000 €` (expected result according RAE) and we want to format it as `1.000 €`. `de-DE` works as expected for us for this special case.
If you have any other idea of how to handle this case properly let me know 🙏🏻
=> feat(packages/sui-i18n): support custom culture in n and c

packages/sui-theme/src/components/atom/input/_settings.scss
Due to the SCSS architecture that we have mounted, it is not correctly collecting the color assignment of the different portals, because the variable assignment is not in this component but in the sui-theme.
We proceed to remove the assignments from here and move them to the component
Related PR:
https://github.com/SUI-Components/sui-components/pull/1873
=> feat(packages/sui-theme): Scss changes for the atom input

packages/sui-bundler/bin/sui-bundler-dev.js, packages/sui-bundler/factories/createDevServerConfig.js
CI is facing sometimes problems with number of opened files while watching:
Watching files on CI doesn't make any sense. With this PR, we're stopping watching files to avoid this problem.
=> feat(packages/sui-bundler): Avoid watching files on CI and make it configurable

packages/sui-studio/bin/sui-studio-generate.js
It fixes a typo that prevents generating a new component in the studio
```npm run generate context component``` will work properly now.
=> Fix typo that prevent to generate a new component in studio

packages/sui-studio/bin/sui-studio-generate.js
It fixes the npm script ```prepare``` in the template of a new generated component.
When ```npm run generate context component``` the script ```prepare``` in ```package.json``` will copy styles to ```lib``` folder.
=> Fix prepare script to copy styles in generate template

packages/sui-react-router/src/Link.js
Added the possibility to send a state between routes
We use the react-router functionality to pass state to the push action
```js
import {Link} from '@s-ui/react-router'
const routeState = {stateProp: 'myStateProp'}
<Link to={href} {...props} state={routeState}>
{children}
</Link>
```
=> feat(packages/sui-react-router): pass state to router push

packages/sui-lint/src/helpers.js
Detect if we're at Travis or GitHub Actions so we get the correct commit range.
=> feat(packages/sui-lint): Get commit range on GitHub Actions on linter

packages/sui-lint/src/helpers.js
We've to use for PRs on GitHub Actions a specific commit range instead the `before` and `after`.
=> feat(packages/sui-lint): Use correct commit range for PRs

packages/sui-theme/src/settings/_box-style.scss
Adding a new border-radius for full circle elements
The current rounded: 50%; is ok, but it only works for 1:1 ratio elements, otherwise it produces oval shapes.
=> feat(packages/sui-theme): add new bdrs circular

packages/sui-test-e2e/package.json, packages/sui-test/package.json
Pin `colors` version to avoid infinite loop as `1.4.0` is fine.
=> feat(packages/sui-test): Pin colors version on package.json

packages/sui-lint/bin/sui-lint-js.js, packages/sui-lint/bin/sui-lint-sass.js, packages/sui-lint/src/helpers.js
Instead of showing always `1` filed linted, we show `All` when it's using the default pattern that match with all the source files of the language.
=> fix(packages/sui-lint): Show correct number of linted files

packages/sui-theme/src/_typography.scss
Add new variable to define link font weight, setting normal as default.
We have the need to modify this value on our theme (coches.net)
=> feat(packages/sui-theme): add new link font weight variable

packages/sui-ssr/server/utils/factory.js
We had some crashes when trying to access to the assets-manifest.json file for multisite configuration. This fix allows to do it avoiding crashes.
=> fix(packages/sui-ssr): allow multisite cache assets manifest

packages/sui-theme/src/components/atom/input/_settings.scss, packages/sui-theme/src/settings/_box-style.scss
Add new variable to change the box shadow input size
Set as variable the size so the different verticals can change it
=> feat(packages/sui-theme): Add new box shadow size variable

packages/sui-helpers/file.js, packages/sui-mono/bin/sui-mono-check.js, packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/src/check.js
Filter packages with the private field present as true so we avoid release them and list them as releasable
=> Avoid private packages

packages/sui-mono/README.md, packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/src/config.js, packages/sui-mono/test/server/configSpec.js
There might be repos with restricted and public packages. This repo allows us to use sui-mono config within each package to use its individual access info. In case the current package has no config, it will use the root one, if this one isn't set either it will use `restricted` by default as it did before.
Check out docs update
=> Sui mono/workspace release config

packages/sui-bundler/webpack.config.prod.js
Use es5 for generating bundle for now.
=> feat(packages/sui-bundler): Use as target es5 for now

packages/sui-bundler/webpack.config.lib.js
I got this error when creating a umd library so I just copied productions fallback config
```
ERROR in ../node_modules/@adv-ui/jobs/lib/fetchers/factory.js 1:81-106
Module not found: Error: Can't resolve 'https' in '/Users/jcger/p/frontend-jobs--common/node_modules/@adv-ui/jobs/lib/fetchers'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "https": false }
resolve 'https' in …
```
=> fix(packages/sui-bundler): breaking because of no fallback set

packages/sui-react-initial-props/src/ssrComponentWithInitialProps.tsx, packages/sui-react-initial-props/src/types.d.ts, packages/sui-react-initial-props/src/withInitialProps.tsx
This PR:
- Avoid rendering page in Server-Side if `redirectTo` is defined. Besides saving time, this change avoids type errors since normally when performing a redirect no props are defined. See example:
```js
Page.getInitialProps = () => {
if (!name) {
return {
__HTTP__: { // This will work in Client-Side and Server-Side
redirectTo: '/path'
}
}
}
return {name}
}
```
- Add redirect support in Client-Side. Initially we are using `window.location` but we could also use the router in the future if needed.
We will add tests in the next pair programming session. Made with:
- @rmoralp 
- @jmanrumartinez 
You can try it out installing the following beta package
- `@s-ui/react-initial-props@2.21.0-beta.0`
None
See example above
=> feat(packages/sui-react-initial-props): redirect support

packages/sui-mono/package.json, packages/sui-mono/src/check.js
When a repo is monopackage and there are changes to release, `commit.scope` from `conventional-changelog` has "Root" value, and we need to convert it to a valid package path to check changes.
=> fix(packages/sui-mono): url construction before check changes to release

packages/sui-lint/package.json
Apply a fix from `pettier`: https://github.com/prettier/prettier/blob/main/CHANGELOG.md#fix-lessscss-format-error-12536-by-fisker
=> fix(packages/sui-lint): fix sass format error in prettier

packages/sui-domain/README.md, packages/sui-domain/src/fetcher/AxiosFetcher.js, packages/sui-domain/src/fetcher/FetcherInterceptor.js, packages/sui-domain/src/fetcher/FetcherInterface.d.ts, packages/sui-domain/src/fetcher/InterceptableFetcherInterface.d.ts, packages/sui-domain/src/fetcher/factory.js, packages/sui-domain/test/common/FetcherInterceptorSpec.js
This `PR` introduces a way to intercept all http responses and errors ocurred while using any `fetcher ` from the `sui-domain` package, by defining one single function that will be called every time an http error occurs.
Recently in COCHES NET PRO, we needed a way to handle all http errors ocurred in all requests, to handle 401 status codes and redirect the user back to the login page when their token expired or became invalid.
Our first approach was to intercept errors by creating a facade class inside our domain package, that wrapped the sui-domain fetcher. 
This class, which we called `FetcherInterceptor`, exposed the same methods than the sui fetcher, and intercepted all errors ocurred during any http request, notifying them to a function in charge of error handling.
However, although …
=> feat(packages/sui-domain): Add a way to globally intercept errors on all axios instances

packages/sui-studio/src/runtime-mocha/index.js
So, people could use more files to separate tests. `index` would keep working.
=> feat(packages/sui-studio): Support more files besides the index

packages/sui-ssr/server/index.js
Just a typo from `runnig` to `running` on listen app
=> feat(packages/sui-ssr): fix typo on listen app

packages/sui-pde/src/adapters/optimizely/index.js
Fix the `eventDispatcher` property when initializing Optimizely Instance.
Creating the optimizely instance does not accept an undefined function to dispatch events.
https://docs.developers.optimizely.com/full-stack/docs/configure-event-dispatcher-javascript-node
We must initialize it to the default's optimizely SDK eventDispatcher.
=> fix(packages/sui-pde): fix event dispatcher on creating instance

packages/sui-pde/src/hooks/useFeature.js
Using feature tests (an A/B which is linked to a FF) causes console errors when being activated:
`[OPTIMIZELY] - ERROR 2022-05-19T10:19:19.689Z OPTIMIZELY: Provided experiment_key is in an invalid format.`
This is caused because the tracking function loses the experiment name passing the structured args to the PDE, as `experimentName` was provided for a function which expects the attribute to be `name`
Additionally, the `adapterId` is added to the passed args as it was missing there.
=> fix(packages/sui-pde): fix feature tests

packages/sui-bundler/package.json
Latest upgrade to `sass` `1.52.2` was causing an error on our builds:
```
[1]  @use 'sass:math';$home-categories-base-path: '/home-categories/coches/';
[2]  // Deprecated (sui-theme V7)
[3]  
[4]  
[5]  $m-base: 8px !default;
[6]  $m-v: ceil($m-base); // 8px
[7]  $m-h: $m-base * 2; // 16px
[8]  $m-v-xsmall: ceil(math.div($m-v, 3)); // 3px
[9]  $m-h-xsmall: ceil(math.div($m-h, 3)); // 8px
[10] $m-v-small: ceil($m-v * 0.5); // 4px
----------------------------------------
Error: RangeError: Invalid value: Not in inclusive range 0..128: -1
```
[Sass issue](https://github.com/sass/dart-sass/issues/1712)
=> chore(packages/sui-bundler): upgrade sass dep to 1.52.3

packages/sui-test-e2e/bin/sui-test-e2e.js
Avoid failures when running e2e tests using plugins after updating to the latest `@s-ui/test-e2e` version, and when `scope` parameter is not defined.
Since Cypress 10, plugins do not have a specific folder where to be stored. Plugins are now stored as part of the cypress config file.
This update, performs a fix in terms of compatibility. When a project is updated from a previous `@s-ui/test-e2e` version, if there's a plugins folder, it's required from the Cypress config file, so it keeps working as usual without any breaking change.
Additionally, before the update, if the scope parameter was not defined, tests were loaded from the `integration` folder. After the upgrade, the `scope` parameter has become mandatory and in case it is not defined, tests execution fails. This PR sets a default …
=> Fix some compatibility issues

packages/sui-test-contract/bin/sui-test-contract-publish.js, packages/sui-test-contract/package.json, packages/sui-test-contract/src/setup/index.js, packages/sui-test-contract/src/setup/utils.js
Use SHA as Consumer Version instead using the Absolute Version.
=> feat(packages/sui-test-contract): Use SHA as consumer version for PACT contracts

packages/sui-react-context/src/index.tsx
Expose useSuiContext hook to consume SuiContext.
A simple abstraction to avoid requiring the SuiContext and the `React.useContext` hook from react on each usage.
Also, being this as named export, the editor will help to identify it while writing and automatically add the import on autocomplete.
**Before**
```jsx
import {useContext} from 'react'
import Context from '@s-ui/react-context'
function App () {
const context = useContext(Context)
...
}
```
**After**
```jsx
import {useSuiContext} from '@s-ui/react-context'
function App () {
const context = useSuiContext()
...
}
```
=> feat(packages/sui-react-context): export useSuiContext hook

packages/sui-test-contract/bin/sui-test-contract-publish.js
`TRAVIS_BRANCH`
- for push builds, or builds not triggered by a pull request, this is the name of the branch.
- **for builds triggered by a pull request this is the name of the branch targeted by the pull request.** ⚠️
- for builds triggered by a tag, this is the same as the name of the tag (TRAVIS_TAG).
`TRAVIS_PULL_REQUEST_BRANCH`
- if the current job is a pull request, the name of the branch from which the PR originated.
- if the current job is a push build, this variable is empty ("").
Source: [Travis docs](https://docs.travis-ci.com/user/environment-variables/)
TRAVIS_BRANCH does not work as expected for Pull Request builds
=> fix(packages/sui-test-contract): fix branch name with travis env

packages/sui-studio/README.md, packages/sui-studio/src/components/tryRequire.js, packages/sui-studio/src/runtime-mocha/index.js
Apply the context exported from the `/demo/context.js` file for React components other than just the ones in `/test/index.test.js`. 
Right now the React context exported from `/demo/context.js` is only applied to test files inside `/test/index.test.js`. Since we can now have multiple files inside the `/test` folder of a component by using commands such as: 
```sh
❯ PATTERN=appraisal/report npm run test:studio:ci:watch
```
With this PR we can set the context in files that use the following naming system:
```js
components.{componentName}.test.js
```
```sh
test
├── components.AgencyEvaluationForm.test.js
├── components.AgencyEvaluationInfo.test.js
└── index.test.js
```
This way the Component used in all 3 files will have the exported context from `/demo/context.js` applied.
I used this …
=> feat(packages/sui-studio): add support for subcomponents context mapping

packages/sui-studio/README.md
Fix a section link in the s-ui/studio README.
Fixes the section link in the s-ui/studio README for the CLI Testing Integration info.
=> docs(packages/sui-studio): fix the readme cli section url

packages/sui-theme/README.md, packages/sui-theme/src/classes.scss, packages/sui-theme/src/classes/_margins.scss, packages/sui-theme/src/classes/_paddings.scss, packages/sui-theme/src/classes/index.scss, packages/sui-theme/src/utils/_spacing.scss
Add new spacing utility classes
You can use this in your vertical theme to get an spacing library...
In your vertical theme...
```
@import '~@s-ui/theme/lib/classes'
```
This get...
```
.m-m { <-- general margin medium
margin: 8px;
}
.m-s {
margin: 4px;
}
...
.mt-m { <-- margin top medium
margin-top: 8px;
}
.mt-s {
margin-top: 4px;
}
...
```
=> feat(packages/sui-theme): add spacing utils

packages/sui-studio/src/components/tryRequire.js
Prevent bundle unexpected files, for example:
```bash
./components/ lazy ^\.\/.*\/index\.js$ exclude: \/node_modules\/(.*)\/src\/(.*)\/index.js$ chunkName: src-component-[request] namespace object ./content/account/node_modules/react-dropzone/src/index.js
```
Beta for testing purposes: @s-ui/studio@11.22.0-beta.0
=> fix(packages/sui-studio): exclude all node_modules src files

packages/sui-mono/bin/sui-mono-release.js
We have found some metrics in Accelerate can be affected by some bot contributors in commits/releases. Here it’s [an example of an affected accelerate metric](https://github.mpi-internal.com/scmspain/frontend-fc--web-server/commit/910659f65ccc3eca4aef1577edbca8aa369b078b).
As you can see [on this Pull Request](https://github.mpi-internal.com/scmspain/frontend-fc--web-server/commit/910659f65ccc3eca4aef1577edbca8aa369b078b), we have a [parent commit](https://github.mpi-internal.com/scmspain/frontend-fc--web-server/commit/077de986d7d0cc8158a33a72e7947a562337975d) done by a bot. And this commit has a comment with a `[skip-ci]` tag at the end of the message. Nevertheless, we can see at [Ledger documentation](https://docs.mpi-internal.com/common-platform/ledger/02-technical-reference/10-accelera …
=> feat(packages/sui-mono): move skip flag before commit msg

packages/sui-mono/bin/sui-mono-release.js
Rollback this change https://github.com/SUI-Components/sui/commit/24763e652256613eef4d46460c206963def09e74
PR https://github.com/SUI-Components/sui/pulls?q=is%3Apr+is%3Aclosed
If we add `[skip ci]` as a prefix, we break commit naming convention and conventional-changelog does not work as expected with angular preset
=> fix(packages/sui-mono): add skip-ci as suffix

packages/sui-mono/src/check.js, packages/sui-mono/test/server/checkSpec.js
`refactor` type of commits will now trigger a new release. 
#1478
=> feat(packages/sui-mono): add "refactor" as commit type with release

packages/sui-studio/src/components/demo/_style.scss, packages/sui-studio/src/components/layout/Logo.js, packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/components/layout/index.js, packages/sui-studio/src/components/navigation/_style.scss, packages/sui-studio/src/components/navigation/index.js, packages/sui-studio/src/components/workbench/_style.scss, packages/sui-studio/src/styles/_settings.scss
Improve side panel navigation and header, especially for mobile
ISSUES CLOSED: #1490
The current navigation has a poor UX.
The side panel navigation and the header in Mobile were not optimal in SUI Studio.
* The button to show and hide the drawer is hidden on scroll
* The header is not fixed on top hence the user needs to scroll all the way up every time to change a component
* The font-size was too small
* The menu can't be collapsed on desktop
* etc
[#1490](https://github.com/SUI-Components/sui/issues/1490)
**BEFORE**
**AFTER**
https://user-images.githubusercontent.com/23620759/194775906-132d7b5a-1bca-4771-a211-f447b96b1a4e.mov
https://user-images.githubusercontent.com/23620759/194775559-5cedaaf4-7b8c-4fbb-a11b-39aaa08a3f0f.mov
=> refactor(packages/sui-studio): Improve navigation of the header

packages/sui-studio/src/components/documentation/markdown.css, packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/components/navigation/_style.scss, packages/sui-studio/src/components/workbench/_style.scss, packages/sui-studio/src/styles/_default.scss
Improve and standardise the hierarchy of the different tabs of Studio
ISSUES CLOSED: #1493
All elements should use the documentation library. It's pretty good chaos at this moment.
https://github.com/SUI-Components/docs-components
All elements of the different tabs should look like they belong to the same universe, check the images below, i.e. the tab "readme" is using a plain H1, very different from the tab Changelog.
❌ As it was until now
✅ This is how it looks like after this PR
[](https://github.com/SUI-Components/sui/issues/1493)
The styles of Studio need a HUGE review, I've just changed the very minimum, but it would be nice to give it a huge love
=> docs(packages/sui-studio): Improve and standardise hierarchy of texts

packages/sui-studio/src/components/demo/Tabs.js
Remove "THEMES" tab, the information is redundant
✅ I push as `feat` to force a new release
=> feat(packages/sui-studio): Remove title of the Themes tabs

packages/sui-domain/README.md, packages/sui-domain/src/EntryPointFactory.js, packages/sui-domain/test/common/EntryPointSpec.js, packages/sui-domain/test/common/fixtures/EmptyUseCaseWithLogger.js, packages/sui-domain/test/common/fixtures/factoryWithMultipleUseCasesAndLogger.js, packages/sui-domain/test/common/fixtures/factoryWithSingleUseCaseAndLogger.js
We want to allow developers inject a logger to the domain and empower them to log/monitor from domain.
```javascript
const logger = isClient
? createClientLogger()
: createServerLogger({req, team: 'sui-believers'})
const domain = new SuiDomain({logger})
```
=> feat(packages/sui-domain): allow inject logger from outside

packages/sui-studio/src/components/icons/index.js, packages/sui-studio/src/components/layout/_style.scss
`🔍 Show`
**Issue fixed with this PR**
https://github.com/SUI-Components/sui/issues/1500
The hamburger menu icon is not visible on mobile, although the button works as expected.
The button is always visible on Desktop, even when you open developer tools in Chrome. You need to test with a Mobile device.
=> fix(packages/sui-studio): Add a fill to the buttons icon

packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/components/layout/index.js
`🔍 Show`
**ISSUE CLOSED** #1503
The drawer should close by clicking outside of it (mobile only)
- There's an overlay $c-black at 10% 
- The user can close the drawer by tapping on the overlay
**Result of this PR:**
https://user-images.githubusercontent.com/23620759/196283304-22c6883c-8bb8-422f-b0a7-f31178a49055.mov
=> fix(packages/sui-studio): hide menu clicking on an overlay in mobile

packages/sui-studio/src/components/layout/_style.scss, packages/sui-studio/src/components/navigation/_style.scss
This commit solves issue #1501 and includes the following changes:
- updating the bottom padding of `.sui-StudioNav` to `80px`
- reducing the height of `.sui-Studio-sidebar` by the height of `NavHeader` that is `48px`
#1501
=> update bottom padding in NavBar menu to 80px and reduce the sidebar height by 48px

packages/sui-i18n/package.json, packages/sui-i18n/src/adapters/polyglot.js
Import `node-polyglot 0.43` code to our package.
Polyglot adapter is already being fully tested:
https://github.com/SUI-Components/sui/blob/master/packages/sui-i18n/test/polyglotSpec.js#L53 
Implements #1468 .
=> feat(packages/sui-i18n): import node-polyglot 0.43 to our package

packages/sui-theme/src/components/atom/input/_placeholders.scss, packages/sui-theme/src/components/atom/input/_settings.scss
Add new outline and outline-offset tokens for molecule select and autosuggest.
What we want to achieve (at motor) is avoiding selects to grow (by its border) when are focused, but keeping the UI.
NOW:
WHAT WE WANT TO ACHIEVE
=> feat(packages/sui-theme): add new molecule select and autosuggest tokens to theme

packages/sui-studio-utils/README.md, packages/sui-studio-utils/package.json, packages/sui-studio-utils/src/domain-builder/index.js, packages/sui-studio-utils/src/test/browser/browserSpec.js, packages/sui-studio-utils/src/test/common/domainBuilderSpec.js, packages/sui-studio-utils/src/test/common/index.js, packages/sui-studio-utils/src/test/server/serverSpec.js
Sometime we need to mock a config property in order to test different escenarios in a test or demo environment. In order to do this, we have added the possibility to mock the config when extending the domain itself.
```js
DomainBuilder.extend({
domain: {get: () => {}},
config: 'mocked-config'
})
```
=> feat(packages/sui-studio-utils): Be able to mock a domain config

packages/sui-domain/README.md, packages/sui-domain/src/EntryPointFactory.js
We want to allow developers inject a pde to the domain and empower them with FeaturesFlag and Experiement in domain.
```javascript
const pde = new OptimizelyAdapter({
optimizely,
userId,
applicationAttributes
})
const domain = new SuiDomain({pde})
```
=> Feat: Allow to Inject PDE in Domain

packages/sui-test-contract/README.md, packages/sui-test-contract/src/setup/utils.js, packages/sui-test-contract/test/server/setupSpec.js
Add `addMatchingRules` flag to add Pact matching rules to check contracts by value type.
Contract generated with  `addMatchingRules` flag:
```
{
description: 'A request for getting a garden',
providerState: 'I have a garden',
request: {
method: 'GET',
path: '/apples/garden',
headers: { host: 'localhost:8181' }
},
response: {
status: 200,
headers: { 'content-type': 'application/json' },
body: {
grassColor: '#34eb4f',
size: { height: 86, width: 96 },
trees: [
{ color: 'red', type: 'Fuji' },
{ color: 'green', type: 'Granny Smith' }
]
},
matchingRules: {
'$.body.grassColor': { match: 'type' },
'$.body.size.height': { match: 'type' },
'$.body.size.width': { match: 'type' },
'$.body.trees.0.color': { match: 'type' },
'$.body.trees.0.type': { match: 'type' },
'$.body.trees.1.color': { match: …
```
=> Feat: Add contract testing matching rules

packages/sui-studio/bin/migrations/component-files.js
This PR adds a new script to migrate existing components to a new structure with a `Component.js` file that contains all the component logic and an index re-export.
Related to #1518 discussion
Share your thoughts if you have any suggestions/feedback or if you find an edge case I'm missing here! 🙏
=> feat(packages/sui-studio): Add script to migrate component files to new structure

packages/sui-react-web-vitals/README.md, packages/sui-react-web-vitals/src/index.js
This PR:
- Try sending distribution metrics by default instead of timing one. This way percentiles could be computed across dimensions
- CLS value should be an integer since our logger can only compute integer values
=> feat(packages/sui-react-web-vitals): add distribution metric support

packages/sui-pde/src/adapters/optimizely/index.js
Fix execution errors on client trying to access to the `experimentsMap` key when a feature is not available anymore in Optimizely.
=> fix(packages/sui-pde): fix error on access to experiments map

packages/sui-i18n/README.md, packages/sui-i18n/src/i18n.js, packages/sui-i18n/test/i18nSpec.js
In **coches.net**, we need the thousands points in the prices to be visible so as not to create confusion in the users of the price they are seeing. Currently the RAE standard says that it should only be in the numbers of more than 5 digits, but we believe that it is necessary to improve the reading of the data that is also in the thousands.
in order to meet this UX requirement, we added the possibility of being able to pass to **`Intl.NumberFormat`** a specific configuration to customize the type of formatting of the numbers according to the configuration described in **https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#options.**
[MTR-66511](https://jira.ets.mpi-internal.com/browse/MTR-66511) & …
=> feat(packages/sui-i18n): Intl.FormatNumber extended options

packages/sui-pde/src/adapters/optimizely/index.js
In some rare cases, users and clients gets a CORS error when requesting for optimizely datafiles (https://cdn.optimizely.com/datafiles), so at this point the application crashes. The CORS error maybe is generated by some antivirus extensions, but we need to cover the code to prevent the error.
=> fix(packages/sui-pde): Prevent error when accessing to getOptimizelyConfig method

packages/sui-react-web-vitals/src/index.js
Replace wildcard `*` with `_` on pathname tag value so that it works when sending data to DataDog.
Having a pathname value of `/*` would yield the same data as a pathname value of `/`, which is not useful to analyze data from apps where pathnames `/*` and `/` mean different pages.
=> feat(packages/sui-react-web-vitals): replace wildcard on pathname tag value

packages/sui-test/bin/sui-test-browser.js
Fix `NaN` when use timeout param in client test.
From
Throw
Solution
=> fix(packages/sui-test): fix NaN when use timeout param in client test

packages/sui-polyfills/src/index.js
The `i18n.interpolate` function uses the `matchAll` method that does not work on Safari browsers older than version 13 and we have some users reporting errors because of this.
Add the `matchAll` polyfill
=> feat(packages/sui-polyfills): Added polyfill for matchAll

packages/sui-react-web-vitals/src/index.js
Add _routeid_ tag to Web Vitals Reporter as read from route `id` prop.
In order to provide an easier way to read Web Performance dashboards, we can now provide an `id` to a `route` that will be sent as `routeid` along with the other tags.
N/A
```
<Route path={HOME} id="home" getComponent={loadHomePage({appName})} />
```
=> feat(packages/sui-react-web-vitals): add routeid to reporter 

packages/sui-lint/package.json
We are using an incompatible version between eslint and stylelint-config-recommended-scss causing the following error:
=> fix(packages/sui-lint): Fix Unknown rule error when checking scss files

packages/sui-mono/package.json
Due to vulnerabilities on the `parse-url` package on versions < 8.1.0, an upgrade of `sui-mono`'s `git-url-parse` dependency is necessary. Major `13` is using `parse-url` major `8` so that would solve the security issue. We're publishing a beta version of `sui-mono` (`2.34.0-beta.0`) so we can safely test this [apparently breaking change](https://github.com/IonicaBizau/git-url-parse/releases/tag/13.0.0).
N/A
N/A
=> feat(packages/sui-mono): upgrade git-url-parse dependency to major 13

packages/sui-i18n/src/i18n.js
Fix missed key warning when i18n.url.
=> fix(packages/sui-i18n): fix missed key warning when i18n.url

packages/sui-lint/eslintrc.js
This PR applies jest rules only inside `__test__` folder for now
=> fix(packages/sui-lint): update jest rules

packages/sui-react-web-vitals/src/index.js
Adding necessary features so that `reportAllChanges: true` can be configured for specific metrics, which provides more fine-grained data about **CWV** metrics. By default, setting it for `LCP` and `INP`. Also, by importing the `web-vitals/attribution` build, we're also able to collect the elements of the page related to the recorded performance metrics.
Enabling custom thresholds for metrics via props to allow for fine-tuning of performance metrics, reduce noise on reporting or simply go with Google's defined thresholds for **CWV**.
n/a
=> feat(packages/sui-react-web-vitals): improve LCP and INP reporting

packages/sui-react-web-vitals/src/index.js
To fix some tag values not being collected by Datadog. 
Prior to this, data coming from pathnames as regexps was not being properly collected by Datadog.
n/a
=> fix(packages/sui-react-web-vitals): fix path normalizer

packages/sui-js/package.json
In this repository there is no this dependabot alert, but in Milanuncios web app repository dependabot is saying to upgrade qs.
Upgrade qs version for security in packages/sui-js
=> fix(packages/sui-js): upgrade qs version for security

packages/sui-mono/bin/sui-mono-release.js
Add the flag `--no-verify` to publish npm packages to improve the npm publish times.
=> feat(packages/sui-mono): add no-verify flag to publish npm packages

packages/sui-react-web-vitals/src/index.js
Improve pathname normalizer for routes with regexps as it's been an issue when collecting data.
As of now, a simple character replacement was applied to some characters. Now, all non-alphanumeric characters will be stripped of the regexp literal and sent as `pathname` to avoid missing data.  
Also, some minor variable renaming.
N/A
Before:
````
'/\\/.*\\x2D(\\d{4,9})\\x2D[a-z]{2,4}(vo|vn).aspx$/'
.replaceAll('*', '_')
.replace(/\\/g, '')
.replace(/\//g, '')
.replaceAll('._', ':');
OUTPUT:
':x2D(d{4,9})x2D[a-z]{2,4}(vo|vn).aspx$'
````
After:
````
'/\\/.*\\x2D(\\d{4,9})\\x2D[a-z]{2,4}(vo|vn).aspx$/'
.replace(/[^a-z0-9]/gi, '');
OUTPUT:
'x2Dd49x2Daz24vovnaspx'
````
=> Feat sui web vitals reporter simplify pathname normalizer when route has a RegExp

packages/sui-pde/README.md, packages/sui-pde/src/hooks/useFeature.js, packages/sui-pde/test/common/useFeatureSpec.js
In order to reduce unnecessary calls to Segment, the Experiment Viewed event is disabled by default.
If you need to track how many times your experiment has been viewed, you should set the shouldTrackExperimentViewed argument to true.
https://github.com/SUI-Components/sui/issues/1601
```js
const {isActive} =  useFeature(
'featureKey4',
{attribute1: 'value'},
undefined,
undefined,
true
)
```
=> [feature][sui-pde] Remove Experiment Viewed event by default.

packages/sui-ssr/hooks-types.js, packages/sui-ssr/server/hooksFactory/index.js, packages/sui-ssr/server/index.js, packages/sui-ssr/server/middlewares/ssr.js
Add the CSP report HTTP header and create a new link so each site can handle the report.
This header will be useful to us to know what resources we need and where they come from (the report will only contain resources from other domains), and this way, once we know what they are, we can create a list of allowed domains. Finally, we will use the CSP header which directly blocks any resources that are not in our allowed list.
More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only
https://github.com/SUI-Components/sui/assets/55990391/5999f95e-69e6-4aa4-a578-ec57d79b4840
=> feat(packages/sui-ssr): 

packages/sui-ssr/server/initialContextValue/index.js
In some web app implementations when is a new user then `cookies` on SSR will be `undefined`. If the web app doesn't inject an empty string, this line will fail on SSR.
@danilucaci reproduced the error on habitaclia
=> fix(packages/sui-ssr): safe check of type

packages/sui-react-router/src/Router.js
This PR avoid an extra re-render in the `Router` component. Normally this causes the application to re-render twice during first load
None
None
=> feat(packages/sui-react-router): avoid extra render during first load

packages/sui-react-web-vitals/src/index.js
=> feat(packages/sui-react-web-vitals): add visibilityState property

packages/sui-lint/.prettierrc.js
New screens are wider and have larger resolutions so it seems it's about time to be able to read our code on longer than 80-character lines.
Code chunk with 80-character lines:
Same code chunk with 120-character lines:
N/A
N/A
=> feat(packages/sui-lint): update line length to 120 characters

packages/sui-polyfills/package.json, packages/sui-polyfills/src/index.js
The append method doesn't work on Edge browsers older than version 17 and Chrome browsers older than version 54, which we still support in IJ.
Add append polyfill
=> feat(packages/sui-polyfills): add append polyfill

packages/sui-test-contract/bin/sui-test-contract-publish.js
When there are some errors executing `sui-test-contract publish` command in CI, the job where the command is being executed will never fail neither stop. So we need to explicitly throw an error.
=> feat(packages/sui-test-contract): make jobs execution halt on contract publish errors

packages/sui-bundler/webpack.config.server.dev.js
This PR adds an initial webpack configuration to enable Server-Side Rendering Fast Refresh support during development
=> feat(packages/sui-bundler): add server dev config

packages/sui-lint/bin/sui-lint-js.js
Sometimes (on CI, on a local environment...) you may want to skip some additional folders when running `sui-lint js`. On a monorepo, a common example could be the components' `demo` or the `test-e2e` folders. 
N/A
`npx @s-ui/lint js -- --ignore-patterns demo test-e2e`
...this will allow you to skip `demo` folders and sub-folders as well as `test-e2e`.
=> sui-lint ignore-patterns option

packages/sui-ssr/README.md, packages/sui-ssr/bin/sui-ssr-dev.js, packages/sui-ssr/bin/sui-ssr.js, packages/sui-ssr/package.json, packages/sui-ssr/server/utils/factory.js
This PR adds Server-Side rendering development support with Fast Refresh
```
Usage: sui-ssr-dev [options]
Options:
-L, --link-all [monorepo]     Link all packages inside of monorepo multipackage
-l, --link-package [package]  Replace each occurrence of this package with an absolute path to this folder (default: [])
-h, --help                    Display help for command
Examples:
$ sui-ssr dev
$ sui-ssr dev --link-package ./domain --link-all ./components
```
=> feat(packages/sui-ssr): add ssr dev mode

packages/sui-polyfills/src/index.js
Add a corejs polyfill for `String.prototype.{is,to}WellFormed` since it is not available in all browsers and we need it in Fotocasa.
Add a corejs polyfill for `String.prototype.{is,to}WellFormed` since it is not available in all browsers and we need it in Fotocasa.
=> :mag: feat(packages/sui-polyfills): add polyfill for string is|to wellFormed

packages/sui-domain/package.json, packages/sui-mockmock/package.json
Upgrade Axios to 1.6.2 to fix the [sui-domain](https://github.com/SUI-Components/sui/security/dependabot/37) and [sui-mockmock](https://github.com/SUI-Components/sui/security/dependabot/38) vulnerabilities
=> 🔍: Upgrade Axios to 1.6.2 to fix the sui-domain and sui-mockmock vulnerabilities

packages/sui-test/bin/mocha/register.js
SUI-TEST / MOCHA / ADV-UI
The adv-ui package was not in the babel build for mocha. This caused that when we imported adv-ui packages into our portals and wanted to run server tests, they crashed.
[SCMI-111632](https://jira.ets.mpi-internal.com/browse/SCMI-111632)
=> add adv-ui package to sui-test mocha compiler

packages/sui-bundler/webpack.config.client.dev.js, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.server.js
This PR uses `gzip` instead of `brotli`. Looks like `brotli` that when `brotli` is enabled webpack takes more time than with `gzip` to bootstrap
=> feat(packages/sui-bundler): use gzip compression

packages/sui-bundler/bin/sui-bundler-dev.js
This PR fixes small issue with sui studio because it doesn't have cache
None
=> fix(packages/sui-bundler): avoid setting key when there is no cache

packages/sui-mono/src/check.js
This PR solves the current issue we have in the master build: https://github.com/SUI-Components/sui/actions/runs/7500241868/job/20418527951#step:12:22
=> fix(packages/sui-mono): fix package name regex

packages/sui-test-contract/bin/sui-test-contract-publish.js
We need to have `GITHUB_HEAD_REF` and `GITHUB_REF_NAME` so they can be used to compute our `branch`, then `tags` values. 
Also, to make the publishing process more informative, we need to add the tags data to the output.
=> feat(packages/sui-test-contract): use GITHUB_HEAD_REF and GITHUB_REF_NAME and add Tags info on console logging

packages/sui-bundler/factories/createDevServerConfig.js
This PR add resources as static folder. The agreement of statics folders will be as follows:
- `/public`: Automatically generated folder for the build and ignored in git.
- `/statics`: Folder where the server itself will expose its content from the root. For example, it is useful for hosting sitemaps.xml, robots.txt, etc.
- `/resources`: Folder that will be synchronized with the application's S3 bucket and exposed through a CDN. For example, it is useful for hosting images, JSONs, PDFs, etc.
Important: Only place strictly necessary items in `/statics`; the majority should go in `/resources` to be served by a CDN and not consume server resources.
None
None
=> feat(packages/sui-bundler): add resources as static folder

packages/sui-mono/bin/sui-mono-changelog.js, packages/sui-mono/bin/sui-mono-release.js, packages/sui-mono/hosts/bitbucket.json, packages/sui-mono/hosts/github.json, packages/sui-mono/hosts/gitlab.json, packages/sui-mono/package.json, packages/sui-mono/src/check.js, packages/sui-mono/src/conventional-changelog-core.js, packages/sui-mono/src/conventional-changelog.js, packages/sui-mono/src/merge-config.js, packages/sui-mono/src/tags.js
This pull request accelerates the release process of the packages `@s-ui/mono release` by parallelizing the package bump and publication, which are the two steps that consume the most time in the entire process.
None
None
=> feat(packages/sui-mono): improve performance

packages/sui-js/src/hash/index.js
We are adding the sha256 hash method to sui-js utilities. This new function uses browser native methods so we are not coupling it to third-party libraries.
This method will be async, so we are naming it createAsyncSha256.
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#converting_a_digest_to_a_hex_string
import {createAsyncSha256} from '@s-ui/js/lib/hash'
const hashedValue = await createAsyncSha256(value)
=> feat(packages/sui-js): Add sha256 hash method

packages/sui-bundler/package.json, packages/sui-bundler/webpack.config.client.dev.js
Bringing *builder.io*'s [Hydration overlay](https://github.com/BuilderIO/hydration-overlay/) tool to help us debug hydration mismatch errors on dev environment.
Using `withHydrationOverlayWebpack` in web pack development configuration allows us to spot hydration mismatches and therefore prevent introducing potencial re-renderings on client and hence, performance issues.
This [additional change](https://github.com/SUI-Components/sui/pull/1740/files#diff-3c38d2c065de8c4205a1963bf98939999af9b4b6ff3826f15ce6cea72bb7c5ebR90) is necessary to make it work. The hydration mismatch overlay only shows up when it detects errors containing the words `hydration` or `hydrating` (see here https://github.com/BuilderIO/hydration-overlay/blob/661aa0e17a50777fe9d7222fe0759d84798b1c3e/packages/lib/src/hydratio …
=> Add Hydration Mismatch Overlay for dev mode

packages/sui-studio/bin/sui-studio-generate.js
Allow to ignore `__tests__` folder when a package is published
With that, we will avoid something like the screenshot below, allowing reduce the size of our packages
=> feat(packages/sui-studio): add __tests__ to npmignore

packages/sui-test/README.md, packages/sui-test/bin/karma/config.js
With this PR, it's possible to add custom aliases from the package.json config like this:
```json
{
"config": {
"sui-test": {
"client": {
"alias": {
"my-package": "path/to/my-package"
}
}
}
}
}
```
=> test(packages/sui-test): fix custom studio-utils alias

packages/sui-bundler/bin/sui-bundler-dev.js, packages/sui-bundler/factories/createDevServerConfig.js
Disabling errors overlay when on client dev environment.
Even though this overlay may be useful in some contexts, we're temporarily disabling it.
=> feat(packages/sui-bundler): set dev server overlay to false

packages/sui-studio/bin/sui-studio-dev.js, packages/sui-studio/workbench/src/components/Root/index.js
At Fotocasa Portal, we are integrating Jest into our tests. One of the problems we encountered was that we couldn't start the demos with studio-dev because it was searching for the path "test/index.test", leading to an error.
This PR solves the problem by detecting if the component has a Jest test and then changing the test alias to later import the correct path.
Demo on component with Jest test
=> feat(packages/sui-studio): Add jest compatibility with test path on studio-dev

packages/eslint-plugin-sui/src/index.js, packages/sui-lint/eslintrc.js, packages/sui-lint/eslintrc.ts.js
=> Enabled all Eslint rules

packages/sui-domain/src/DomainError.js, packages/sui-domain/src/index.js
This adds a new `DomainError` class to `@s-ui/domain` which is intended to be the base class for handling errors in the domain layer. This is part of the [Domain Error Handling agreements](https://docs.mpi-internal.com/scmspain/es-td-agreements/Frontend/agreements/domain/#error-handling) we have defined recently.
[Domain Error Handling Issue](https://github.mpi-internal.com/scmspain/es-td-agreements/issues/190)
[Using DomainError guide](https://docs.mpi-internal.com/scmspain/es-td-agreements/Frontend/guides/domain-error-handling/business-error-handling/)
=> feat(packages/sui-domain): Add DomainError class

packages/eslint-plugin-sui/src/rules/decorators.js
Rephrasing the message for this inlineError decorator rule.
Replacing this:
> the inlineError decorator should be always the first
for this:
> The inlineError decorator should always be closest to the execute method
=> feat(packages/eslint-plugin-sui): rephrase message for inlineErrorMissplace rule

packages/eslint-plugin-sui/src/index.js, packages/eslint-plugin-sui/src/rules/decorator-deprecated-remark-method.js, packages/eslint-plugin-sui/src/rules/decorator-deprecated.js, packages/eslint-plugin-sui/src/utils/decorators.js, packages/sui-decorators/src/decorators/deprecated/index.js, packages/sui-decorators/src/index.js, packages/sui-decorators/test/browser/DeprecatedSpec.js, packages/sui-decorators/test/server/DeprecatedSpec.js, packages/sui-lint/eslintrc.js
Frontend Tech Community has agreed to create, use, and standardize the `@Deprecated()` decorator. It will help us to manage the death code and monitor it to keep our code as clean as possible. 
Imagine you are refactoring a code, or disabling a functionality. How sure you are, that your code is not being used? For those cases, if you use the `@Deprecated()` decorator, you will be able to see a `console.warn` on your terminal or browser console (it's disabled on production by default). 
If you want to monitor the health of your code, this decorator brings you the possibility to integrate yourself into your application and send it to your desired platform. 
This decorator has 2 required parameters: 
- `key`: Used to enable you the possibility of monitoring and know how many times the …
=> feat(packages/sui-decorators): Create @Deprecated() decorator

packages/sui-js/README.md, packages/sui-js/src/string/parse-query-string.js, packages/sui-js/test/stringSpec.js
=> feat(packages/sui-js): parse query string allow sparse config

packages/sui-lint/eslintrc.js
Disables `AsyncInlineError` decorator rule temporarily to prevent duplication of imports that are causing lint errors. It seems the current linter configuration is replacing instances of `inlineError` with `AsyncInlineError` in edited files. However, it is also duplicating the import statement each time this change is made within the same file, leading to multiple import declarations and subsequent lint errors.
https://github.mpi-internal.com/scmspain/frontend-ma--web-app/actions/runs/7182952/job/22368775?pr=6097#step:5:57
=> fix(packages/sui-lint): disable decorator rule temporarily

packages/sui-pde/src/adapters/default.js, packages/sui-pde/src/adapters/optimizely/index.js, packages/sui-pde/src/adapters/optimizely/multiple.js, packages/sui-pde/src/hooks/useDecision.js, packages/sui-pde/src/pde.js, packages/sui-pde/test/common/useDecisionSpec.js
This PR:
- Fix an issue when consents are not accepted returning an object
- Fix issue where `ExperimentViewed` event was being sent for feature flags only
=> feat(packages/sui-pde): add decide listener

packages/lint-repository-sui/src/index.js, packages/lint-repository-sui/src/rules/jest-adoption.js
Create a rule to measure the jest adoption  on Fotocasa
=> feat(packages/lint-repository-sui): Add jest adoption rule to lint

packages/sui-decorators/src/decorators/tracer/index.js
Add error reporter to tracer decorator to log use cases errors.
=> feat(packages/sui-decorators): add error reporter to tracer decorator

package-lock.json, packages/sui-bundler/package.json, packages/sui-critical-css-middleware/package.json, packages/sui-critical-css/package.json, packages/sui-js/package.json, packages/sui-sass-loader/package.json, packages/sui-studio/package.json, packages/sui-svg/package.json, packages/sui-test-e2e/package.json, packages/sui-test/package.json
fix for different issues we have listed here: https://github.com/SUI-Components/sui/security/dependabot
=> fix security issues

package-lock.json, packages/sui-studio/bin/sui-studio-test.js, packages/sui-studio/package.json, packages/sui-test/bin/karma/index.js, packages/sui-test/bin/sui-test-browser.js
Add a command option `--no-coverage-inline` for the binary `sui-test browser` in order to save the coverage summary into a text file instead of attaching it at the end of the standard output.
=> FEAT (sui-test & sui-studio) binary option: no coverage inline

packages/sui-segment-wrapper/src/index.js, packages/sui-segment-wrapper/src/repositories/googleRepository.js, packages/sui-segment-wrapper/src/segmentWrapper.js, packages/sui-segment-wrapper/test/stubs.js
GA4 init event needs to be sent:
* just **once** per session (https://support.google.com/analytics/answer/9191807#session-counts)
* and only whenever the user **has accepted consents**.
=> feat(packages/sui-segment-wrapper): send init event once per session

packages/sui-segment-wrapper/src/events.js, packages/sui-segment-wrapper/src/index.js, packages/sui-segment-wrapper/src/repositories/googleRepository.js
The gtag config now was being loaded async due to the function to get the adobeCloudVisitorId and was causing problems when trying to retrieve the session_id outside this lib
Removed the adobeCloudVisitorId from GA4 since it is not needed any more and it was added for debugging
=> fix(packages/sui-segment-wrapper): Remove adobeCloudVisitorId from GA4

packages/sui-bundler/README.md, packages/sui-bundler/shared/module-rules-compiler.js
When trying to integrate the **SUI Semantic Tokens** library into Milanuncios, we encountered a requirement that forces us to add **TypeScript** to the project.
During the integration attempt, we detected a **bug**: styles in **SSR** are not being applied correctly and are only loading on the client side, causing a **visual jump**.
I isolated the TypeScript integration in the web app, and the problem was coming from here.  
It seems that when compiling and bundling with **TypeScript + SWC**, the `routes.js` files **are not including the styles** with **magic comments** in the server-side chunks. As a result, the styles only load on the client side, causing the jump.  
When reviewing the **SUI Bundler** bundling process, it looks like TypeScript follows a different path:  
🔍 [[Relevant …
=> feat(packages/sui-bundler): add disableTSLoader flag to control TypeScript loader usage

packages/sui-segment-wrapper/src/repositories/googleRepository.js, packages/sui-segment-wrapper/src/segmentWrapper.js, packages/sui-segment-wrapper/test/segmentWrapperSpec.js
We need to send to segment if the user has accepted or rejected the consent for analytics storage
=> feat(packages/sui-segment-wrapper): Added analytics_storage privacy state for segment

packages/sui-segment-wrapper/src/repositories/googleRepository.js, packages/sui-segment-wrapper/test/segmentWrapperSpec.js
Due to an error when user rejects consents that we do not fully understand, we decided to catch any error and reject the analytics_storage for those cases in order to unblock the problem as a workaround
=> feat(packages/sui-segment-wrapper): DENIE consent if it fails to retrieve it

packages/sui-segment-wrapper/src/universalId.js
Skip the _Universal ID_ retrieval from server side, since this function code is executed from the library entrypoint.
=> feat(packages/sui-segment-wrapper): skip universal id retrieval on server

package-lock.json, packages/sui-js-compiler/index.js, packages/sui-js-compiler/package.json
Upgrade TypeScript package from 5.0.4 to 5.8.2. After upgrading it, the test failed.
The problem is in the `compileTypes` function where options are passed directly to `createProgram` without properly parsing the TypeScript configuration.
Refactor TypeScript compilation to use `parseJsonConfigFileContent`
=> Upgrade typescript package

packages/sui-ssr/server/template/index.js
Prevent Cross-Site Scripting (XSS) vulnerabilities when parsing the initial prop
Using [$` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement)inserts the portion of the string that precedes the matched substring. When matching potentially dangerous content, this can include malicious code. We replaced the string-based replacement with a callback function as the second argument of the replace() method, which allow us full control over each match
=> fix(packages/sui-ssr): avoid XSS on SRR

packages/sui-bundler/webpack.config.client.dev.js, packages/sui-bundler/webpack.config.dev.js, packages/sui-bundler/webpack.config.prod.js
This PR adds proper context to sui bundler in case that the app is inside `app` folder for example, and not inside the root
=> feat(packages/sui-bundler): add proper context to bundler

packages/sui-segment-wrapper/src/repositories/xandrRepository.js, packages/sui-segment-wrapper/test/xandrRepositorySpec.js
Due to an undocumented requirement in the endpoint that retrieves the xandrId, and after opening a ticket with Xandr, we need to add '?consent=1' to the endpoint URL.
*before*
*after*
[XCOMP-14829](https://jira.ets.mpi-internal.com/browse/XCOMP-14829)
=> Update URL to retrieve xandrId to specify consent

packages/sui-mockmock/src/http/index.js
We need to iterate this tool because in a Vitest environment, condition `isNode` will be always `true` since `jsdom` or `happy-dom` are just browser emulators running on Node.
Suggestion to make this tool work when running client-side tests:
* Run on Vitest:`FORCE_SERVER_MOCKER=true npm run my-tests` // server mocker will be used
* Run on Vitest:`FORCE_SERVER_MOCKER=false npm run my-tests` // client mocker will be used
* Run on Mocha:`npm run my-tests` // server mocker will be used (default behavior)
* Run on Karma:`npm run my-tests` // client mocker will be used (default behavior)
=> feat(packages/sui-mockmock): allow to force server mocker usage

packages/sui-segment-wrapper/src/index.js, packages/sui-segment-wrapper/src/middlewares/source/pageData.js, packages/sui-segment-wrapper/test/middlewares/pageDataMiddlewareSpec.js
This PR add a experimental middleware to add page information to normal track events based on the latests page view. This especially useful when using GA4
=> feat(packages/sui-segment-wrapper): add pageData middleware

packages/sui-segment-wrapper/package.json, packages/sui-segment-wrapper/test/repositories/googleRepositorySpec.js
Added several tests for getCampaignDetais in segment-wrapper which I intend to improve soon, to ensure the funcionality remains working properly.
Also in order to fix test for segment-wrapper I added the Env variable "VERSION" to fix a the failing test: 
"sends an event with the actual context and traits when the consents are declined", which confusion the clientVersion from "segment-wrapper@0.0.0" getting "segment-wrapper@false"
=> test(packages/sui-segment-wrapper): Added tests for getCampaignDetais
